services:
  db:
    image: postgres:latest
    container_name: englishme-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2004
      POSTGRES_DB: englishme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: englishme-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/englishme_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 2004
      FIREBASE_CONFIG_PATH: classpath:serviceAccountKey.json
      ADMIN_EMAIL: admin@englishme.vn
      ADMIN_PASSWORD: admin123456
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}

volumes:
  postgres_data: