-- ── UNIT 10 — Dealing With Problems ──
-- ── UNIT 11 — The World Around Us ──
-- Each normal lesson: 7 practice + 7 quiz activities
-- Unit review: 10 quiz-only activities

-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║ BƯỚC 0 — DỌN SẠCH B1 units 10-11 CŨ (idempotent)                        ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B1' AND id IN ('b1-u10','b1-u11');

DELETE FROM learning_lesson_activities
 WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B1' AND unit_id IN ('b1-u10','b1-u11'));

DELETE FROM learning_lessons WHERE level_code = 'B1' AND unit_id IN ('b1-u10','b1-u11');

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 10 — Dealing With Problems
-- Theme: functional | Conditionals (2nd & 3rd), wish/if only
-- ══════════════════════════════════════════════════════════════════════════

-- Lesson 10-L1: Second Conditional
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u10-l1','B1','listening','b1-u10','normal',1,'Second Conditional','If + past simple, would + base verb — tình huống giả định hiện tại',10,20,70,'{}'::jsonb,
  '{"warmup":"Nếu bạn có một triệu đô, bạn sẽ làm gì? Câu hỏi này dùng điều kiện loại 2!",
    "objectives":["Dùng đúng cấu trúc điều kiện loại 2","Phân biệt điều kiện loại 1 (thực tế) và loại 2 (giả định)","Dùng were thay was trong mệnh đề if loại 2"],
    "grammarHtml":"<b>Điều kiện loại 2:</b> If + past simple, would + base verb<br>Dùng cho: tình huống giả định HIỆN TẠI hoặc TƯƠNG LAI không thực tế; lời khuyên lịch sự.<br>If I had more money, I would travel the world.<br>If I were you, I would apologise. (were cho mọi chủ ngữ — formal)<br><b>Đảo ngữ:</b> Were I you, I would... (formal)<br><b>So sánh với loại 1:</b><br>Type 1 (thực tế): If it rains, I will take an umbrella.<br>Type 2 (giả định): If it rained, I would take an umbrella.",
    "vocabBlock":[
      {"word":"hypothetical","ipa":"/ˌhaɪpəˈθetɪkl/","meaningVi":"giả thuyết, giả định","example":"This is a hypothetical situation."},
      {"word":"would","ipa":"/wʊd/","meaningVi":"sẽ (điều kiện)","example":"I would help if I could."},
      {"word":"If I were you","ipa":"/ɪf aɪ wɜː juː/","meaningVi":"Nếu tôi là bạn","example":"If I were you, I would tell the truth."},
      {"word":"afford","ipa":"/əˈfɔːd/","meaningVi":"có đủ tiền để","example":"If I could afford it, I would buy a car."}],
    "examples":[
      {"en":"If I had a car, I would drive to work.","vi":"Nếu tôi có xe, tôi sẽ lái xe đi làm."},
      {"en":"If I were you, I would talk to your manager.","vi":"Nếu tôi là bạn, tôi sẽ nói chuyện với quản lý."},
      {"en":"What would you do if you won the lottery?","vi":"Bạn sẽ làm gì nếu bạn thắng xổ số?"},
      {"en":"She would be happier if she exercised more.","vi":"Cô ấy sẽ hạnh phúc hơn nếu cô ấy tập thể dục nhiều hơn."}],
    "commonMistakes":["❌ If I would have more money... → ✅ If I had more money... (mệnh đề if không dùng would)","❌ If I was you... → ✅ If I were you... (were cho mọi chủ ngữ, formal)","❌ I would can help → ✅ I could help (would + base verb, không hai modal)"],
    "tips":["Mệnh đề if: past simple (không dùng would).","Mệnh đề kết quả: would/could/might + base verb.","If I were you = lời khuyên lịch sự."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u10-l1-p1','b1-u10-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu điều kiện loại 2 ĐÚNG:","options":[{"id":"a","text":"If I will have time, I will call you."},{"id":"b","text":"If I had time, I would call you."},{"id":"c","text":"If I would have time, I call you."}],"correctOptionId":"b","explanationVi":"Loại 2: If + past simple, would + base verb."}'::jsonb),
 ('b1-u10-l1-p2','b1-u10-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền vào chỗ trống: ''If I ___ (be) you, I would apologise.''","acceptedAnswers":["were"],"explanationVi":"If I were you — were cho mọi chủ ngữ."}'::jsonb),
 ('b1-u10-l1-p3','b1-u10-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối mệnh đề:","pairs":[{"left":"If I had a car","right":"I would drive to work."},{"left":"If I were you","right":"I would tell the truth."},{"left":"If she studied harder","right":"she would pass the exam."}],"explanationVi":"Ghép đúng từng cặp điều kiện."}'::jsonb),
 ('b1-u10-l1-p4','b1-u10-l1','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''If I would have more money, I would travel.''","acceptedAnswers":["If I had more money, I would travel."],"explanationVi":"Mệnh đề if không dùng would → past simple."}'::jsonb),
 ('b1-u10-l1-p5','b1-u10-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh: ''Nếu tôi là bạn, tôi sẽ xin lỗi.''","sourceText":"Nếu tôi là bạn, tôi sẽ xin lỗi.","acceptedAnswers":["If I were you, I would apologise.","If I were you, I would say sorry."],"explanationVi":"If I were you, I would apologise."}'::jsonb),
 ('b1-u10-l1-p6','b1-u10-l1','multiple_choice',6,'practice','medium',false,'{"question":"Câu điều kiện loại mấy? ''If it rains, I will stay home.''","options":[{"id":"a","text":"Loại 1"},{"id":"b","text":"Loại 2"},{"id":"c","text":"Loại 3"}],"correctOptionId":"a","explanationVi":"If + present, will + base verb → Loại 1 (thực tế)."}'::jsonb),
 ('b1-u10-l1-p7','b1-u10-l1','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành: ''She ___ (be) happier if she ___ (exercise) more.''","acceptedAnswers":["would be / exercised"],"explanationVi":"would + base verb / if + past simple."}'::jsonb),
 ('b1-u10-l1-q1','b1-u10-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG:","options":[{"id":"a","text":"If I had wings, I would fly."},{"id":"b","text":"If I would have wings, I fly."},{"id":"c","text":"If I have wings, I would fly."}],"correctOptionId":"a","explanationVi":"Loại 2: If + past simple, would + base verb."}'::jsonb),
 ('b1-u10-l1-q2','b1-u10-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''What ___ you do if you won the lottery?''","acceptedAnswers":["would"],"explanationVi":"Câu hỏi loại 2: would + S + base verb."}'::jsonb),
 ('b1-u10-l1-q3','b1-u10-l1','error_correction',10,'quiz','medium',true,'{"question":"Sửa lỗi: ''If I was you, I would tell her.''","acceptedAnswers":["If I were you, I would tell her."],"explanationVi":"If I were you (were, không phải was — formal)."}'::jsonb),
 ('b1-u10-l1-q4','b1-u10-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền vào chỗ trống: ''If he ___ (study) harder, he ___ (pass) the exam.''","acceptedAnswers":["studied / would pass"],"explanationVi":"If + past simple, would + base verb."}'::jsonb),
 ('b1-u10-l1-q5','b1-u10-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối loại điều kiện với đặc điểm:","pairs":[{"left":"Loại 1","right":"If + present, will + base"},{"left":"Loại 2","right":"If + past, would + base"}],"explanationVi":"Phân biệt loại 1 và loại 2."}'::jsonb),
 ('b1-u10-l1-q6','b1-u10-l1','translation',13,'quiz','hard',true,'{"question":"Dịch: ''Nếu cô ấy tập thể dục nhiều hơn, cô ấy sẽ cảm thấy tốt hơn.''","sourceText":"Nếu cô ấy tập thể dục nhiều hơn, cô ấy sẽ cảm thấy tốt hơn.","acceptedAnswers":["If she exercised more, she would feel better."],"explanationVi":"If + past simple, would + base verb."}'::jsonb),
 ('b1-u10-l1-q7','b1-u10-l1','sentence_ordering',14,'quiz','hard',true,'{"question":"Sắp xếp thành câu điều kiện loại 2 đúng:","tokens":["If","I","had","more","time","I","would","learn","guitar"],"correctOrder":[0,1,2,3,4,5,6,7,8],"explanationVi":"If I had more time, I would learn guitar."}'::jsonb);

-- Lesson 10-L2: Third Conditional
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u10-l2','B1','listening','b1-u10','normal',2,'Third Conditional','If + past perfect, would have + V3 — hối tiếc về quá khứ',10,20,70,'{}'::jsonb,
  '{"warmup":"Bạn đã bao giờ nghĩ ''Giá mà lúc đó tôi đã...'' chưa? Đó là điều kiện loại 3!",
    "objectives":["Dùng đúng cấu trúc điều kiện loại 3","Diễn đạt sự hối tiếc về quá khứ","Phân biệt loại 2 (giả định hiện tại) và loại 3 (giả định quá khứ)"],
    "grammarHtml":"<b>Điều kiện loại 3:</b> If + past perfect (had + V3), would have + V3<br>Dùng để nói về tình huống KHÔNG THỰC trong quá khứ — sự hối tiếc, kết quả khác đi.<br>If I had studied harder, I would have passed.<br>If she hadn''t been late, she would have caught the train.<br><b>Dạng ngắn:</b> I''d have known / she''d have come<br><b>Mixed conditional (nâng cao B1):</b> If + past perfect, would + base verb (quá khứ ảnh hưởng hiện tại):<br>If I had studied medicine, I would be a doctor now.",
    "vocabBlock":[
      {"word":"regret","ipa":"/rɪˈɡret/","meaningVi":"hối tiếc","example":"I regret not studying harder."},
      {"word":"would have","ipa":"/wʊd həv/","meaningVi":"đáng lẽ đã","example":"I would have called if I had known."},
      {"word":"had + V3","ipa":"/hæd/","meaningVi":"đã (past perfect)","example":"If I had known, I would have told you."},
      {"word":"otherwise","ipa":"/ˈʌðəwaɪz/","meaningVi":"nếu không thì","example":"I studied hard; otherwise, I would have failed."}],
    "examples":[
      {"en":"If I had saved more money, I would have bought a house.","vi":"Giá mà tôi tiết kiệm nhiều hơn, tôi đã mua được nhà."},
      {"en":"If she hadn''t missed the bus, she would have been on time.","vi":"Nếu cô ấy không lỡ xe buýt, cô ấy đã đến đúng giờ."},
      {"en":"We would have won if we had practised more.","vi":"Chúng tôi đã thắng nếu chúng tôi luyện tập nhiều hơn."},
      {"en":"If he had asked, I would have helped him.","vi":"Nếu anh ấy đã hỏi, tôi đã giúp anh ấy rồi."}],
    "commonMistakes":["❌ If I would have studied... → ✅ If I had studied... (mệnh đề if: past perfect, không dùng would)","❌ I would have pass → ✅ I would have passed (would have + V3)","❌ If she had not came → ✅ If she had not come (V3 của come = come)"],
    "tips":["Loại 3: If + had + V3, would have + V3.","Mệnh đề if: past perfect.","Mệnh đề kết quả: would/could/might + have + V3."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u10-l2-p1','b1-u10-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu điều kiện loại 3 ĐÚNG:","options":[{"id":"a","text":"If I had studied, I would have passed."},{"id":"b","text":"If I would have studied, I would have passed."},{"id":"c","text":"If I studied, I would have passed."}],"correctOptionId":"a","explanationVi":"Loại 3: If + past perfect, would have + V3."}'::jsonb),
 ('b1-u10-l2-p2','b1-u10-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền vào chỗ trống: ''If she ___ (not miss) the bus, she ___ (arrive) on time.''","acceptedAnswers":["hadn''t missed / would have arrived"],"explanationVi":"If + past perfect negative, would have + V3."}'::jsonb),
 ('b1-u10-l2-p3','b1-u10-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối mệnh đề if với kết quả:","pairs":[{"left":"If I had saved more","right":"I would have bought a house."},{"left":"If he had asked","right":"I would have helped him."},{"left":"If she hadn''t been late","right":"she would have caught the train."}],"explanationVi":"Ghép đúng từng cặp điều kiện."}'::jsonb),
 ('b1-u10-l2-p4','b1-u10-l2','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''If I would have known, I would have told you.''","acceptedAnswers":["If I had known, I would have told you."],"explanationVi":"Mệnh đề if: past perfect (không dùng would have)."}'::jsonb),
 ('b1-u10-l2-p5','b1-u10-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh: ''Giá mà tôi học chăm hơn, tôi đã đỗ rồi.''","sourceText":"Giá mà tôi học chăm hơn, tôi đã đỗ rồi.","acceptedAnswers":["If I had studied harder, I would have passed."],"explanationVi":"Loại 3: If + past perfect, would have + V3."}'::jsonb),
 ('b1-u10-l2-p6','b1-u10-l2','multiple_choice',6,'practice','medium',false,'{"question":"Câu nào là điều kiện loại 3?","options":[{"id":"a","text":"If I were you, I would go."},{"id":"b","text":"If I had been there, I would have helped."},{"id":"c","text":"If it rains, I will stay."}],"correctOptionId":"b","explanationVi":"If + past perfect → loại 3."}'::jsonb),
 ('b1-u10-l2-p7','b1-u10-l2','grammar_fill_blank',7,'practice','medium',false,'{"question":"Điền vào chỗ trống: ''We ___ (win) the game if we ___ (practise) more.''","acceptedAnswers":["would have won / had practised"],"explanationVi":"Loại 3 đảo mệnh đề."}'::jsonb),
 ('b1-u10-l2-q1','b1-u10-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG:","options":[{"id":"a","text":"If they had left earlier, they wouldn''t have been late."},{"id":"b","text":"If they would have left earlier, they wouldn''t have been late."},{"id":"c","text":"If they left earlier, they wouldn''t have been late."}],"correctOptionId":"a","explanationVi":"Loại 3: If + past perfect."}'::jsonb),
 ('b1-u10-l2-q2','b1-u10-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''If he ___ (study) medicine, he ___ (become) a doctor.''","acceptedAnswers":["had studied / would have become"],"explanationVi":"If + had + V3, would have + V3."}'::jsonb),
 ('b1-u10-l2-q3','b1-u10-l2','error_correction',10,'quiz','medium',true,'{"question":"Sửa lỗi: ''She would have pass if she had studied.''","acceptedAnswers":["She would have passed if she had studied."],"explanationVi":"would have + V3: passed."}'::jsonb),
 ('b1-u10-l2-q4','b1-u10-l2','translation',11,'quiz','medium',true,'{"question":"Dịch: ''Nếu anh ấy đã nói với tôi, tôi đã giúp anh ấy rồi.''","sourceText":"Nếu anh ấy đã nói với tôi, tôi đã giúp anh ấy rồi.","acceptedAnswers":["If he had told me, I would have helped him."],"explanationVi":"Loại 3."}'::jsonb),
 ('b1-u10-l2-q5','b1-u10-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối loại điều kiện với mệnh đề if:","pairs":[{"left":"Loại 2","right":"If + past simple"},{"left":"Loại 3","right":"If + past perfect"}],"explanationVi":"Phân biệt loại 2 và loại 3."}'::jsonb),
 ('b1-u10-l2-q6','b1-u10-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu điều kiện loại 3 đúng:","tokens":["If","she","had","known","she","would","have","come"],"correctOrder":[0,1,2,3,4,5,6,7],"explanationVi":"If she had known, she would have come."}'::jsonb),
 ('b1-u10-l2-q7','b1-u10-l2','multiple_choice',14,'quiz','hard',true,'{"question":"Mixed conditional ĐÚNG: (quá khứ ảnh hưởng hiện tại)","options":[{"id":"a","text":"If I had studied medicine, I would be a doctor now."},{"id":"b","text":"If I had studied medicine, I would have been a doctor now."},{"id":"c","text":"If I studied medicine, I would be a doctor now."}],"correctOptionId":"a","explanationVi":"Mixed: If + past perfect, would + base verb (hiện tại)."}'::jsonb);

-- Lesson 10-L3: Wish & If Only
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u10-l3','B1','listening','b1-u10','normal',3,'Wish & If Only','Ước muốn và hối tiếc',10,20,70,'{}'::jsonb,
  '{"warmup":"Bạn ước gì ngay lúc này? Bạn hối tiếc điều gì trong quá khứ?",
    "objectives":["Dùng wish + past simple cho ước muốn hiện tại","Dùng wish + past perfect cho hối tiếc quá khứ","Dùng wish + would cho ước muốn về thay đổi thói quen"],
    "grammarHtml":"<b>Wish cho hiện tại:</b> wish + past simple (giống loại 2)<br>I wish I had more time. (Ước tôi có nhiều thời gian hơn.)<br>I wish I were taller. (Ước tôi cao hơn.)<br><b>Wish cho quá khứ:</b> wish + past perfect (giống loại 3)<br>I wish I had studied harder. (Ước tôi đã học chăm hơn.)<br><b>Wish + would:</b> ước về thay đổi thói quen/hành động tương lai<br>I wish you wouldn''t make so much noise. (Ước bạn bớt ồn.)<br><b>If only</b> = wish (nhấn mạnh hơn):<br>If only I were taller! | If only I had listened!",
    "vocabBlock":[
      {"word":"wish","ipa":"/wɪʃ/","meaningVi":"ước muốn","example":"I wish I could fly."},
      {"word":"if only","ipa":"/ɪf ˈəʊnli/","meaningVi":"giá mà, ước gì","example":"If only I had more time!"},
      {"word":"regret","ipa":"/rɪˈɡret/","meaningVi":"hối tiếc","example":"I regret not calling sooner."},
      {"word":"were","ipa":"/wɜː/","meaningVi":"(dạng giả định của be)","example":"I wish I were younger."}],
    "examples":[
      {"en":"I wish I spoke Spanish. (Ước tôi nói được tiếng Tây Ban Nha.)","vi":"Ước tôi nói được tiếng Tây Ban Nha."},
      {"en":"I wish I had saved more money. (Ước tôi đã tiết kiệm hơn.)","vi":"Ước tôi đã tiết kiệm nhiều hơn."},
      {"en":"I wish you would stop complaining.","vi":"Tôi ước bạn ngừng phàn nàn đi."},
      {"en":"If only I had listened to my parents!","vi":"Giá mà tôi đã nghe lời bố mẹ!"}],
    "commonMistakes":["❌ I wish I would have more time. → ✅ I wish I had more time. (hiện tại → past simple)","❌ I wish I passed. → ✅ I wish I had passed. (quá khứ → past perfect)","❌ If only I listened! → ✅ If only I had listened! (hối tiếc quá khứ)"],
    "tips":["wish + past simple = ước muốn hiện tại (không thực).","wish + past perfect = hối tiếc quá khứ.","wish + would = ước về hành vi người khác."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u10-l3-p1','b1-u10-l3','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG: Ước mình cao hơn.","options":[{"id":"a","text":"I wish I am taller."},{"id":"b","text":"I wish I were taller."},{"id":"c","text":"I wish I would be taller."}],"correctOptionId":"b","explanationVi":"wish + past simple (were): ước muốn hiện tại."}'::jsonb),
 ('b1-u10-l3-p2','b1-u10-l3','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền vào chỗ trống: ''I wish I ___ (study) harder last year.''","acceptedAnswers":["had studied"],"explanationVi":"Hối tiếc quá khứ: wish + past perfect."}'::jsonb),
 ('b1-u10-l3-p3','b1-u10-l3','vocabulary_match',3,'practice','easy',false,'{"question":"Nối cấu trúc với ý nghĩa:","pairs":[{"left":"wish + past simple","right":"ước muốn hiện tại"},{"left":"wish + past perfect","right":"hối tiếc quá khứ"},{"left":"wish + would","right":"ước thay đổi thói quen"}],"explanationVi":"Phân biệt ba cấu trúc wish."}'::jsonb),
 ('b1-u10-l3-p4','b1-u10-l3','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''I wish I would have more time.''","acceptedAnswers":["I wish I had more time."],"explanationVi":"wish + past simple cho ước muốn hiện tại."}'::jsonb),
 ('b1-u10-l3-p5','b1-u10-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh: ''Ước tôi đã nói chuyện với cô ấy.''","sourceText":"Ước tôi đã nói chuyện với cô ấy.","acceptedAnswers":["I wish I had talked to her.","I wish I had spoken to her."],"explanationVi":"Hối tiếc quá khứ: wish + past perfect."}'::jsonb),
 ('b1-u10-l3-p6','b1-u10-l3','multiple_choice',6,'practice','medium',false,'{"question":"Chọn câu ''if only'' ĐÚNG: Giá mà tôi đã nghe lời họ!","options":[{"id":"a","text":"If only I listen to them!"},{"id":"b","text":"If only I had listened to them!"},{"id":"c","text":"If only I listened to them!"}],"correctOptionId":"b","explanationVi":"Hối tiếc quá khứ: if only + past perfect."}'::jsonb),
 ('b1-u10-l3-p7','b1-u10-l3','grammar_fill_blank',7,'practice','medium',false,'{"question":"Điền vào chỗ trống: ''I wish you ___ (stop) making so much noise.''","acceptedAnswers":["would stop"],"explanationVi":"Ước về thói quen người khác: wish + would."}'::jsonb),
 ('b1-u10-l3-q1','b1-u10-l3','multiple_choice',8,'quiz','easy',true,'{"question":"Câu nào diễn đạt ước muốn hiện tại ĐÚNG?","options":[{"id":"a","text":"I wish I had more time."},{"id":"b","text":"I wish I had had more time."},{"id":"c","text":"I wish I will have more time."}],"correctOptionId":"a","explanationVi":"wish + past simple = ước muốn hiện tại."}'::jsonb),
 ('b1-u10-l3-q2','b1-u10-l3','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''If only I ___ (not say) that!''","acceptedAnswers":["hadn''t said"],"explanationVi":"Hối tiếc quá khứ: if only + past perfect."}'::jsonb),
 ('b1-u10-l3-q3','b1-u10-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Chọn câu hối tiếc quá khứ ĐÚNG:","options":[{"id":"a","text":"I wish I didn''t eat so much."},{"id":"b","text":"I wish I hadn''t eaten so much."},{"id":"c","text":"I wish I won''t eat so much."}],"correctOptionId":"b","explanationVi":"Hối tiếc quá khứ: wish + past perfect."}'::jsonb),
 ('b1-u10-l3-q4','b1-u10-l3','translation',11,'quiz','medium',true,'{"question":"Dịch: ''Ước gì bạn không nói vậy.''","sourceText":"Ước gì bạn không nói vậy.","acceptedAnswers":["I wish you hadn''t said that.","If only you hadn''t said that."],"explanationVi":"Hối tiếc quá khứ."}'::jsonb),
 ('b1-u10-l3-q5','b1-u10-l3','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối câu với loại wish:","pairs":[{"left":"I wish I were taller.","right":"ước muốn hiện tại"},{"left":"I wish I had studied.","right":"hối tiếc quá khứ"},{"left":"I wish you would stop.","right":"ước thay đổi thói quen"}],"explanationVi":"Phân biệt ba loại."}'::jsonb),
 ('b1-u10-l3-q6','b1-u10-l3','error_correction',13,'quiz','hard',true,'{"question":"Sửa lỗi: ''I wish I passed the exam.'' (nói về kỳ thi đã qua)","acceptedAnswers":["I wish I had passed the exam."],"explanationVi":"Hối tiếc quá khứ: wish + past perfect."}'::jsonb),
 ('b1-u10-l3-q7','b1-u10-l3','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền vào chỗ trống: ''If only I ___ (take) that job offer!''","acceptedAnswers":["had taken"],"explanationVi":"Hối tiếc quá khứ: if only + had + V3."}'::jsonb);

-- Lesson 10-L4: Reading — A Bad Day
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u10-l4','B1','listening','b1-u10','normal',4,'A Very Bad Day','Đọc hiểu: Ngày tệ nhất và bài học rút ra',10,20,70,'{}'::jsonb,
  '{"warmup":"Bạn đã bao giờ có một ngày mọi thứ đều đi sai không?",
    "objectives":["Đọc hiểu đoạn văn B1 về sự hối tiếc và bài học","Nhận biết điều kiện loại 2, 3 và wish trong văn bản","Ôn từ vựng về vấn đề và giải pháp"],
    "vocabBlock":[
      {"word":"oversleep","ipa":"/ˌəʊvəˈsliːp/","meaningVi":"ngủ quên","example":"I overslept and missed the bus."},
      {"word":"deadline","ipa":"/ˈdedlaɪn/","meaningVi":"hạn chót","example":"I missed the project deadline."},
      {"word":"consequence","ipa":"/ˈkɒnsɪkwəns/","meaningVi":"hậu quả","example":"There were serious consequences."},
      {"word":"set an alarm","ipa":"/set ən əˈlɑːm/","meaningVi":"đặt báo thức","example":"I should have set an alarm."}],
    "examples":[
      {"en":"Last Monday was the worst day of Lan''s working life. She overslept because she had forgotten to set her alarm. If she had set her alarm, she would have woken up on time. She missed the 7 o''clock bus. If she hadn''t overslept, she wouldn''t have missed the bus. She arrived at work one hour late and her manager was angry. She wished she had gone to bed earlier the night before. At the meeting, she realised she had left her presentation at home. If she had checked her bag the night before, she would have remembered it. ''I wish I were more organised,'' she thought. ''If only I had prepared better!'' That evening, she made a list of things to do the next morning so that she would never have such a bad day again. She decided that if she had one like that again, she would ask her colleague for help instead of trying to manage alone.","vi":"Thứ Hai tuần trước là ngày tệ nhất trong cuộc đời làm việc của Lan. Cô ngủ quên vì đã quên đặt báo thức. Nếu cô đặt báo thức, cô đã thức dậy đúng giờ. Cô lỡ xe buýt 7 giờ. Nếu cô không ngủ quên, cô đã không lỡ xe. Cô đến cơ quan muộn một tiếng và quản lý nổi giận. Cô ước mình đã đi ngủ sớm hơn tối hôm trước. Tại cuộc họp, cô nhận ra mình đã để quên bài thuyết trình ở nhà. Nếu cô kiểm tra túi vào tối hôm trước, cô đã nhớ mang theo. ''Ước gì mình gọn gàng hơn,'' cô nghĩ. ''Giá mà mình chuẩn bị kỹ hơn!'' Buổi tối, cô lập danh sách việc cần làm vào sáng hôm sau để không bao giờ có ngày tệ như vậy nữa. Cô quyết định nếu có ngày như thế nữa, cô sẽ nhờ đồng nghiệp giúp thay vì cố tự xử lý một mình."}],
    "commonMistakes":["Chú ý phân biệt các loại điều kiện và wish trong bài đọc."],
    "tips":["Tìm các cấu trúc: If + past perfect... would have; wish + past perfect; if only."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u10-l4-p1','b1-u10-l4','multiple_choice',1,'practice','easy',false,'{"question":"Tại sao Lan ngủ quên?","options":[{"id":"a","text":"Cô bị ốm"},{"id":"b","text":"Cô quên đặt báo thức"},{"id":"c","text":"Báo thức bị hỏng"}],"correctOptionId":"b","explanationVi":"''forgotten to set her alarm.''"}'::jsonb),
 ('b1-u10-l4-p2','b1-u10-l4','multiple_choice',2,'practice','easy',false,'{"question":"Lan quên mang gì đến cơ quan?","options":[{"id":"a","text":"Chìa khóa"},{"id":"b","text":"Bài thuyết trình"},{"id":"c","text":"Máy tính"}],"correctOptionId":"b","explanationVi":"''left her presentation at home.''"}'::jsonb),
 ('b1-u10-l4-p3','b1-u10-l4','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"oversleep","right":"ngủ quên"},{"left":"deadline","right":"hạn chót"},{"left":"consequence","right":"hậu quả"},{"left":"set an alarm","right":"đặt báo thức"}],"explanationVi":"Ghép đúng từng từ."}'::jsonb),
 ('b1-u10-l4-p4','b1-u10-l4','multiple_choice',4,'practice','medium',false,'{"question":"Loại điều kiện nào trong câu: ''If she had set her alarm, she would have woken up on time.''?","options":[{"id":"a","text":"Loại 1"},{"id":"b","text":"Loại 2"},{"id":"c","text":"Loại 3"}],"correctOptionId":"c","explanationVi":"If + past perfect → loại 3."}'::jsonb),
 ('b1-u10-l4-p5','b1-u10-l4','grammar_fill_blank',5,'practice','medium',false,'{"question":"Hoàn thành theo bài: ''She wished she ___ (go) to bed earlier.''","acceptedAnswers":["had gone"],"explanationVi":"wish + past perfect: wished she had gone."}'::jsonb),
 ('b1-u10-l4-p6','b1-u10-l4','multiple_choice',6,'practice','medium',false,'{"question":"Lan quyết định làm gì để không tái diễn?","options":[{"id":"a","text":"Mua báo thức mới"},{"id":"b","text":"Lập danh sách việc cần làm"},{"id":"c","text":"Đi làm sớm hơn"}],"correctOptionId":"b","explanationVi":"''made a list of things to do the next morning.''"}'::jsonb),
 ('b1-u10-l4-p7','b1-u10-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành: ''If she ___ (check) her bag, she ___ (remember) the presentation.''","acceptedAnswers":["had checked / would have remembered"],"explanationVi":"Loại 3: If + past perfect, would have + V3."}'::jsonb),
 ('b1-u10-l4-q1','b1-u10-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Câu ''I wish I were more organised'' diễn đạt điều gì?","options":[{"id":"a","text":"Hối tiếc quá khứ"},{"id":"b","text":"Ước muốn hiện tại"},{"id":"c","text":"Kế hoạch tương lai"}],"correctOptionId":"b","explanationVi":"wish + past simple = ước muốn hiện tại."}'::jsonb),
 ('b1-u10-l4-q2','b1-u10-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Câu ''If only I had prepared better!'' diễn đạt điều gì?","options":[{"id":"a","text":"Điều kiện tương lai"},{"id":"b","text":"Hối tiếc quá khứ"},{"id":"c","text":"Ước muốn hiện tại"}],"correctOptionId":"b","explanationVi":"if only + past perfect = hối tiếc quá khứ."}'::jsonb),
 ('b1-u10-l4-q3','b1-u10-l4','grammar_fill_blank',10,'quiz','medium',true,'{"question":"Hoàn thành điều kiện loại 3: ''If she ___ (not oversleep), she ___ (not miss) the bus.''","acceptedAnswers":["hadn''t overslept / wouldn''t have missed"],"explanationVi":"Loại 3 phủ định."}'::jsonb),
 ('b1-u10-l4-q4','b1-u10-l4','multiple_choice',11,'quiz','medium',true,'{"question":"Lan sẽ làm gì nếu có ngày tệ nữa?","options":[{"id":"a","text":"Ở nhà"},{"id":"b","text":"Nhờ đồng nghiệp giúp"},{"id":"c","text":"Xin nghỉ phép"}],"correctOptionId":"b","explanationVi":"''would ask her colleague for help.''"}'::jsonb),
 ('b1-u10-l4-q5','b1-u10-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Câu nào mô tả đúng nhất nội dung bài đọc?","options":[{"id":"a","text":"Lan thích ngày thứ Hai"},{"id":"b","text":"Lan học từ những sai lầm và lập kế hoạch cải thiện"},{"id":"c","text":"Lan quyết định nghỉ việc"}],"correctOptionId":"b","explanationVi":"Bài học rút ra từ ngày tệ."}'::jsonb),
 ('b1-u10-l4-q6','b1-u10-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"oversleep","right":"ngủ quên"},{"left":"consequence","right":"hậu quả"},{"left":"set an alarm","right":"đặt báo thức"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b1-u10-l4-q7','b1-u10-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chuyển sang wish: ''She didn''t prepare well.'' → She wished she ___.","acceptedAnswers":["had prepared well","had prepared better"],"explanationVi":"Hối tiếc quá khứ: wish + past perfect."}'::jsonb);

-- Lesson 10-L5: Unit Review
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u10-l5','B1','listening','b1-u10','unit_review',5,'Unit 10 Review','Ôn tập Unit 10: Dealing With Problems',12,30,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 10: điều kiện loại 2, loại 3 và wish/if only.","objectives":["Tổng hợp can-do Unit 10","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u10-l5-q1','b1-u10-l5','multiple_choice',1,'quiz','easy',true,'{"question":"Chọn câu điều kiện loại 2 ĐÚNG:","options":[{"id":"a","text":"If I had a car, I would drive."},{"id":"b","text":"If I would have a car, I drive."},{"id":"c","text":"If I have a car, I would drive."}],"correctOptionId":"a","explanationVi":"Loại 2: If + past simple, would + base verb."}'::jsonb),
 ('b1-u10-l5-q2','b1-u10-l5','grammar_fill_blank',2,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''If I ___ (be) you, I would talk to her.''","acceptedAnswers":["were"],"explanationVi":"If I were you — were cho mọi chủ ngữ."}'::jsonb),
 ('b1-u10-l5-q3','b1-u10-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Chọn câu điều kiện loại 3 ĐÚNG:","options":[{"id":"a","text":"If she had known, she would have come."},{"id":"b","text":"If she would have known, she would come."},{"id":"c","text":"If she knew, she would have come."}],"correctOptionId":"a","explanationVi":"Loại 3: If + past perfect, would have + V3."}'::jsonb),
 ('b1-u10-l5-q4','b1-u10-l5','error_correction',4,'quiz','medium',true,'{"question":"Sửa lỗi: ''I wish I would have more free time.''","acceptedAnswers":["I wish I had more free time."],"explanationVi":"wish + past simple = ước muốn hiện tại."}'::jsonb),
 ('b1-u10-l5-q5','b1-u10-l5','grammar_fill_blank',5,'quiz','medium',true,'{"question":"Điền vào chỗ trống: ''I wish I ___ (not say) that to her.''","acceptedAnswers":["hadn''t said"],"explanationVi":"Hối tiếc quá khứ: wish + past perfect."}'::jsonb),
 ('b1-u10-l5-q6','b1-u10-l5','multiple_choice',6,'quiz','medium',true,'{"question":"Câu nào là ''if only'' ĐÚNG?","options":[{"id":"a","text":"If only I listen to them!"},{"id":"b","text":"If only I had listened to them!"},{"id":"c","text":"If only I listened to them!"}],"correctOptionId":"b","explanationVi":"Hối tiếc quá khứ: if only + past perfect."}'::jsonb),
 ('b1-u10-l5-q7','b1-u10-l5','translation',7,'quiz','medium',true,'{"question":"Dịch: ''Giá mà tôi đã học y khoa.''","sourceText":"Giá mà tôi đã học y khoa.","acceptedAnswers":["If only I had studied medicine.","I wish I had studied medicine."],"explanationVi":"Hối tiếc quá khứ."}'::jsonb),
 ('b1-u10-l5-q8','b1-u10-l5','multiple_choice',8,'quiz','hard',true,'{"question":"Câu nào là mixed conditional ĐÚNG?","options":[{"id":"a","text":"If I had taken that job, I would be rich now."},{"id":"b","text":"If I took that job, I would have been rich."},{"id":"c","text":"If I would have taken that job, I would be rich."}],"correctOptionId":"a","explanationVi":"Mixed: If + past perfect, would + base verb (hiện tại)."}'::jsonb),
 ('b1-u10-l5-q9','b1-u10-l5','error_correction',9,'quiz','medium',true,'{"question":"Sửa lỗi: ''If they would have called, we would have known.''","acceptedAnswers":["If they had called, we would have known."],"explanationVi":"Mệnh đề if: past perfect (không would have)."}'::jsonb),
 ('b1-u10-l5-q10','b1-u10-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Điền vào chỗ trống: ''If she ___ (study) harder, she ___ (pass) the exam.'' (Loại 3)","acceptedAnswers":["had studied / would have passed"],"explanationVi":"Loại 3: had + V3 / would have + V3."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b1-u10-l5' WHERE id = 'b1-u10';

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 11 — The World Around Us
-- Theme: environment | Passive voice (present/past/perfect), causative have/get
-- ══════════════════════════════════════════════════════════════════════════

-- Lesson 11-L1: Passive Voice — Present & Past
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u11-l1','B1','reading','b1-u11','normal',1,'Passive Voice — Present & Past','be + V3; by agent; when to use passive',10,20,70,'{}'::jsonb,
  '{"warmup":"Ai xây dựng tháp Eiffel? Bạn có thể nói cả hai cách: ''Gustave Eiffel built it'' hoặc ''It was built by Gustave Eiffel.'' Cách thứ hai là bị động!",
    "objectives":["Hình thành câu bị động thì hiện tại đơn và quá khứ đơn","Dùng by để chỉ tác nhân","Biết khi nào dùng bị động thay chủ động"],
    "grammarHtml":"<b>Câu bị động:</b> Object + be + V3 (+ by + agent)<br><b>Hiện tại đơn bị động:</b> is/are + V3<br>English is spoken in many countries.<br><b>Quá khứ đơn bị động:</b> was/were + V3<br>The Eiffel Tower was built in 1889.<br><b>Khi dùng bị động:</b><br>• Không biết ai làm: My bike was stolen.<br>• Không quan trọng ai làm: The road is repaired every year.<br>• Nhấn mạnh tân ngữ: The award was given to her.<br><b>By + agent:</b> chỉ thêm khi tác nhân quan trọng.<br>The book was written by Hemingway.",
    "vocabBlock":[
      {"word":"passive","ipa":"/ˈpæsɪv/","meaningVi":"bị động","example":"English is spoken here."},
      {"word":"be + V3","ipa":"/biː/","meaningVi":"cấu trúc bị động","example":"It was made in Vietnam."},
      {"word":"by","ipa":"/baɪ/","meaningVi":"bởi (tác nhân)","example":"The film was directed by Kubrick."},
      {"word":"agent","ipa":"/ˈeɪdʒənt/","meaningVi":"tác nhân","example":"The by-agent is often omitted."}],
    "examples":[
      {"en":"Rice is grown in many Asian countries.","vi":"Lúa được trồng ở nhiều nước châu Á."},
      {"en":"The bridge was built in 1960.","vi":"Cây cầu được xây dựng năm 1960."},
      {"en":"My phone was stolen on the bus.","vi":"Điện thoại tôi bị đánh cắp trên xe buýt."},
      {"en":"The rules are explained by the teacher.","vi":"Các quy tắc được giải thích bởi giáo viên."}],
    "commonMistakes":["❌ The book is write by... → ✅ The book is written by... (V3, không base verb)","❌ Rice is grown by farmers in many countries. → Thêm by chỉ khi cần nhấn mạnh tác nhân.","❌ My bike is stolen yesterday. → ✅ My bike was stolen yesterday. (quá khứ → was)"],
    "tips":["Bị động = be (đúng thì) + V3.","by + agent: chỉ thêm khi cần thiết.","Quá khứ bị động: was/were + V3."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u11-l1-p1','b1-u11-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu bị động ĐÚNG (hiện tại đơn):","options":[{"id":"a","text":"English speak in many countries."},{"id":"b","text":"English is spoken in many countries."},{"id":"c","text":"English is speak in many countries."}],"correctOptionId":"b","explanationVi":"Bị động hiện tại: is/are + V3."}'::jsonb),
 ('b1-u11-l1-p2','b1-u11-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chuyển sang bị động: ''They built the school in 1990.'' → The school ___ in 1990.","acceptedAnswers":["was built"],"explanationVi":"Quá khứ bị động: was/were + V3."}'::jsonb),
 ('b1-u11-l1-p3','b1-u11-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối câu chủ động với câu bị động:","pairs":[{"left":"They grow rice here.","right":"Rice is grown here."},{"left":"Someone stole my bag.","right":"My bag was stolen."},{"left":"A teacher explains the rules.","right":"The rules are explained by a teacher."}],"explanationVi":"Ghép đúng từng cặp."}'::jsonb),
 ('b1-u11-l1-p4','b1-u11-l1','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''The letter is write every day.''","acceptedAnswers":["The letter is written every day."],"explanationVi":"Bị động: is + V3 (written, không write)."}'::jsonb),
 ('b1-u11-l1-p5','b1-u11-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh (bị động): ''Phở được ăn khắp Việt Nam.''","sourceText":"Phở được ăn khắp Việt Nam.","acceptedAnswers":["Pho is eaten all over Vietnam.","Pho is eaten throughout Vietnam."],"explanationVi":"Bị động hiện tại: is + V3."}'::jsonb),
 ('b1-u11-l1-p6','b1-u11-l1','multiple_choice',6,'practice','medium',false,'{"question":"Khi nào KHÔNG cần thêm by + agent?","options":[{"id":"a","text":"Khi tác nhân quan trọng"},{"id":"b","text":"Khi không biết hoặc không quan trọng ai làm"},{"id":"c","text":"Khi câu ở quá khứ"}],"correctOptionId":"b","explanationVi":"by + agent chỉ thêm khi cần thiết."}'::jsonb),
 ('b1-u11-l1-p7','b1-u11-l1','grammar_fill_blank',7,'practice','medium',false,'{"question":"Chuyển sang bị động: ''Hemingway wrote this novel.'' → This novel ___ by Hemingway.","acceptedAnswers":["was written"],"explanationVi":"Quá khứ bị động: was + V3."}'::jsonb),
 ('b1-u11-l1-q1','b1-u11-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Câu bị động ĐÚNG (quá khứ đơn):","options":[{"id":"a","text":"The bridge was builded in 1960."},{"id":"b","text":"The bridge was built in 1960."},{"id":"c","text":"The bridge is built in 1960."}],"correctOptionId":"b","explanationVi":"Quá khứ bị động: was + V3 (built)."}'::jsonb),
 ('b1-u11-l1-q2','b1-u11-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''French ___ (speak) in many African countries.''","acceptedAnswers":["is spoken"],"explanationVi":"Bị động hiện tại: is + V3."}'::jsonb),
 ('b1-u11-l1-q3','b1-u11-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Chuyển câu: ''People make silk in Hội An.'' → Silk ___ in Hội An.","options":[{"id":"a","text":"is make"},{"id":"b","text":"is made"},{"id":"c","text":"was made"}],"correctOptionId":"b","explanationVi":"Bị động hiện tại: is made."}'::jsonb),
 ('b1-u11-l1-q4','b1-u11-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chuyển sang bị động: ''Someone repaired the car.'' → The car ___.","acceptedAnswers":["was repaired"],"explanationVi":"Quá khứ bị động: was + V3."}'::jsonb),
 ('b1-u11-l1-q5','b1-u11-l1','error_correction',12,'quiz','medium',true,'{"question":"Sửa lỗi: ''The film is direct by Nolan.''","acceptedAnswers":["The film is directed by Nolan."],"explanationVi":"Bị động: is + V3 (directed)."}'::jsonb),
 ('b1-u11-l1-q6','b1-u11-l1','translation',13,'quiz','hard',true,'{"question":"Dịch: ''Chùa Một Cột được xây dựng vào thế kỷ 11.''","sourceText":"Chùa Một Cột được xây dựng vào thế kỷ 11.","acceptedAnswers":["The One Pillar Pagoda was built in the 11th century."],"explanationVi":"Quá khứ bị động: was built."}'::jsonb),
 ('b1-u11-l1-q7','b1-u11-l1','sentence_ordering',14,'quiz','hard',true,'{"question":"Sắp xếp thành câu bị động đúng:","tokens":["The","rules","are","explained","by","the","teacher"],"correctOrder":[0,1,2,3,4,5,6],"explanationVi":"The rules are explained by the teacher."}'::jsonb);

-- Lesson 11-L2: Passive Voice — Present Perfect & Future
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u11-l2','B1','reading','b1-u11','normal',2,'Passive — Perfect & Future','have been + V3; will be + V3',10,20,70,'{}'::jsonb,
  '{"warmup":"Tin tức thường dùng bị động nhiều. ''Three people have been arrested.'' ''A new law will be introduced.''",
    "objectives":["Dùng bị động thì hiện tại hoàn thành: have/has been + V3","Dùng bị động thì tương lai: will be + V3","Nhận biết bị động trong văn bản tin tức"],
    "grammarHtml":"<b>Hiện tại hoàn thành bị động:</b> have/has been + V3<br>Three people have been arrested.<br>The project has been completed.<br><b>Tương lai bị động:</b> will be + V3<br>A new hospital will be built next year.<br>The results will be announced tomorrow.<br><b>Bị động tiếp diễn:</b> is/are being + V3 (hiện tại)<br>The road is being repaired.<br><b>Tổng hợp:</b><br>Present simple: is/are + V3<br>Past simple: was/were + V3<br>Present perfect: have/has been + V3<br>Future: will be + V3",
    "vocabBlock":[
      {"word":"announce","ipa":"/əˈnaʊns/","meaningVi":"công bố","example":"The results will be announced."},
      {"word":"complete","ipa":"/kəmˈpliːt/","meaningVi":"hoàn thành","example":"The project has been completed."},
      {"word":"arrest","ipa":"/əˈrest/","meaningVi":"bắt giữ","example":"Two suspects have been arrested."},
      {"word":"introduce","ipa":"/ˌɪntrəˈdjuːs/","meaningVi":"giới thiệu, ban hành","example":"New rules will be introduced."}],
    "examples":[
      {"en":"Five people have been rescued from the flood.","vi":"Năm người đã được giải cứu khỏi lũ lụt."},
      {"en":"The prize has been awarded to a local student.","vi":"Giải thưởng đã được trao cho một học sinh địa phương."},
      {"en":"A new metro line will be opened next year.","vi":"Một tuyến metro mới sẽ được khai trương năm tới."},
      {"en":"The road is being repaired at the moment.","vi":"Con đường đang được sửa chữa lúc này."}],
    "commonMistakes":["❌ Three people have been arrest. → ✅ ...have been arrested. (V3)","❌ The bridge will built next year. → ✅ The bridge will be built... (will + be + V3)","❌ Has been announce → ✅ has been announced"],
    "tips":["Hiện tại hoàn thành bị động: have/has been + V3.","Tương lai bị động: will be + V3.","Bị động tiếp diễn: is/are being + V3."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u11-l2-p1','b1-u11-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu bị động ĐÚNG (hiện tại hoàn thành):","options":[{"id":"a","text":"Three people have arrested."},{"id":"b","text":"Three people have been arrested."},{"id":"c","text":"Three people had been arrested."}],"correctOptionId":"b","explanationVi":"HTTB bị động: have/has been + V3."}'::jsonb),
 ('b1-u11-l2-p2','b1-u11-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chuyển sang bị động tương lai: ''They will open the new library.'' → The new library ___ next month.","acceptedAnswers":["will be opened"],"explanationVi":"Tương lai bị động: will be + V3."}'::jsonb),
 ('b1-u11-l2-p3','b1-u11-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối câu chủ động với bị động:","pairs":[{"left":"They have completed the project.","right":"The project has been completed."},{"left":"They will announce the results.","right":"The results will be announced."},{"left":"They are repairing the road.","right":"The road is being repaired."}],"explanationVi":"Ghép đúng từng cặp."}'::jsonb),
 ('b1-u11-l2-p4','b1-u11-l2','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''The bridge will built next year.''","acceptedAnswers":["The bridge will be built next year."],"explanationVi":"Tương lai bị động: will + be + V3."}'::jsonb),
 ('b1-u11-l2-p5','b1-u11-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh: ''Tuyến metro mới sẽ được khai trương vào năm tới.''","sourceText":"Tuyến metro mới sẽ được khai trương vào năm tới.","acceptedAnswers":["The new metro line will be opened next year.","A new metro line will be opened next year."],"explanationVi":"Tương lai bị động: will be opened."}'::jsonb),
 ('b1-u11-l2-p6','b1-u11-l2','multiple_choice',6,'practice','medium',false,'{"question":"Chọn câu bị động tiếp diễn ĐÚNG:","options":[{"id":"a","text":"The road is repaired."},{"id":"b","text":"The road is being repaired."},{"id":"c","text":"The road has been repaired."}],"correctOptionId":"b","explanationVi":"Bị động tiếp diễn: is/are being + V3."}'::jsonb),
 ('b1-u11-l2-p7','b1-u11-l2','grammar_fill_blank',7,'practice','medium',false,'{"question":"Điền vào chỗ trống: ''Five people ___ (rescue — HTTB) from the flood.''","acceptedAnswers":["have been rescued"],"explanationVi":"HTTB bị động: have been + V3."}'::jsonb),
 ('b1-u11-l2-q1','b1-u11-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Câu bị động ĐÚNG (HTTB):","options":[{"id":"a","text":"The prize has given to her."},{"id":"b","text":"The prize has been given to her."},{"id":"c","text":"The prize was been given to her."}],"correctOptionId":"b","explanationVi":"HTTB bị động: has been + V3."}'::jsonb),
 ('b1-u11-l2-q2','b1-u11-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''A new law ___ (introduce — tương lai) next month.''","acceptedAnswers":["will be introduced"],"explanationVi":"Tương lai bị động: will be + V3."}'::jsonb),
 ('b1-u11-l2-q3','b1-u11-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Thì nào của câu bị động: ''The results will be announced tomorrow.''?","options":[{"id":"a","text":"Hiện tại hoàn thành"},{"id":"b","text":"Quá khứ đơn"},{"id":"c","text":"Tương lai"}],"correctOptionId":"c","explanationVi":"will be + V3 = tương lai bị động."}'::jsonb),
 ('b1-u11-l2-q4','b1-u11-l2','error_correction',11,'quiz','medium',true,'{"question":"Sửa lỗi: ''The new school has been complete.''","acceptedAnswers":["The new school has been completed."],"explanationVi":"HTTB bị động: has been + V3 (completed)."}'::jsonb),
 ('b1-u11-l2-q5','b1-u11-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối thì với cấu trúc bị động:","pairs":[{"left":"Hiện tại đơn","right":"is/are + V3"},{"left":"HTTB","right":"have/has been + V3"},{"left":"Tương lai","right":"will be + V3"}],"explanationVi":"Tổng hợp bị động."}'::jsonb),
 ('b1-u11-l2-q6','b1-u11-l2','translation',13,'quiz','hard',true,'{"question":"Dịch: ''Năm người đã được giải cứu khỏi lũ lụt.''","sourceText":"Năm người đã được giải cứu khỏi lũ lụt.","acceptedAnswers":["Five people have been rescued from the flood."],"explanationVi":"HTTB bị động."}'::jsonb),
 ('b1-u11-l2-q7','b1-u11-l2','sentence_ordering',14,'quiz','hard',true,'{"question":"Sắp xếp thành câu bị động đúng:","tokens":["A","new","hospital","will","be","built","next","year"],"correctOrder":[0,1,2,3,4,5,6,7],"explanationVi":"A new hospital will be built next year."}'::jsonb);

-- Lesson 11-L3: Environment Vocabulary & Causative
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u11-l3','B1','reading','b1-u11','normal',3,'Environment & Causative Have/Get','Từ vựng môi trường + have/get something done',10,20,70,'{}'::jsonb,
  '{"warmup":"Bạn không tự sửa xe — bạn mang xe đi sửa. Tiếng Anh có cách diễn đạt riêng cho việc ''nhờ ai làm gì''!",
    "objectives":["Học từ vựng về môi trường ở B1","Dùng have/get + object + V3 (causative)","Phân biệt causative với bị động thông thường"],
    "grammarHtml":"<b>Causative:</b> have/get + object + V3 = nhờ/thuê ai làm gì<br>I had my car repaired. (Tôi đã nhờ sửa xe.)<br>She got her hair cut. (Cô ấy đi cắt tóc.)<br><b>Thì:</b> Dùng đúng thì của have/get.<br>I have my house cleaned every week. (hiện tại)<br>I''m going to get my teeth checked. (tương lai)<br><b>Từ vựng môi trường B1:</b>",
    "vocabBlock":[
      {"word":"pollution","ipa":"/pəˈluːʃn/","meaningVi":"ô nhiễm","example":"Air pollution is a serious problem."},
      {"word":"recycle","ipa":"/ˌriːˈsaɪkl/","meaningVi":"tái chế","example":"We should recycle more."},
      {"word":"deforestation","ipa":"/ˌdiːˌfɒrɪˈsteɪʃn/","meaningVi":"nạn phá rừng","example":"Deforestation destroys habitats."},
      {"word":"renewable energy","ipa":"/rɪˈnjuːəbl ˈenədʒi/","meaningVi":"năng lượng tái tạo","example":"Solar is a renewable energy source."},
      {"word":"carbon footprint","ipa":"/ˈkɑːbən ˈfʊtprɪnt/","meaningVi":"dấu carbon","example":"Reduce your carbon footprint."},
      {"word":"endangered","ipa":"/ɪnˈdeɪndʒəd/","meaningVi":"có nguy cơ tuyệt chủng","example":"Tigers are endangered animals."}],
    "examples":[
      {"en":"I had my phone fixed at the shop.","vi":"Tôi nhờ sửa điện thoại ở cửa hàng."},
      {"en":"She got her eyes tested last month.","vi":"Cô ấy đi kiểm tra mắt tháng trước."},
      {"en":"We should get our house insulated to save energy.","vi":"Chúng ta nên nhờ cách nhiệt nhà để tiết kiệm năng lượng."},
      {"en":"He''s having his roof repaired because of the storm damage.","vi":"Anh ấy đang nhờ sửa mái nhà vì hư hại do bão."}],
    "commonMistakes":["❌ I had my car repair. → ✅ I had my car repaired. (have + obj + V3)","❌ She got cut her hair. → ✅ She got her hair cut. (get + obj + V3, obj đứng trước V3)","Phân biệt: I had my car repaired (nhờ sửa) vs My car was repaired (được sửa)."],
    "tips":["have/get + object + V3 = causative (nhờ ai đó làm).","Object đứng giữa have/get và V3.","Đổi thì của have/get theo ngữ cảnh."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u11-l3-p1','b1-u11-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"pollution","right":"ô nhiễm"},{"left":"recycle","right":"tái chế"},{"left":"deforestation","right":"nạn phá rừng"},{"left":"endangered","right":"có nguy cơ tuyệt chủng"}],"explanationVi":"Từ vựng môi trường."}'::jsonb),
 ('b1-u11-l3-p2','b1-u11-l3','multiple_choice',2,'practice','easy',false,'{"question":"Chọn câu causative ĐÚNG:","options":[{"id":"a","text":"I had repaired my car."},{"id":"b","text":"I had my car repaired."},{"id":"c","text":"I had my car repair."}],"correctOptionId":"b","explanationVi":"Causative: have + object + V3."}'::jsonb),
 ('b1-u11-l3-p3','b1-u11-l3','grammar_fill_blank',3,'practice','easy',false,'{"question":"Điền vào chỗ trống: ''She got her hair ___ (cut) at the salon.''","acceptedAnswers":["cut"],"explanationVi":"get + object + V3 (cut)."}'::jsonb),
 ('b1-u11-l3-p4','b1-u11-l3','vocabulary_match',4,'practice','medium',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"renewable energy","right":"năng lượng tái tạo"},{"left":"carbon footprint","right":"dấu carbon"},{"left":"habitat","right":"môi trường sống"},{"left":"climate change","right":"biến đổi khí hậu"}],"explanationVi":"Từ vựng môi trường nâng cao."}'::jsonb),
 ('b1-u11-l3-p5','b1-u11-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh: ''Tôi nhờ sửa điện thoại ở cửa hàng.''","sourceText":"Tôi nhờ sửa điện thoại ở cửa hàng.","acceptedAnswers":["I had my phone fixed at the shop.","I got my phone fixed at the shop."],"explanationVi":"Causative: have/get + obj + V3."}'::jsonb),
 ('b1-u11-l3-p6','b1-u11-l3','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''She got cut her hair short.''","acceptedAnswers":["She got her hair cut short."],"explanationVi":"get + object + V3: object (her hair) đứng trước V3 (cut)."}'::jsonb),
 ('b1-u11-l3-p7','b1-u11-l3','multiple_choice',7,'practice','medium',false,'{"question":"Từ nào mô tả nguồn năng lượng từ mặt trời và gió?","options":[{"id":"a","text":"fossil fuel"},{"id":"b","text":"renewable energy"},{"id":"c","text":"nuclear energy"}],"correctOptionId":"b","explanationVi":"Mặt trời, gió → renewable energy."}'::jsonb),
 ('b1-u11-l3-q1','b1-u11-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"pollution","right":"ô nhiễm"},{"left":"recycle","right":"tái chế"},{"left":"endangered","right":"có nguy cơ tuyệt chủng"}],"explanationVi":"Từ vựng môi trường."}'::jsonb),
 ('b1-u11-l3-q2','b1-u11-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Câu causative ĐÚNG:","options":[{"id":"a","text":"I got my teeth check last month."},{"id":"b","text":"I got my teeth checked last month."},{"id":"c","text":"I got checked my teeth last month."}],"correctOptionId":"b","explanationVi":"get + obj + V3: my teeth checked."}'::jsonb),
 ('b1-u11-l3-q3','b1-u11-l3','grammar_fill_blank',10,'quiz','medium',true,'{"question":"Điền vào chỗ trống: ''He''s having his roof ___ (repair) after the storm.''","acceptedAnswers":["repaired"],"explanationVi":"have + obj + V3: repaired."}'::jsonb),
 ('b1-u11-l3-q4','b1-u11-l3','multiple_choice',11,'quiz','medium',true,'{"question":"''I had my car repaired'' nghĩa là gì?","options":[{"id":"a","text":"Tôi tự sửa xe"},{"id":"b","text":"Xe tôi bị hỏng"},{"id":"c","text":"Tôi nhờ người khác sửa xe"}],"correctOptionId":"c","explanationVi":"Causative = nhờ/thuê ai đó làm."}'::jsonb),
 ('b1-u11-l3-q5','b1-u11-l3','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với định nghĩa:","pairs":[{"left":"deforestation","right":"chặt phá rừng quy mô lớn"},{"left":"carbon footprint","right":"lượng CO2 cá nhân thải ra"},{"left":"renewable energy","right":"năng lượng không cạn kiệt"}],"explanationVi":"Từ vựng môi trường."}'::jsonb),
 ('b1-u11-l3-q6','b1-u11-l3','translation',13,'quiz','hard',true,'{"question":"Dịch: ''Cô ấy sẽ nhờ kiểm tra mắt vào tuần tới.''","sourceText":"Cô ấy sẽ nhờ kiểm tra mắt vào tuần tới.","acceptedAnswers":["She is going to get her eyes tested next week.","She will have her eyes tested next week."],"explanationVi":"Causative tương lai."}'::jsonb),
 ('b1-u11-l3-q7','b1-u11-l3','error_correction',14,'quiz','hard',true,'{"question":"Sửa lỗi: ''They had their house paint last summer.''","acceptedAnswers":["They had their house painted last summer."],"explanationVi":"have + obj + V3: painted."}'::jsonb);

-- Lesson 11-L4: Reading — Our Changing Planet
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u11-l4','B1','reading','b1-u11','normal',4,'Our Changing Planet','Đọc hiểu: Môi trường và biến đổi khí hậu',10,20,70,'{}'::jsonb,
  '{"warmup":"Trái đất đang thay đổi. Hãy đọc bài viết về những thay đổi quan trọng nhất.",
    "objectives":["Đọc hiểu văn bản B1 về môi trường","Nhận biết câu bị động trong văn bản báo chí","Ôn từ vựng môi trường"],
    "vocabBlock":[
      {"word":"global warming","ipa":"/ˌɡləʊbl ˈwɔːmɪŋ/","meaningVi":"nóng lên toàn cầu","example":"Global warming is accelerating."},
      {"word":"glacier","ipa":"/ˈɡlæsiə/","meaningVi":"sông băng","example":"Glaciers are melting rapidly."},
      {"word":"species","ipa":"/ˈspiːʃiːz/","meaningVi":"loài (sinh vật)","example":"Many species are endangered."},
      {"word":"emit","ipa":"/ɪˈmɪt/","meaningVi":"thải ra","example":"Cars emit carbon dioxide."}],
    "examples":[
      {"en":"Our planet is changing faster than ever before, and scientists are concerned. Every year, billions of tonnes of carbon dioxide are released into the atmosphere by cars, factories, and power stations. As a result, global temperatures have been rising steadily. Many glaciers have already been melted and sea levels have been rising. Several animal species have been declared endangered, and some have already been lost forever. In Vietnam, coastal areas are being affected by rising sea levels. New laws have been introduced by the government to reduce pollution, and renewable energy projects have been funded across the country. Citizens are also being encouraged to recycle more and reduce their carbon footprints. If action is not taken now, scientists warn that the consequences will be severe. ''The planet must be protected,'' said one researcher, ''and it can still be saved if we act together.''","vi":"Hành tinh của chúng ta đang thay đổi nhanh hơn bao giờ hết, và các nhà khoa học lo ngại. Mỗi năm, hàng tỷ tấn carbon dioxide được thải vào khí quyển bởi ô tô, nhà máy và nhà máy điện. Kết quả là, nhiệt độ toàn cầu đã tăng đều đặn. Nhiều sông băng đã tan chảy và mực nước biển đang dâng lên. Một số loài động vật đã được tuyên bố có nguy cơ tuyệt chủng, và một số đã biến mất mãi mãi. Ở Việt Nam, các vùng ven biển đang bị ảnh hưởng bởi mực nước biển dâng. Các luật mới đã được chính phủ ban hành để giảm ô nhiễm, và các dự án năng lượng tái tạo đã được tài trợ trên cả nước. Người dân cũng đang được khuyến khích tái chế nhiều hơn và giảm dấu carbon. Nếu không hành động ngay bây giờ, các nhà khoa học cảnh báo rằng hậu quả sẽ rất nghiêm trọng. ''Hành tinh phải được bảo vệ,'' một nhà nghiên cứu nói, ''và nó vẫn có thể được cứu nếu chúng ta hành động cùng nhau.''"}],
    "commonMistakes":["Chú ý nhận biết thì của câu bị động trong bài đọc."],
    "tips":["Tìm các cấu trúc: are released, have been melted, have been rising, will be severe."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u11-l4-p1','b1-u11-l4','multiple_choice',1,'practice','easy',false,'{"question":"Theo bài, CO2 chủ yếu được thải ra bởi điều gì?","options":[{"id":"a","text":"Núi lửa"},{"id":"b","text":"Ô tô, nhà máy và nhà máy điện"},{"id":"c","text":"Rừng nhiệt đới"}],"correctOptionId":"b","explanationVi":"''cars, factories, and power stations.''"}'::jsonb),
 ('b1-u11-l4-p2','b1-u11-l4','multiple_choice',2,'practice','easy',false,'{"question":"Ở Việt Nam, điều gì đang bị ảnh hưởng bởi mực nước biển?","options":[{"id":"a","text":"Rừng núi"},{"id":"b","text":"Vùng ven biển"},{"id":"c","text":"Đồng bằng sông Cửu Long"}],"correctOptionId":"b","explanationVi":"''coastal areas are being affected.''"}'::jsonb),
 ('b1-u11-l4-p3','b1-u11-l4','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"global warming","right":"nóng lên toàn cầu"},{"left":"glacier","right":"sông băng"},{"left":"species","right":"loài sinh vật"},{"left":"emit","right":"thải ra"}],"explanationVi":"Từ vựng môi trường."}'::jsonb),
 ('b1-u11-l4-p4','b1-u11-l4','multiple_choice',4,'practice','medium',false,'{"question":"Câu ''New laws have been introduced'' là thì gì của bị động?","options":[{"id":"a","text":"Quá khứ đơn"},{"id":"b","text":"Hiện tại hoàn thành"},{"id":"c","text":"Tương lai"}],"correctOptionId":"b","explanationVi":"have been + V3 = HTTB bị động."}'::jsonb),
 ('b1-u11-l4-p5','b1-u11-l4','multiple_choice',5,'practice','medium',false,'{"question":"Người dân đang được khuyến khích làm gì?","options":[{"id":"a","text":"Dùng ít điện hơn"},{"id":"b","text":"Tái chế và giảm dấu carbon"},{"id":"c","text":"Trồng thêm cây"}],"correctOptionId":"b","explanationVi":"''recycle more and reduce their carbon footprints.''"}'::jsonb),
 ('b1-u11-l4-p6','b1-u11-l4','grammar_fill_blank',6,'practice','medium',false,'{"question":"Hoàn thành câu bị động theo bài: ''The planet must ___ protected.''","acceptedAnswers":["be"],"explanationVi":"Modal + be + V3: must be protected."}'::jsonb),
 ('b1-u11-l4-p7','b1-u11-l4','multiple_choice',7,'practice','medium',false,'{"question":"Câu ''it can still be saved'' diễn đạt điều gì?","options":[{"id":"a","text":"Hành tinh sẽ tự cứu"},{"id":"b","text":"Con người có thể cứu hành tinh"},{"id":"c","text":"Hành tinh không thể cứu được"}],"correctOptionId":"b","explanationVi":"can be saved = có thể được cứu."}'::jsonb),
 ('b1-u11-l4-q1','b1-u11-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Theo bài, điều gì đã tăng đều đặn?","options":[{"id":"a","text":"Lượng mưa"},{"id":"b","text":"Nhiệt độ toàn cầu"},{"id":"c","text":"Diện tích rừng"}],"correctOptionId":"b","explanationVi":"''global temperatures have been rising steadily.''"}'::jsonb),
 ('b1-u11-l4-q2','b1-u11-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Câu bị động nào trong bài ở thì quá khứ đơn?","options":[{"id":"a","text":"are released"},{"id":"b","text":"have been melted"},{"id":"c","text":"were introduced (nếu dùng quá khứ)"}],"correctOptionId":"b","explanationVi":"Nhận biết thì bị động qua cấu trúc."}'::jsonb),
 ('b1-u11-l4-q3','b1-u11-l4','grammar_fill_blank',10,'quiz','medium',true,'{"question":"Hoàn thành theo bài: ''Renewable energy projects ___ (fund — HTTB) across the country.''","acceptedAnswers":["have been funded"],"explanationVi":"HTTB bị động: have been + V3."}'::jsonb),
 ('b1-u11-l4-q4','b1-u11-l4','multiple_choice',11,'quiz','medium',true,'{"question":"Câu ''Citizens are being encouraged to recycle'' là thì gì của bị động?","options":[{"id":"a","text":"Bị động tiếp diễn"},{"id":"b","text":"Bị động tương lai"},{"id":"c","text":"Bị động quá khứ"}],"correctOptionId":"a","explanationVi":"are being + V3 = bị động tiếp diễn."}'::jsonb),
 ('b1-u11-l4-q5','b1-u11-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Điều nhà khoa học cảnh báo nếu không hành động?","options":[{"id":"a","text":"Nhiệt độ sẽ ổn định"},{"id":"b","text":"Hậu quả sẽ rất nghiêm trọng"},{"id":"c","text":"Sẽ không còn ô nhiễm"}],"correctOptionId":"b","explanationVi":"''the consequences will be severe.''"}'::jsonb),
 ('b1-u11-l4-q6','b1-u11-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"glacier","right":"sông băng"},{"left":"species","right":"loài sinh vật"},{"left":"emit","right":"thải ra"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b1-u11-l4-q7','b1-u11-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chuyển sang bị động: ''They have declared several species endangered.'' → Several species ___.","acceptedAnswers":["have been declared endangered"],"explanationVi":"HTTB bị động: have been + V3."}'::jsonb);

-- Lesson 11-L5: Unit Review
INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b1-u11-l5','B1','reading','b1-u11','unit_review',5,'Unit 11 Review','Ôn tập Unit 11: The World Around Us',12,30,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 11: bị động các thì, causative have/get và từ vựng môi trường.","objectives":["Tổng hợp can-do Unit 11","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b1-u11-l5-q1','b1-u11-l5','multiple_choice',1,'quiz','easy',true,'{"question":"Câu bị động hiện tại ĐÚNG:","options":[{"id":"a","text":"Rice grow in Vietnam."},{"id":"b","text":"Rice is grown in Vietnam."},{"id":"c","text":"Rice is grow in Vietnam."}],"correctOptionId":"b","explanationVi":"Bị động hiện tại: is + V3."}'::jsonb),
 ('b1-u11-l5-q2','b1-u11-l5','grammar_fill_blank',2,'quiz','easy',true,'{"question":"Điền vào chỗ trống: ''The museum ___ (build — quá khứ) in 1920.''","acceptedAnswers":["was built"],"explanationVi":"Quá khứ bị động: was + V3."}'::jsonb),
 ('b1-u11-l5-q3','b1-u11-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Câu HTTB bị động ĐÚNG:","options":[{"id":"a","text":"The award have been given to her."},{"id":"b","text":"The award has been given to her."},{"id":"c","text":"The award was been given to her."}],"correctOptionId":"b","explanationVi":"HTTB bị động: has been + V3."}'::jsonb),
 ('b1-u11-l5-q4','b1-u11-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Điền vào chỗ trống: ''A new bridge ___ (build — tương lai) next year.''","acceptedAnswers":["will be built"],"explanationVi":"Tương lai bị động: will be + V3."}'::jsonb),
 ('b1-u11-l5-q5','b1-u11-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu causative ĐÚNG:","options":[{"id":"a","text":"I had repaired my car."},{"id":"b","text":"I had my car repaired."},{"id":"c","text":"I had my car repair."}],"correctOptionId":"b","explanationVi":"Causative: have + obj + V3."}'::jsonb),
 ('b1-u11-l5-q6','b1-u11-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ môi trường với nghĩa:","pairs":[{"left":"pollution","right":"ô nhiễm"},{"left":"recycle","right":"tái chế"},{"left":"renewable energy","right":"năng lượng tái tạo"},{"left":"endangered","right":"có nguy cơ tuyệt chủng"}],"explanationVi":"Từ vựng môi trường."}'::jsonb),
 ('b1-u11-l5-q7','b1-u11-l5','error_correction',7,'quiz','medium',true,'{"question":"Sửa lỗi: ''She got cut her hair short.''","acceptedAnswers":["She got her hair cut short."],"explanationVi":"get + obj + V3: obj đứng trước V3."}'::jsonb),
 ('b1-u11-l5-q8','b1-u11-l5','multiple_choice',8,'quiz','hard',true,'{"question":"Thì nào: ''The road is being repaired''?","options":[{"id":"a","text":"Bị động tiếp diễn"},{"id":"b","text":"Bị động hiện tại đơn"},{"id":"c","text":"HTTB bị động"}],"correctOptionId":"a","explanationVi":"is being + V3 = bị động tiếp diễn."}'::jsonb),
 ('b1-u11-l5-q9','b1-u11-l5','grammar_fill_blank',9,'quiz','medium',true,'{"question":"Chuyển sang bị động: ''They are announcing the results.'' → The results ___.","acceptedAnswers":["are being announced"],"explanationVi":"Bị động tiếp diễn: are being + V3."}'::jsonb),
 ('b1-u11-l5-q10','b1-u11-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Điền vào chỗ trống: ''He''s going to have his house ___ (paint) this summer.''","acceptedAnswers":["painted"],"explanationVi":"Causative: have + obj + V3 (painted)."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b1-u11-l5' WHERE id = 'b1-u11';
