-- ══════════════════════════════════════════════════════════════════════════
-- B2 Units 02-03
-- Unit 02: What Lies Ahead — Future Perfect & Future Perfect Continuous
-- Unit 03: What If? — Conditional Type 3, Mixed Conditionals, Wish/If only
-- ══════════════════════════════════════════════════════════════════════════

-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║ BƯỚC 0 — DỌN SẠCH (idempotent)                                           ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B2' AND id IN ('b2-u02','b2-u03');

DELETE FROM learning_lesson_activities
 WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B2' AND unit_id IN ('b2-u02','b2-u03'));

DELETE FROM learning_lessons WHERE level_code = 'B2' AND unit_id IN ('b2-u02','b2-u03');

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 02 — What Lies Ahead
-- Theme: future | Future Perfect; Future Perfect Continuous
-- ══════════════════════════════════════════════════════════════════════════

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u02-l1','B2','reading','b2-u02','normal',1,'Future Perfect','Will have done: hoàn thành trước mốc tương lai',12,25,70,'{}'::jsonb,
  '{"warmup":"''Vào năm 2030, loài người sẽ đã bay lên Sao Hỏa.'' Bạn thấy cấu trúc này quen không? Đó là thì tương lai hoàn thành!",
    "objectives":["Dùng will have + V3 để nói về việc hoàn tất trước mốc thời gian tương lai","Phân biệt future perfect với future continuous","Dùng đúng với by + mốc thời gian"],
    "grammarHtml":"<b>Future Perfect:</b> S + will have + V3<br>Dùng để chỉ hành động SẼ HOÀN TẤT trước một thời điểm hoặc sự kiện trong tương lai.<br><b>Dấu hiệu:</b> by (the time), by then, by next year, before + tương lai.<br><b>Ví dụ:</b> By 2030, scientists will have found a cure. (Trước năm 2030, sẽ tìm ra thuốc.)<br><b>Phủ định:</b> won''t have + V3: She won''t have finished by 3pm.<br><b>Câu hỏi:</b> Will + S + have + V3? Will you have arrived by then?<br><b>Khác với Future Continuous (will be + V-ing):</b> Future continuous = đang xảy ra tại mốc; Future perfect = đã xong trước mốc.<br>At 8pm, I will be eating. (đang ăn lúc 8h) vs By 8pm, I will have eaten. (đã ăn xong trước 8h).",
    "vocabBlock":[
      {"word":"by the time","ipa":"/baɪ ðə taɪm/","meaningVi":"vào lúc (mà)","example":"By the time you arrive, I will have left."},
      {"word":"innovation","ipa":"/ˌɪnəˈveɪʃn/","meaningVi":"sự đổi mới, cải tiến","example":"Technology innovation is accelerating."},
      {"word":"breakthrough","ipa":"/ˈbreɪkθruː/","meaningVi":"bước đột phá","example":"Scientists made a major breakthrough."},
      {"word":"automate","ipa":"/ˈɔːtəmeɪt/","meaningVi":"tự động hóa","example":"Many jobs will be automated by 2040."},
      {"word":"by then","ipa":"/baɪ ðen/","meaningVi":"vào lúc đó","example":"By then, the situation will have changed."}],
    "examples":[
      {"en":"By 2035, humans will have landed on Mars.","vi":"Trước năm 2035, con người sẽ đã đổ bộ lên Sao Hỏa."},
      {"en":"She will have graduated by the time I return.","vi":"Cô ấy sẽ đã tốt nghiệp khi tôi trở về."},
      {"en":"Will you have finished the report by Friday?","vi":"Bạn sẽ hoàn thành báo cáo trước thứ Sáu chứ?"},
      {"en":"By next summer, they will have been married for ten years.","vi":"Trước hè năm sau, họ sẽ đã kết hôn được mười năm."}],
    "commonMistakes":["❌ By 2030, scientists will find a cure. → ✅ will have found (hoàn tất trước mốc)","❌ By Friday she finishes the report. → ✅ will have finished","❌ Nhầm by (trước mốc) với at (đúng tại mốc)."],
    "tips":["by = trước mốc → future perfect; at = đúng tại mốc → future simple/continuous.","By the time + present simple → main clause dùng future perfect."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u02-l1-p1','b2-u02-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG: ''___ 2040, many jobs ___ (automate).''","options":[{"id":"a","text":"At / will automate"},{"id":"b","text":"By / will have been automated"},{"id":"c","text":"In / automate"}],"correctOptionId":"b","explanationVi":"By + mốc tương lai + will have been automated (future perfect passive)."}'::jsonb),
 ('b2-u02-l1-p2','b2-u02-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chia động từ: ''By the time you arrive, I ___ (cook) dinner.''","acceptedAnswers":["will have cooked"],"explanationVi":"Nấu xong trước khi bạn đến → will have cooked."}'::jsonb),
 ('b2-u02-l1-p3','b2-u02-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"innovation","right":"sự đổi mới"},{"left":"breakthrough","right":"bước đột phá"},{"left":"automate","right":"tự động hóa"},{"left":"by then","right":"vào lúc đó"}],"explanationVi":"Từ vựng công nghệ & tương lai."}'::jsonb),
 ('b2-u02-l1-p4','b2-u02-l1','grammar_fill_blank',4,'practice','medium',false,'{"question":"Chia động từ: ''She ___ (not/finish) the project by Monday.''","acceptedAnswers":["won''t have finished","will not have finished"],"explanationVi":"Phủ định future perfect: won''t have finished."}'::jsonb),
 ('b2-u02-l1-p5','b2-u02-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Trước năm 2030, con người sẽ đã tìm ra thuốc chữa bệnh đó.","acceptedAnswers":["By 2030, humans will have found a cure for the disease.","By 2030, scientists will have found a cure for the disease."],"explanationVi":"By 2030 + will have found."}'::jsonb),
 ('b2-u02-l1-p6','b2-u02-l1','multiple_choice',6,'practice','medium',false,'{"question":"Phân biệt: ''At 6pm I ___ dinner'' (đang ăn lúc 6h) vs ''By 6pm I ___ dinner'' (đã ăn xong):","options":[{"id":"a","text":"will be eating / will have eaten"},{"id":"b","text":"will eat / will be eating"},{"id":"c","text":"will have eaten / will be eating"}],"correctOptionId":"a","explanationVi":"Đang xảy ra → will be eating; đã xong → will have eaten."}'::jsonb),
 ('b2-u02-l1-p7','b2-u02-l1','error_correction',7,'practice','medium',false,'{"question":"Sửa lỗi: ''By next year, she will finish her degree.''","acceptedAnswers":["By next year, she will have finished her degree."],"explanationVi":"Hoàn tất trước mốc tương lai → will have finished."}'::jsonb),
 ('b2-u02-l1-q1','b2-u02-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG: ''___ the meeting starts, we ___ the report.''","options":[{"id":"a","text":"By the time / will have finished"},{"id":"b","text":"When / will finish"},{"id":"c","text":"Until / finish"}],"correctOptionId":"a","explanationVi":"By the time + present → future perfect."}'::jsonb),
 ('b2-u02-l1-q2','b2-u02-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chia động từ: ''___ you ___ (graduate) by June?''","acceptedAnswers":["Will you have graduated"],"explanationVi":"Câu hỏi future perfect: Will + S + have + V3?"}'::jsonb),
 ('b2-u02-l1-q3','b2-u02-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Thì nào chỉ hành động ĐÃ XONG trước một mốc tương lai?","options":[{"id":"a","text":"Future simple"},{"id":"b","text":"Future continuous"},{"id":"c","text":"Future perfect"}],"correctOptionId":"c","explanationVi":"Future perfect = will have + V3 = hoàn tất trước mốc."}'::jsonb),
 ('b2-u02-l1-q4','b2-u02-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chia động từ: ''By 2050, technology ___ (transform) every industry.''","acceptedAnswers":["will have transformed"],"explanationVi":"Hoàn tất trước 2050 → will have transformed."}'::jsonb),
 ('b2-u02-l1-q5','b2-u02-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"breakthrough","right":"bước đột phá"},{"left":"by the time","right":"vào lúc mà"},{"left":"innovation","right":"sự đổi mới"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l1-q6','b2-u02-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["arrived","will","By","he","the","have","time","you"],"correctOrder":[2,6,0,4,7,1,5,3],"explanationVi":"By the time you arrived, he will have left — or: By the time you arrive, he will have left."}'::jsonb),
 ('b2-u02-l1-q7','b2-u02-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''They ___ (not/solve) the problem by the deadline.''","acceptedAnswers":["won''t have solved","will not have solved"],"explanationVi":"Phủ định future perfect."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u02-l2','B2','reading','b2-u02','normal',2,'Future Perfect Continuous','Will have been doing: nhấn thời lượng tới mốc tương lai',12,25,70,'{}'::jsonb,
  '{"warmup":"''Vào năm sau, tôi sẽ đã học tiếng Anh được 10 năm.'' Câu này nhấn vào điều gì — kết quả hay thời gian?",
    "objectives":["Dùng will have been + V-ing để nhấn thời lượng kéo dài tới mốc tương lai","Phân biệt future perfect và future perfect continuous","Nhận biết ngữ cảnh phù hợp"],
    "grammarHtml":"<b>Future Perfect Continuous:</b> S + will have been + V-ing<br>Dùng để nhấn mạnh THỜI LƯỢNG của hành động đang diễn ra liên tục tính đến một mốc tương lai.<br><b>Dấu hiệu:</b> for + khoảng thời gian + by + mốc tương lai.<br><b>Ví dụ:</b> By July, I will have been working here for five years.<br><b>So sánh:</b><br>By June, she will have written the report. (xong rồi — nhấn kết quả)<br>By June, she will have been writing the report for six months. (vẫn đang viết — nhấn thời lượng)<br><b>Không dùng stative verbs:</b> ❌ will have been knowing → ✅ will have known",
    "vocabBlock":[
      {"word":"by then","ipa":"/baɪ ðen/","meaningVi":"vào lúc đó","example":"By then, I will have been living here for a decade."},
      {"word":"for a decade","ipa":"/fɔː ə ˈdekeɪd/","meaningVi":"trong một thập kỷ","example":"They will have been married for a decade by then."},
      {"word":"continuously","ipa":"/kənˈtɪnjuəsli/","meaningVi":"liên tục","example":"She has been working continuously for hours."},
      {"word":"accumulate","ipa":"/əˈkjuːmjəleɪt/","meaningVi":"tích lũy","example":"By retirement, he will have accumulated vast experience."}],
    "examples":[
      {"en":"By next year, she will have been teaching for twenty years.","vi":"Sang năm, cô ấy sẽ đã dạy học được hai mươi năm."},
      {"en":"By the time the project finishes, we will have been working on it for three years.","vi":"Khi dự án kết thúc, chúng tôi sẽ đã làm nó được ba năm."},
      {"en":"How long will you have been waiting by the time he arrives?","vi":"Bạn sẽ đã chờ bao lâu khi anh ấy đến?"}],
    "commonMistakes":["❌ By June I will have been known her for ten years. → ✅ will have known (know là stative verb).","Không nhầm với future perfect: will have written (xong) vs will have been writing (đang viết, nhấn thời gian)."],
    "tips":["for + khoảng thời gian → dấu hiệu dùng future perfect continuous.","Kết quả xong hẳn → future perfect; quá trình kéo dài → future perfect continuous."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u02-l2-p1','b2-u02-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu nhấn THỜI LƯỢNG tới mốc tương lai:","options":[{"id":"a","text":"By June, she will have finished the course."},{"id":"b","text":"By June, she will have been studying for two years."},{"id":"c","text":"She will study until June."}],"correctOptionId":"b","explanationVi":"Nhấn thời lượng 2 năm tới mốc → future perfect continuous."}'::jsonb),
 ('b2-u02-l2-p2','b2-u02-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chia động từ: ''By next March, he ___ (work) here for five years.''","acceptedAnswers":["will have been working"],"explanationVi":"Nhấn thời lượng 5 năm tới mốc → will have been working."}'::jsonb),
 ('b2-u02-l2-p3','b2-u02-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"continuously","right":"liên tục"},{"left":"accumulate","right":"tích lũy"},{"left":"by then","right":"vào lúc đó"},{"left":"for a decade","right":"trong một thập kỷ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l2-p4','b2-u02-l2','multiple_choice',4,'practice','medium',false,'{"question":"Phân biệt: ''By 2025, they ___ the bridge'' (xong) vs ''By 2025, they ___ the bridge for 3 years'' (quá trình):","options":[{"id":"a","text":"will have built / will have been building"},{"id":"b","text":"will build / will have built"},{"id":"c","text":"will have been building / will have built"}],"correctOptionId":"a","explanationVi":"Xong hẳn → will have built; nhấn thời gian → will have been building."}'::jsonb),
 ('b2-u02-l2-p5','b2-u02-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Sang năm, tôi sẽ đã học tiếng Anh được mười năm.","acceptedAnswers":["By next year, I will have been learning English for ten years.","By next year, I will have been studying English for ten years."],"explanationVi":"By next year + for ten years → future perfect continuous."}'::jsonb),
 ('b2-u02-l2-p6','b2-u02-l2','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''By the time he retires, he will have been knowing the company for 30 years.''","acceptedAnswers":["By the time he retires, he will have known the company for 30 years."],"explanationVi":"know là stative verb → will have known (không dùng continuous)."}'::jsonb),
 ('b2-u02-l2-p7','b2-u02-l2','grammar_fill_blank',7,'practice','medium',false,'{"question":"Chia động từ: ''How long ___ you ___ (wait) by the time he arrives?''","acceptedAnswers":["will you have been waiting"],"explanationVi":"Hỏi thời lượng chờ đợi đến mốc tương lai."}'::jsonb),
 ('b2-u02-l2-q1','b2-u02-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Thì nào nhấn mạnh THỜI LƯỢNG liên tục tới mốc tương lai?","options":[{"id":"a","text":"Future perfect"},{"id":"b","text":"Future continuous"},{"id":"c","text":"Future perfect continuous"}],"correctOptionId":"c","explanationVi":"Future perfect continuous = will have been + V-ing."}'::jsonb),
 ('b2-u02-l2-q2','b2-u02-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chia động từ: ''By the end of the year, she ___ (teach) for 15 years.''","acceptedAnswers":["will have been teaching"],"explanationVi":"Nhấn thời lượng 15 năm → will have been teaching."}'::jsonb),
 ('b2-u02-l2-q3','b2-u02-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Câu nào ĐÚNG? (know là stative verb)","options":[{"id":"a","text":"By then, I will have been knowing her for years."},{"id":"b","text":"By then, I will have known her for years."},{"id":"c","text":"By then, I will know her for years."}],"correctOptionId":"b","explanationVi":"know = stative → will have known (không dùng continuous)."}'::jsonb),
 ('b2-u02-l2-q4','b2-u02-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chia động từ: ''By retirement, he ___ (accumulate) decades of experience.''","acceptedAnswers":["will have accumulated","will have been accumulating"],"explanationVi":"Tích lũy tới mốc → will have accumulated / will have been accumulating."}'::jsonb),
 ('b2-u02-l2-q5','b2-u02-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"accumulate","right":"tích lũy"},{"left":"continuously","right":"liên tục"},{"left":"for a decade","right":"trong mười năm"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l2-q6','b2-u02-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["been","By","she","will","have","March","teaching","for","20","years"],"correctOrder":[1,5,2,3,4,0,6,7,8,9],"explanationVi":"By March, she will have been teaching for 20 years."}'::jsonb),
 ('b2-u02-l2-q7','b2-u02-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''By the project deadline, we ___ (work) on it for six months.''","acceptedAnswers":["will have been working"],"explanationVi":"Nhấn thời lượng 6 tháng → will have been working."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u02-l3','B2','reading','b2-u02','normal',3,'Technology & Science Vocabulary','Từ vựng công nghệ & khoa học B2',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn có thể nói về xu hướng công nghệ và những dự đoán về tương lai không? Cần những từ vựng gì?",
    "objectives":["Học 10 từ vựng B2 về công nghệ và khoa học","Dùng từ trong ngữ cảnh dự đoán tương lai","Phân biệt sắc thái giữa các từ gần nghĩa"],
    "vocabBlock":[
      {"word":"innovation","ipa":"/ˌɪnəˈveɪʃn/","meaningVi":"sự đổi mới, cải tiến","example":"Innovation in AI is accelerating rapidly."},
      {"word":"breakthrough","ipa":"/ˈbreɪkθruː/","meaningVi":"bước đột phá","example":"The new vaccine was a medical breakthrough."},
      {"word":"automate","ipa":"/ˈɔːtəmeɪt/","meaningVi":"tự động hóa","example":"Factories are automating their production lines."},
      {"word":"artificial intelligence","ipa":"/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/","meaningVi":"trí tuệ nhân tạo","example":"Artificial intelligence is transforming industries."},
      {"word":"renewable energy","ipa":"/rɪˈnjuːəbl ˈenədʒi/","meaningVi":"năng lượng tái tạo","example":"We must invest in renewable energy sources."},
      {"word":"device","ipa":"/dɪˈvaɪs/","meaningVi":"thiết bị, dụng cụ","example":"Wearable devices monitor health continuously."},
      {"word":"algorithm","ipa":"/ˈælɡərɪðəm/","meaningVi":"thuật toán","example":"The algorithm predicts user behaviour."},
      {"word":"data-driven","ipa":"/ˈdeɪtə ˈdrɪvn/","meaningVi":"dựa trên dữ liệu","example":"Modern medicine is increasingly data-driven."},
      {"word":"sustainable","ipa":"/səˈsteɪnəbl/","meaningVi":"bền vững","example":"We need sustainable solutions for energy."},
      {"word":"emerging","ipa":"/ɪˈmɜːdʒɪŋ/","meaningVi":"đang nổi lên, mới xuất hiện","example":"Emerging technologies are changing our world."}],
    "examples":[
      {"en":"By 2040, artificial intelligence will have automated millions of jobs.","vi":"Trước năm 2040, trí tuệ nhân tạo sẽ đã tự động hóa hàng triệu công việc."},
      {"en":"The next breakthrough in renewable energy will transform how we power cities.","vi":"Bước đột phá tiếp theo trong năng lượng tái tạo sẽ thay đổi cách chúng ta cung cấp điện cho thành phố."},
      {"en":"Emerging technologies require sustainable, data-driven approaches.","vi":"Các công nghệ đang nổi lên đòi hỏi các cách tiếp cận bền vững và dựa trên dữ liệu."}],
    "commonMistakes":["innovation (quá trình/ý tưởng mới) ≠ invention (phát minh cụ thể).","sustainable (bền vững về lâu dài) ≠ renewable (có thể tái tạo).","data-driven (tính từ ghép): a data-driven decision."],
    "tips":["breakthrough + in + lĩnh vực: a breakthrough in medicine/AI/energy.","emerging + technology/market/economy = đang nổi lên, chưa trưởng thành."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u02-l3-p1','b2-u02-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"innovation","right":"sự đổi mới"},{"left":"breakthrough","right":"bước đột phá"},{"left":"automate","right":"tự động hóa"},{"left":"device","right":"thiết bị"}],"explanationVi":"Từ vựng công nghệ cơ bản."}'::jsonb),
 ('b2-u02-l3-p2','b2-u02-l3','vocabulary_match',2,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"sustainable","right":"bền vững"},{"left":"emerging","right":"đang nổi lên"},{"left":"algorithm","right":"thuật toán"},{"left":"data-driven","right":"dựa trên dữ liệu"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l3-p3','b2-u02-l3','multiple_choice',3,'practice','easy',false,'{"question":"Từ nào có nghĩa là ''trí tuệ nhân tạo''?","options":[{"id":"a","text":"renewable energy"},{"id":"b","text":"artificial intelligence"},{"id":"c","text":"algorithm"}],"correctOptionId":"b","explanationVi":"AI = artificial intelligence."}'::jsonb),
 ('b2-u02-l3-p4','b2-u02-l3','multiple_choice',4,'practice','medium',false,'{"question":"Điền từ đúng: ''The company is investing heavily in ___ energy to reduce carbon emissions.''","options":[{"id":"a","text":"artificial"},{"id":"b","text":"emerging"},{"id":"c","text":"renewable"}],"correctOptionId":"c","explanationVi":"renewable energy = năng lượng tái tạo."}'::jsonb),
 ('b2-u02-l3-p5','b2-u02-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Các công nghệ đang nổi lên đòi hỏi các giải pháp bền vững.","acceptedAnswers":["Emerging technologies require sustainable solutions.","Emerging technologies need sustainable solutions."],"explanationVi":"emerging technologies + sustainable solutions."}'::jsonb),
 ('b2-u02-l3-p6','b2-u02-l3','multiple_choice',6,'practice','medium',false,'{"question":"Từ nào điền vào: ''The new drug is a major ___ in cancer treatment.''","options":[{"id":"a","text":"device"},{"id":"b","text":"breakthrough"},{"id":"c","text":"algorithm"}],"correctOptionId":"b","explanationVi":"breakthrough in + lĩnh vực = bước đột phá."}'::jsonb),
 ('b2-u02-l3-p7','b2-u02-l3','vocabulary_match',7,'practice','easy',false,'{"question":"Nối từ còn lại:","pairs":[{"left":"artificial intelligence","right":"trí tuệ nhân tạo"},{"left":"renewable energy","right":"năng lượng tái tạo"}],"explanationVi":"Ghép đúng hai cụm từ."}'::jsonb),
 ('b2-u02-l3-q1','b2-u02-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"sustainable","right":"bền vững"},{"left":"emerging","right":"đang nổi lên"},{"left":"breakthrough","right":"bước đột phá"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l3-q2','b2-u02-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''tự động hóa''?","options":[{"id":"a","text":"accumulate"},{"id":"b","text":"automate"},{"id":"c","text":"innovate"}],"correctOptionId":"b","explanationVi":"automate = tự động hóa."}'::jsonb),
 ('b2-u02-l3-q3','b2-u02-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Điền từ đúng: ''The hospital uses a ___ approach to diagnose diseases.''","options":[{"id":"a","text":"data-driven"},{"id":"b","text":"life-changing"},{"id":"c","text":"renewable"}],"correctOptionId":"a","explanationVi":"data-driven = dựa trên dữ liệu."}'::jsonb),
 ('b2-u02-l3-q4','b2-u02-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền từ đúng: ''An ___ uses mathematical steps to solve problems.''","acceptedAnswers":["algorithm"],"explanationVi":"algorithm = thuật toán."}'::jsonb),
 ('b2-u02-l3-q5','b2-u02-l3','multiple_choice',12,'quiz','medium',true,'{"question":"Từ nào mô tả năng lượng từ mặt trời hoặc gió?","options":[{"id":"a","text":"artificial"},{"id":"b","text":"renewable"},{"id":"c","text":"automated"}],"correctOptionId":"b","explanationVi":"renewable energy = mặt trời, gió, nước..."}'::jsonb),
 ('b2-u02-l3-q6','b2-u02-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["intelligence","Artificial","jobs","millions","will","automate","of"],"correctOrder":[1,0,4,5,2,3,6],"explanationVi":"Artificial intelligence will automate millions of jobs."}'::jsonb),
 ('b2-u02-l3-q7','b2-u02-l3','vocabulary_match',14,'quiz','medium',true,'{"question":"Nối từ với định nghĩa:","pairs":[{"left":"innovation","right":"sự đổi mới, cải tiến"},{"left":"device","right":"thiết bị, dụng cụ"},{"left":"algorithm","right":"thuật toán"}],"explanationVi":"Ghép đúng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u02-l4','B2','reading','b2-u02','normal',4,'The World in 2050','Đọc hiểu: Thế giới năm 2050',12,25,70,'{}'::jsonb,
  '{"warmup":"Thế giới sẽ trông như thế nào vào năm 2050? Đọc bài dự báo và chú ý cách dùng future perfect.",
    "objectives":["Đọc hiểu văn bản B2 về xu hướng công nghệ và tương lai","Nhận biết future perfect và future perfect continuous trong ngữ cảnh","Trả lời câu hỏi suy luận về nội dung bài"],
    "vocabBlock":[
      {"word":"prediction","ipa":"/prɪˈdɪkʃn/","meaningVi":"dự đoán","example":"Experts made bold predictions about 2050."},
      {"word":"accelerate","ipa":"/əkˈseləreɪt/","meaningVi":"tăng tốc","example":"Climate change is accelerating."},
      {"word":"transform","ipa":"/trænsˈfɔːm/","meaningVi":"biến đổi, thay đổi hoàn toàn","example":"AI will transform the job market."},
      {"word":"inevitable","ipa":"/ɪnˈevɪtəbl/","meaningVi":"không thể tránh khỏi","example":"Change is inevitable."}],
    "examples":[
      {"en":"By 2050, experts predict that renewable energy will have replaced most fossil fuels. Cities will have been redesigning their infrastructure for decades to accommodate electric vehicles and smart grids. Artificial intelligence will have transformed the medical field — many diseases that we struggle with today will have been cured, and AI-driven algorithms will have been diagnosing conditions for years before symptoms appear. However, not all predictions are optimistic. By the middle of the century, the global population will have grown significantly, putting pressure on food and water supplies. The question is not whether change will happen, but whether we will have prepared well enough to handle it.","vi":"Đến năm 2050, các chuyên gia dự đoán rằng năng lượng tái tạo sẽ đã thay thế hầu hết nhiên liệu hóa thạch. Các thành phố sẽ đã thiết kế lại cơ sở hạ tầng trong nhiều thập kỷ để đáp ứng xe điện và lưới điện thông minh. Trí tuệ nhân tạo sẽ đã biến đổi lĩnh vực y tế — nhiều bệnh mà chúng ta đang vật lộn ngày nay sẽ đã được chữa khỏi, và các thuật toán do AI điều khiển sẽ đã chẩn đoán các tình trạng trong nhiều năm trước khi triệu chứng xuất hiện. Tuy nhiên, không phải tất cả dự đoán đều lạc quan. Vào giữa thế kỷ, dân số toàn cầu sẽ đã tăng đáng kể, tạo áp lực lên nguồn thực phẩm và nước. Câu hỏi không phải là liệu sự thay đổi có xảy ra không, mà là liệu chúng ta có chuẩn bị đủ để xử lý nó không."}],
    "commonMistakes":["Đọc kỹ để phân biệt future perfect (đã xong) và future perfect continuous (đang diễn ra tới mốc)."],
    "tips":["by + năm/mốc + future perfect = hoàn tất trước mốc đó.","for + khoảng thời gian + future perfect continuous = đang diễn ra liên tục tới mốc."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u02-l4-p1','b2-u02-l4','multiple_choice',1,'practice','easy',false,'{"question":"Bài báo nói gì sẽ xảy ra với nhiên liệu hóa thạch trước năm 2050?","options":[{"id":"a","text":"Chúng vẫn được dùng rộng rãi"},{"id":"b","text":"Năng lượng tái tạo sẽ đã thay thế hầu hết"},{"id":"c","text":"Chúng sẽ trở nên rẻ hơn"}],"correctOptionId":"b","explanationVi":"''renewable energy will have replaced most fossil fuels.''"}'::jsonb),
 ('b2-u02-l4-p2','b2-u02-l4','multiple_choice',2,'practice','easy',false,'{"question":"AI sẽ làm gì với lĩnh vực y tế?","options":[{"id":"a","text":"Thay thế tất cả bác sĩ"},{"id":"b","text":"Chẩn đoán bệnh trước khi triệu chứng xuất hiện"},{"id":"c","text":"Chỉ dùng cho nghiên cứu cơ bản"}],"correctOptionId":"b","explanationVi":"''AI-driven algorithms will have been diagnosing conditions...before symptoms appear.''"}'::jsonb),
 ('b2-u02-l4-p3','b2-u02-l4','multiple_choice',3,'practice','medium',false,'{"question":"Thách thức nào được đề cập trong bài?","options":[{"id":"a","text":"Thiếu điện"},{"id":"b","text":"Áp lực từ tăng dân số"},{"id":"c","text":"Chiến tranh công nghệ"}],"correctOptionId":"b","explanationVi":"''the global population will have grown...putting pressure on food and water.''"}'::jsonb),
 ('b2-u02-l4-p4','b2-u02-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"prediction","right":"dự đoán"},{"left":"accelerate","right":"tăng tốc"},{"left":"transform","right":"biến đổi"},{"left":"inevitable","right":"không thể tránh khỏi"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l4-p5','b2-u02-l4','multiple_choice',5,'practice','medium',false,'{"question":"Thì nào được dùng trong: ''AI will have been diagnosing conditions for years''?","options":[{"id":"a","text":"Future perfect"},{"id":"b","text":"Future perfect continuous"},{"id":"c","text":"Future continuous"}],"correctOptionId":"b","explanationVi":"will have been + V-ing + for = future perfect continuous."}'::jsonb),
 ('b2-u02-l4-p6','b2-u02-l4','multiple_choice',6,'practice','medium',false,'{"question":"Theo bài, câu hỏi quan trọng nhất là gì?","options":[{"id":"a","text":"Liệu AI có thay thế con người không"},{"id":"b","text":"Chúng ta có chuẩn bị đủ để xử lý sự thay đổi không"},{"id":"c","text":"Khi nào năng lượng tái tạo ra đời"}],"correctOptionId":"b","explanationVi":"''whether we will have prepared well enough to handle it.''"}'::jsonb),
 ('b2-u02-l4-p7','b2-u02-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành theo bài: ''By 2050, renewable energy ___ (replace) most fossil fuels.''","acceptedAnswers":["will have replaced"],"explanationVi":"Hoàn tất trước mốc 2050 → will have replaced."}'::jsonb),
 ('b2-u02-l4-q1','b2-u02-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Bài nói gì sẽ xảy ra với các bệnh hiện nay?","options":[{"id":"a","text":"Chúng sẽ trở nên phổ biến hơn"},{"id":"b","text":"Nhiều bệnh sẽ đã được chữa khỏi"},{"id":"c","text":"Chỉ bệnh cảm sẽ chữa được"}],"correctOptionId":"b","explanationVi":"''many diseases...will have been cured.''"}'::jsonb),
 ('b2-u02-l4-q2','b2-u02-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Thành phố sẽ làm gì với cơ sở hạ tầng?","options":[{"id":"a","text":"Giữ nguyên không thay đổi"},{"id":"b","text":"Sẽ đã thiết kế lại trong nhiều thập kỷ"},{"id":"c","text":"Xây thêm nhiều đường cao tốc"}],"correctOptionId":"b","explanationVi":"''Cities will have been redesigning their infrastructure for decades.''"}'::jsonb),
 ('b2-u02-l4-q3','b2-u02-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Từ ''inevitable'' trong bài có nghĩa gần với?","options":[{"id":"a","text":"possible"},{"id":"b","text":"impossible to avoid"},{"id":"c","text":"surprising"}],"correctOptionId":"b","explanationVi":"inevitable = không thể tránh khỏi."}'::jsonb),
 ('b2-u02-l4-q4','b2-u02-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''By 2050, the population ___ (grow) significantly.''","acceptedAnswers":["will have grown"],"explanationVi":"Tăng trước mốc 2050 → will have grown."}'::jsonb),
 ('b2-u02-l4-q5','b2-u02-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Thái độ của bài về tương lai là?","options":[{"id":"a","text":"Hoàn toàn lạc quan"},{"id":"b","text":"Vừa lạc quan vừa lo ngại"},{"id":"c","text":"Hoàn toàn bi quan"}],"correctOptionId":"b","explanationVi":"Có cả dự đoán tốt (energy, medicine) lẫn lo ngại (population, resources)."}'::jsonb),
 ('b2-u02-l4-q6','b2-u02-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"transform","right":"biến đổi hoàn toàn"},{"left":"accelerate","right":"tăng tốc"},{"left":"prediction","right":"dự đoán"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l4-q7','b2-u02-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''AI algorithms ___ (diagnose) conditions for years before 2050.''","acceptedAnswers":["will have been diagnosing"],"explanationVi":"Chẩn đoán liên tục tới mốc → will have been diagnosing."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u02-l5','B2','reading','b2-u02','unit_review',5,'Unit 2 Review','Ôn tập Unit 2: Điều gì đang chờ phía trước',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 2: future perfect, future perfect continuous và từ vựng công nghệ.","objectives":["Tổng hợp can-do Unit 2","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u02-l5-q1','b2-u02-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Chia động từ: ''By 2030, she ___ (live) here for a decade.''","acceptedAnswers":["will have been living","will have lived"],"explanationVi":"Tới mốc 2030 → future perfect (continuous)."}'::jsonb),
 ('b2-u02-l5-q2','b2-u02-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (hoàn tất TRƯỚC mốc tương lai):","options":[{"id":"a","text":"By 6pm, I will eat dinner."},{"id":"b","text":"By 6pm, I will have eaten dinner."},{"id":"c","text":"By 6pm, I will be eating dinner."}],"correctOptionId":"b","explanationVi":"Xong trước mốc → will have eaten."}'::jsonb),
 ('b2-u02-l5-q3','b2-u02-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''bước đột phá''?","options":[{"id":"a","text":"algorithm"},{"id":"b","text":"device"},{"id":"c","text":"breakthrough"}],"correctOptionId":"c","explanationVi":"breakthrough = bước đột phá."}'::jsonb),
 ('b2-u02-l5-q4','b2-u02-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Chia động từ: ''By next year, he ___ (teach) for 20 years.''","acceptedAnswers":["will have been teaching"],"explanationVi":"Nhấn thời lượng → future perfect continuous."}'::jsonb),
 ('b2-u02-l5-q5','b2-u02-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào ĐÚNG? (know là stative verb)","options":[{"id":"a","text":"By then, I will have been knowing him for years."},{"id":"b","text":"By then, I will have known him for years."},{"id":"c","text":"By then, I will know him since years."}],"correctOptionId":"b","explanationVi":"Stative verb → future perfect: will have known."}'::jsonb),
 ('b2-u02-l5-q6','b2-u02-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"sustainable","right":"bền vững"},{"left":"emerging","right":"đang nổi lên"},{"left":"automate","right":"tự động hóa"},{"left":"innovation","right":"sự đổi mới"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u02-l5-q7','b2-u02-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Chia động từ: ''By the deadline, they ___ (not/finish) the project.''","acceptedAnswers":["won''t have finished","will not have finished"],"explanationVi":"Phủ định future perfect."}'::jsonb),
 ('b2-u02-l5-q8','b2-u02-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["have","By","scientists","the","will","discovered","2040","cure"],"correctOrder":[1,6,2,3,0,4,5,7],"explanationVi":"By 2040, scientists will have discovered the cure."}'::jsonb),
 ('b2-u02-l5-q9','b2-u02-l5','multiple_choice',9,'quiz','medium',true,'{"question":"Thì nào nhấn mạnh THỜI LƯỢNG liên tục tới mốc tương lai?","options":[{"id":"a","text":"Future perfect"},{"id":"b","text":"Future perfect continuous"},{"id":"c","text":"Future simple"}],"correctOptionId":"b","explanationVi":"Future perfect continuous = will have been + V-ing."}'::jsonb),
 ('b2-u02-l5-q10','b2-u02-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Chia động từ: ''By the time the conference ends, delegates ___ (discuss) the issue for three days.''","acceptedAnswers":["will have been discussing"],"explanationVi":"Thảo luận liên tục 3 ngày tới mốc kết thúc → will have been discussing."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u02-l5' WHERE id = 'b2-u02';

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 03 — What If? — Speculating
-- Theme: speculation | Conditional Type 3; Mixed Conditionals; Wish/If only
-- ══════════════════════════════════════════════════════════════════════════

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u03-l1','B2','reading','b2-u03','normal',1,'Third Conditional','If + past perfect, would have + V3 — nuối tiếc quá khứ',12,25,70,'{}'::jsonb,
  '{"warmup":"''Giá mà tôi học chăm hơn, tôi đã đỗ kỳ thi.'' Câu này nói về quá khứ thực tế hay giả định? Có thể thay đổi được không?",
    "objectives":["Dùng đúng cấu trúc điều kiện loại 3","Diễn đạt hậu quả của điều kiện quá khứ không thực","Phân biệt loại 2 (giả định hiện tại) và loại 3 (nuối tiếc quá khứ)"],
    "grammarHtml":"<b>Điều kiện loại 3:</b> If + past perfect, would have + V3<br>Dùng để nói về tình huống KHÔNG THỰC TẾ trong quá khứ và hệ quả tưởng tượng.<br><b>Ví dụ:</b> If I had studied harder, I would have passed the exam. (Nhưng thực tế: tôi không học chăm, và tôi trượt.)<br><b>Dạng khác của mệnh đề kết quả:</b> could have / might have + V3<br>If she had arrived on time, we could have caught the train.<br><b>Đảo ngữ (trang trọng):</b> Had I known, I would have helped.<br><b>So sánh với Loại 2:</b><br>Type 2: If I had more money, I would travel. (giả định hiện tại/tương lai)<br>Type 3: If I had had more money, I would have travelled. (quá khứ — không thể đổi)",
    "vocabBlock":[
      {"word":"regret","ipa":"/rɪˈɡret/","meaningVi":"hối hận, tiếc nuối","example":"I regret not taking that opportunity."},
      {"word":"consequence","ipa":"/ˈkɒnsɪkwəns/","meaningVi":"hậu quả, kết quả","example":"The consequences of that decision were serious."},
      {"word":"hypothetical","ipa":"/ˌhaɪpəˈθetɪkl/","meaningVi":"giả thuyết, giả định","example":"This is a hypothetical situation."},
      {"word":"outcome","ipa":"/ˈaʊtkʌm/","meaningVi":"kết quả, kết cục","example":"The outcome would have been different."},
      {"word":"in retrospect","ipa":"/ɪn ˈretrəspekt/","meaningVi":"nhìn lại, hồi tưởng","example":"In retrospect, I should have prepared more."}],
    "examples":[
      {"en":"If I had taken that job, I would have moved to London.","vi":"Nếu tôi đã nhận công việc đó, tôi đã chuyển đến London."},
      {"en":"She wouldn''t have been injured if she had worn her helmet.","vi":"Cô ấy đã không bị thương nếu cô ấy đội mũ bảo hiểm."},
      {"en":"If we had left earlier, we might have avoided the traffic.","vi":"Nếu chúng tôi đi sớm hơn, chúng tôi có thể đã tránh được kẹt xe."},
      {"en":"Had I known the truth, I would have acted differently.","vi":"Nếu tôi biết sự thật, tôi đã hành động khác."}],
    "commonMistakes":["❌ If I would have known → ✅ If I had known (mệnh đề if không dùng would)","❌ I would have pass → ✅ I would have passed (would have + V3)","❌ Nhầm loại 2 và loại 3: loại 3 LUÔN dùng past perfect trong mệnh đề if."],
    "tips":["Loại 3: cả hai mệnh đề đều ''trái thực tế'' trong quá khứ.","could/might have + V3 thể hiện khả năng, không chắc chắn bằng would have.","Đảo ngữ had I... = rút if, nâng had lên đầu: trang trọng hơn."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u03-l1-p1','b2-u03-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu điều kiện loại 3 ĐÚNG:","options":[{"id":"a","text":"If I had more time, I would help you."},{"id":"b","text":"If I had had more time, I would have helped you."},{"id":"c","text":"If I would have more time, I would help."}],"correctOptionId":"b","explanationVi":"Loại 3: If + past perfect, would have + V3."}'::jsonb),
 ('b2-u03-l1-p2','b2-u03-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chia động từ: ''If she ___ (study) harder, she ___ (pass) the exam.''","acceptedAnswers":["had studied / would have passed"],"explanationVi":"Loại 3: had studied → would have passed."}'::jsonb),
 ('b2-u03-l1-p3','b2-u03-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"regret","right":"hối hận"},{"left":"consequence","right":"hậu quả"},{"left":"outcome","right":"kết cục"},{"left":"in retrospect","right":"nhìn lại"}],"explanationVi":"Từ vựng tiếc nuối và hậu quả."}'::jsonb),
 ('b2-u03-l1-p4','b2-u03-l1','grammar_fill_blank',4,'practice','medium',false,'{"question":"Hoàn thành dạng đảo ngữ: ''___ I known, I would have helped.''","acceptedAnswers":["Had"],"explanationVi":"Đảo ngữ loại 3: Had + S + V3 (bỏ if)."}'::jsonb),
 ('b2-u03-l1-p5','b2-u03-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Nếu anh ấy đến đúng giờ, chúng tôi đã bắt được chuyến tàu.","acceptedAnswers":["If he had arrived on time, we would have caught the train.","If he had come on time, we would have caught the train."],"explanationVi":"Loại 3: had arrived + would have caught."}'::jsonb),
 ('b2-u03-l1-p6','b2-u03-l1','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''If I would have known, I would have told you.''","acceptedAnswers":["If I had known, I would have told you."],"explanationVi":"Mệnh đề if: had known (không dùng would)."}'::jsonb),
 ('b2-u03-l1-p7','b2-u03-l1','sentence_ordering',7,'practice','medium',false,'{"question":"Sắp xếp thành câu đúng:","tokens":["passed","would","have","she","harder","If","had","studied","she"],"correctOrder":[5,3,6,7,4,1,2,0,8],"explanationVi":"If she had studied harder, she would have passed."}'::jsonb),
 ('b2-u03-l1-q1','b2-u03-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG: nuối tiếc về quá khứ không thực:","options":[{"id":"a","text":"If I study more, I will pass."},{"id":"b","text":"If I had studied more, I would have passed."},{"id":"c","text":"If I studied more, I would pass."}],"correctOptionId":"b","explanationVi":"Loại 3 (quá khứ không thực): had studied + would have passed."}'::jsonb),
 ('b2-u03-l1-q2','b2-u03-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chia động từ: ''We ___ (not/be) late if she ___ (leave) earlier.''","acceptedAnswers":["wouldn''t have been / had left","would not have been / had left"],"explanationVi":"wouldn''t have been + had left."}'::jsonb),
 ('b2-u03-l1-q3','b2-u03-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Đâu là cấu trúc ĐÚNG của mệnh đề kết quả trong loại 3?","options":[{"id":"a","text":"would + V"},{"id":"b","text":"would have + V3"},{"id":"c","text":"had + V3"}],"correctOptionId":"b","explanationVi":"Mệnh đề kết quả loại 3: would/could/might have + V3."}'::jsonb),
 ('b2-u03-l1-q4','b2-u03-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Viết dạng đảo ngữ: ''If we had left earlier, we would have caught the train.''","acceptedAnswers":["Had we left earlier, we would have caught the train."],"explanationVi":"Had we + V3... (bỏ if, đảo had lên đầu)."}'::jsonb),
 ('b2-u03-l1-q5','b2-u03-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"hypothetical","right":"giả thuyết"},{"left":"in retrospect","right":"nhìn lại"},{"left":"regret","right":"hối hận"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l1-q6','b2-u03-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng (đảo ngữ):","tokens":["have","the","Had","arrived","train","caught","we","would","they","on","time"],"correctOrder":[2,3,9,10,7,1,5,6,0,4,8],"explanationVi":"Had they arrived on time, we would have caught the train."}'::jsonb),
 ('b2-u03-l1-q7','b2-u03-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''She might ___ (avoid) the accident if she ___ (drive) more carefully.''","acceptedAnswers":["might have avoided / had driven"],"explanationVi":"might have avoided + had driven."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u03-l2','B2','reading','b2-u03','normal',2,'Mixed Conditionals','Kết hợp điều kiện quá khứ và hiện tại',12,25,70,'{}'::jsonb,
  '{"warmup":"''Nếu tôi học y khoa (quá khứ — nhưng không học), giờ tôi đã là bác sĩ rồi (hiện tại).'' Bạn có thể nhận ra hai mốc thời gian khác nhau không?",
    "objectives":["Hiểu và dùng mixed conditionals kết hợp điều kiện quá khứ với hệ quả hiện tại","Hiểu mixed conditional hướng ngược lại: điều kiện hiện tại với hệ quả quá khứ","Phân biệt mixed conditionals với loại 2 và 3 đơn thuần"],
    "grammarHtml":"<b>Mixed Conditional (loại phổ biến nhất):</b><br>Điều kiện QUÁ KHỨ → hệ quả HIỆN TẠI<br>If + past perfect (if-clause), would + base verb (result-clause)<br><b>Ví dụ:</b> If she had studied medicine, she would be a doctor now. (Không học y = quá khứ; không phải bác sĩ = hiện tại)<br><br><b>Mixed Conditional (ngược lại — ít gặp hơn):</b><br>Điều kiện HIỆN TẠI → hệ quả QUÁ KHỨ<br>If + past simple (if-clause), would have + V3 (result-clause)<br><b>Ví dụ:</b> If he were braver, he would have spoken up at the meeting. (Nhút nhát = tính cách hiện tại; không lên tiếng = quá khứ)<br><br><b>Nhận biết:</b> mỗi mệnh đề ở một ''tầng thời gian'' khác nhau.",
    "vocabBlock":[
      {"word":"brave","ipa":"/breɪv/","meaningVi":"dũng cảm","example":"If he were braver, he would have spoken up."},
      {"word":"ambitious","ipa":"/æmˈbɪʃəs/","meaningVi":"tham vọng","example":"If she were more ambitious, she would have applied."},
      {"word":"as a result","ipa":"/æz ə rɪˈzʌlt/","meaningVi":"do đó, kết quả là","example":"As a result, nothing changed."},
      {"word":"presumably","ipa":"/prɪˈzjuːməbli/","meaningVi":"chắc là, có lẽ","example":"Presumably, things would be different now."}],
    "examples":[
      {"en":"If I had taken that job, I would be living in Paris now.","vi":"Nếu tôi đã nhận công việc đó, giờ tôi đang sống ở Paris."},
      {"en":"If she weren''t so shy, she would have spoken to him at the party.","vi":"Nếu cô ấy không nhút nhát như vậy, cô ấy đã nói chuyện với anh ấy ở bữa tiệc."},
      {"en":"If he had invested wisely, he would be rich now.","vi":"Nếu anh ấy đầu tư khôn ngoan, giờ anh ấy đã giàu rồi."}],
    "commonMistakes":["❌ Mixed conditional không phải là lỗi ngữ pháp — đó là cách kết hợp hai thời điểm có chủ đích.","Lưu ý: now/at the moment trong mệnh đề kết quả = dấu hiệu mixed conditional (quá khứ→hiện tại).","❌ If he was braver (loại 2) vs If he were braver (mixed — tính cách hiện tại)"],
    "tips":["now/currently trong mệnh đề kết quả + if + past perfect = mixed conditional.","Hỏi: ''điều kiện và hệ quả ở cùng thời gian không?'' → nếu không → mixed."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u03-l2-p1','b2-u03-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu mixed conditional ĐÚNG (quá khứ → hiện tại):","options":[{"id":"a","text":"If I had studied medicine, I would have been a doctor."},{"id":"b","text":"If I had studied medicine, I would be a doctor now."},{"id":"c","text":"If I study medicine, I will be a doctor."}],"correctOptionId":"b","explanationVi":"Quá khứ (had studied) → hiện tại (would be now) = mixed conditional."}'::jsonb),
 ('b2-u03-l2-p2','b2-u03-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chia động từ: ''If she ___ (invest) her money wisely, she ___ (be) wealthy now.''","acceptedAnswers":["had invested / would be"],"explanationVi":"Quá khứ (had invested) → hiện tại (would be now)."}'::jsonb),
 ('b2-u03-l2-p3','b2-u03-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"brave","right":"dũng cảm"},{"left":"ambitious","right":"tham vọng"},{"left":"as a result","right":"do đó"},{"left":"presumably","right":"chắc là"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l2-p4','b2-u03-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Mixed conditional (hiện tại → quá khứ): ''If he ___ (be) braver, he ___ (speak) up at the meeting.''","acceptedAnswers":["were / would have spoken"],"explanationVi":"Tính cách hiện tại (were) → hành động quá khứ (would have spoken)."}'::jsonb),
 ('b2-u03-l2-p5','b2-u03-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Nếu anh ấy đầu tư khôn ngoan, giờ anh ấy đã giàu rồi.","acceptedAnswers":["If he had invested wisely, he would be rich now.","If he had invested his money wisely, he would be wealthy now."],"explanationVi":"Had invested (quá khứ) → would be now (hiện tại)."}'::jsonb),
 ('b2-u03-l2-p6','b2-u03-l2','multiple_choice',6,'practice','medium',false,'{"question":"Đâu là dấu hiệu nhận biết mixed conditional (quá khứ → hiện tại)?","options":[{"id":"a","text":"would have + V3 trong mệnh đề kết quả"},{"id":"b","text":"now/currently trong mệnh đề kết quả"},{"id":"c","text":"if + present simple"}],"correctOptionId":"b","explanationVi":"now/currently + would + base verb = kết quả ở hiện tại."}'::jsonb),
 ('b2-u03-l2-p7','b2-u03-l2','error_correction',7,'practice','medium',false,'{"question":"Phân loại: ''If I had taken that job, I would be in London now.'' — Đây là loại mấy?","acceptedAnswers":["mixed conditional","mixed"],"explanationVi":"Quá khứ (had taken) → hiện tại (would be now) = mixed conditional."}'::jsonb),
 ('b2-u03-l2-q1','b2-u03-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Câu nào là mixed conditional?","options":[{"id":"a","text":"If I had worked harder, I would have succeeded."},{"id":"b","text":"If I had worked harder, I would be successful now."},{"id":"c","text":"If I work harder, I will succeed."}],"correctOptionId":"b","explanationVi":"had worked (quá khứ) + would be now (hiện tại) = mixed."}'::jsonb),
 ('b2-u03-l2-q2','b2-u03-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chia động từ: ''If she ___ (take) that scholarship, she ___ (study) abroad now.''","acceptedAnswers":["had taken / would be studying"],"explanationVi":"had taken (quá khứ) → would be studying now (hiện tại)."}'::jsonb),
 ('b2-u03-l2-q3','b2-u03-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Mixed conditional (hiện tại → quá khứ): ''If he ___ so lazy, he ___ the job.''","options":[{"id":"a","text":"wasn''t / would get"},{"id":"b","text":"weren''t / would have got"},{"id":"c","text":"hadn''t been / would have got"}],"correctOptionId":"b","explanationVi":"Tính cách hiện tại (weren''t) → quá khứ (would have got)."}'::jsonb),
 ('b2-u03-l2-q4','b2-u03-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chia động từ: ''If they ___ (plan) better, they ___ (not/be) in trouble now.''","acceptedAnswers":["had planned / wouldn''t be","had planned / would not be"],"explanationVi":"had planned (quá khứ) → wouldn''t be now (hiện tại)."}'::jsonb),
 ('b2-u03-l2-q5','b2-u03-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"ambitious","right":"tham vọng"},{"left":"brave","right":"dũng cảm"},{"left":"presumably","right":"chắc là"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l2-q6','b2-u03-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["now","she","had","If","medicine","would","be","studied","a","doctor"],"correctOrder":[3,1,2,4,7,5,6,8,9,0],"explanationVi":"If she had studied medicine, she would be a doctor now."}'::jsonb),
 ('b2-u03-l2-q7','b2-u03-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''If he ___ (not/be) so stubborn, he ___ (listen) to the advice.''","acceptedAnswers":["weren''t / would have listened","wasn''t / would have listened"],"explanationVi":"Tính cách hiện tại (weren''t/wasn''t) → quá khứ (would have listened)."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u03-l3','B2','reading','b2-u03','normal',3,'Wish / If Only','Mong ước & tiếc nuối: wish + past/past perfect/would',12,25,70,'{}'::jsonb,
  '{"warmup":"''Giá mà tôi có thể bay.'' / ''Giá mà tôi không nói điều đó.'' / ''Giá mà anh ấy ngừng làm ồn.'' — Ba câu này khác nhau về thời gian và ý nghĩa như thế nào?",
    "objectives":["Dùng wish/if only + past simple để mong ước trái thực tế hiện tại","Dùng wish/if only + past perfect để tiếc nuối quá khứ","Dùng wish/if only + would để diễn đạt muốn ai/điều gì thay đổi"],
    "grammarHtml":"<b>1. Wish/If only + past simple:</b> mong ước về hiện tại hoặc tương lai (trái thực tế)<br>I wish I were taller. (Tôi ước mình cao hơn — thực tế không cao.)<br>If only I spoke better English!<br><b>2. Wish/If only + past perfect:</b> tiếc nuối về quá khứ (không thể thay đổi)<br>I wish I had studied harder. (Giá mà tôi học chăm hơn — thực tế đã không học.)<br>If only she hadn''t said that!<br><b>3. Wish/If only + would:</b> muốn ai/điều gì thay đổi (thường bực bội hoặc mong ước người khác làm khác đi)<br>I wish he would stop talking. (Tôi ước anh ấy ngừng nói.)<br><b>Lưu ý:</b> wish + would KHÔNG dùng cho bản thân: ❌ I wish I would be... → ✅ I wish I were/was...",
    "vocabBlock":[
      {"word":"if only","ipa":"/ɪf ˈəʊnli/","meaningVi":"giá mà, ước gì","example":"If only I had more time!"},
      {"word":"I wish","ipa":"/aɪ wɪʃ/","meaningVi":"tôi ước","example":"I wish things were different."},
      {"word":"regretful","ipa":"/rɪˈɡretfl/","meaningVi":"đầy tiếc nuối","example":"She felt regretful about her words."},
      {"word":"hindsight","ipa":"/ˈhaɪndsaɪt/","meaningVi":"sự nhìn lại (quá khứ)","example":"With hindsight, I wish I had chosen differently."},
      {"word":"to no avail","ipa":"/tə nəʊ əˈveɪl/","meaningVi":"vô ích, không có kết quả","example":"She tried to change his mind, but to no avail."}],
    "examples":[
      {"en":"I wish I could travel more.","vi":"Tôi ước mình có thể đi du lịch nhiều hơn."},
      {"en":"If only I hadn''t said that — it hurt her feelings.","vi":"Giá mà tôi không nói điều đó — nó đã làm tổn thương cảm xúc của cô ấy."},
      {"en":"I wish the neighbours would turn down their music.","vi":"Tôi ước hàng xóm tắt bớt nhạc."},
      {"en":"She wishes she had taken that opportunity when she had the chance.","vi":"Cô ấy ước mình đã nắm bắt cơ hội đó khi còn có thể."}],
    "commonMistakes":["❌ I wish I would be taller. → ✅ I wish I were taller. (bản thân + present wish → past simple)","❌ If only I didn''t say that. → ✅ If only I hadn''t said that. (tiếc quá khứ → past perfect)","Wish + would KHÔNG áp dụng cho chủ ngữ chính là người nói."],
    "tips":["Hiện tại/tương lai mong ước → wish + past simple.","Quá khứ tiếc nuối → wish + past perfect.","Mong người khác đổi thay → wish + would."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u03-l3-p1','b2-u03-l3','multiple_choice',1,'practice','easy',false,'{"question":"Chọn cấu trúc ĐÚNG để mong ước điều trái thực tế hiện tại:","options":[{"id":"a","text":"I wish I am taller."},{"id":"b","text":"I wish I were taller."},{"id":"c","text":"I wish I would be taller."}],"correctOptionId":"b","explanationVi":"Mong ước hiện tại trái thực tế → wish + past simple (were)."}'::jsonb),
 ('b2-u03-l3-p2','b2-u03-l3','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''If only I ___ (not/say) that — I regret it now.''","acceptedAnswers":["hadn''t said","had not said"],"explanationVi":"Tiếc nuối quá khứ → wish/if only + past perfect."}'::jsonb),
 ('b2-u03-l3-p3','b2-u03-l3','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"if only","right":"giá mà"},{"left":"regretful","right":"đầy tiếc nuối"},{"left":"hindsight","right":"sự nhìn lại quá khứ"},{"left":"to no avail","right":"vô ích"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l3-p4','b2-u03-l3','grammar_fill_blank',4,'practice','medium',false,'{"question":"Điền đúng: ''I wish he ___ (stop) making noise — it''s driving me crazy.''","acceptedAnswers":["would stop"],"explanationVi":"Muốn người khác thay đổi → wish + would."}'::jsonb),
 ('b2-u03-l3-p5','b2-u03-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Giá mà cô ấy đã nhận công việc đó khi có cơ hội.","acceptedAnswers":["If only she had taken that job when she had the chance.","I wish she had taken that job when she had the chance."],"explanationVi":"Tiếc nuối quá khứ → if only/I wish + past perfect."}'::jsonb),
 ('b2-u03-l3-p6','b2-u03-l3','multiple_choice',6,'practice','medium',false,'{"question":"Chọn câu ĐÚNG: mong muốn người khác thay đổi hành vi:","options":[{"id":"a","text":"I wish she stopped talking."},{"id":"b","text":"I wish she would stop talking."},{"id":"c","text":"I wish she had stopped talking."}],"correctOptionId":"b","explanationVi":"Muốn người khác thay đổi hành vi → wish + would."}'::jsonb),
 ('b2-u03-l3-p7','b2-u03-l3','error_correction',7,'practice','medium',false,'{"question":"Sửa lỗi: ''I wish I would have more free time.''","acceptedAnswers":["I wish I had more free time."],"explanationVi":"Mong ước hiện tại về bản thân → wish + past simple (không dùng would)."}'::jsonb),
 ('b2-u03-l3-q1','b2-u03-l3','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG để tiếc nuối về quá khứ:","options":[{"id":"a","text":"I wish I studied harder."},{"id":"b","text":"I wish I had studied harder."},{"id":"c","text":"I wish I would study harder."}],"correctOptionId":"b","explanationVi":"Tiếc nuối quá khứ → wish + past perfect."}'::jsonb),
 ('b2-u03-l3-q2','b2-u03-l3','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''If only he ___ (be) more careful — now we have problems.''","acceptedAnswers":["had been"],"explanationVi":"Tiếc nuối quá khứ → if only + past perfect."}'::jsonb),
 ('b2-u03-l3-q3','b2-u03-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Câu nào diễn đạt ''tôi ước trời không mưa'' (hiện tại)?","options":[{"id":"a","text":"I wish it didn''t rain."},{"id":"b","text":"I wish it hadn''t rained."},{"id":"c","text":"I wish it would rain."}],"correctOptionId":"a","explanationVi":"Mong ước hiện tại trái thực tế → wish + past simple."}'::jsonb),
 ('b2-u03-l3-q4','b2-u03-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng: ''She wishes her boss ___ (give) her more feedback.''","acceptedAnswers":["would give"],"explanationVi":"Muốn người khác thay đổi → wish + would."}'::jsonb),
 ('b2-u03-l3-q5','b2-u03-l3','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối cụm từ với nghĩa:","pairs":[{"left":"if only","right":"giá mà"},{"left":"to no avail","right":"vô ích"},{"left":"regretful","right":"đầy tiếc nuối"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l3-q6','b2-u03-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["the","had","If","I","only","taken","opportunity"],"correctOrder":[2,0,3,4,1,5,6],"explanationVi":"If only I had taken the opportunity."}'::jsonb),
 ('b2-u03-l3-q7','b2-u03-l3','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''I wish I ___ (can) speak three languages fluently.''","acceptedAnswers":["could"],"explanationVi":"Mong ước hiện tại → wish + past simple (could = past của can)."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u03-l4','B2','reading','b2-u03','normal',4,'Regrets & Turning Points','Đọc hiểu: Nuối tiếc & bước ngoặt',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc đoạn văn về những quyết định đã thay đổi cuộc đời — và những gì có thể đã xảy ra nếu họ chọn khác đi.",
    "objectives":["Đọc hiểu văn bản B2 về tiếc nuối và giả định","Nhận biết conditional type 3, mixed conditionals và wish trong ngữ cảnh","Suy luận thái độ của tác giả"],
    "vocabBlock":[
      {"word":"dilemma","ipa":"/dɪˈlemə/","meaningVi":"tình thế lưỡng nan","example":"She faced a difficult dilemma."},
      {"word":"take a risk","ipa":"/teɪk ə rɪsk/","meaningVi":"chấp nhận rủi ro","example":"He decided to take a risk and start his own business."},
      {"word":"with hindsight","ipa":"/wɪð ˈhaɪndsaɪt/","meaningVi":"nhìn lại","example":"With hindsight, it was the wrong choice."},
      {"word":"irreversible","ipa":"/ˌɪrɪˈvɜːsəbl/","meaningVi":"không thể đảo ngược","example":"Some decisions are irreversible."}],
    "examples":[
      {"en":"At 22, Maria stood at a crossroads. She had been offered a place at a prestigious university in Paris, but accepting it meant leaving her family and her partner behind. She chose to stay. Now, fifteen years later, she looks back with mixed feelings. ''If I had gone to Paris, I would probably be working in international business now,'' she admits. ''With hindsight, I wish I had taken that leap. But if I had gone, I might never have started my own company here — and that has been the most rewarding thing I''ve ever done. I sometimes wish things had turned out differently, but I also know that every decision shapes who you become. If only we could see the full consequences of our choices before we make them.''","vi":"Năm 22 tuổi, Maria đứng trước một ngã rẽ. Cô được nhận vào một trường đại học danh tiếng ở Paris, nhưng chấp nhận có nghĩa là phải rời xa gia đình và người yêu. Cô chọn ở lại. Giờ, mười lăm năm sau, cô nhìn lại với cảm xúc lẫn lộn. ''Nếu tôi đã đến Paris, bây giờ có lẽ tôi đang làm việc trong lĩnh vực kinh doanh quốc tế,'' cô thừa nhận. ''Nhìn lại, tôi ước mình đã dám bước. Nhưng nếu tôi đã đi, tôi có thể không bao giờ khởi nghiệp ở đây — và đó là điều có ý nghĩa nhất tôi từng làm. Tôi đôi khi ước mọi thứ đã khác đi, nhưng tôi cũng biết rằng mỗi quyết định định hình con người bạn trở thành. Giá mà chúng ta có thể nhìn thấy hậu quả đầy đủ của các lựa chọn trước khi đưa ra.''"}],
    "commonMistakes":["Đọc kỹ để phân biệt loại 3 (had gone → would be now = mixed) và wish + past perfect."],
    "tips":["Chú ý cấu trúc: ''would probably be...now'' sau ''if I had gone'' = mixed conditional.","wish + had taken = tiếc nuối quá khứ."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u03-l4-p1','b2-u03-l4','multiple_choice',1,'practice','easy',false,'{"question":"Maria đứng trước quyết định gì lúc 22 tuổi?","options":[{"id":"a","text":"Lập gia đình hay không"},{"id":"b","text":"Đi Paris học hay ở lại"},{"id":"c","text":"Chuyển sang ngành khác"}],"correctOptionId":"b","explanationVi":"''offered a place at a prestigious university in Paris''."}'::jsonb),
 ('b2-u03-l4-p2','b2-u03-l4','multiple_choice',2,'practice','easy',false,'{"question":"Câu ''If I had gone to Paris, I would probably be working in international business now'' là loại conditional nào?","options":[{"id":"a","text":"Type 3"},{"id":"b","text":"Mixed conditional"},{"id":"c","text":"Type 2"}],"correctOptionId":"b","explanationVi":"Quá khứ (had gone) → hiện tại (would be now) = mixed conditional."}'::jsonb),
 ('b2-u03-l4-p3','b2-u03-l4','multiple_choice',3,'practice','medium',false,'{"question":"Maria có hoàn toàn hối hận về quyết định của mình không?","options":[{"id":"a","text":"Có, hoàn toàn hối hận"},{"id":"b","text":"Không, cô ấy chưa bao giờ nghĩ đến"},{"id":"c","text":"Có lẫn lộn — vừa tiếc vừa trân trọng những gì đạt được"}],"correctOptionId":"c","explanationVi":"''looks back with mixed feelings'' — both regret and appreciation."}'::jsonb),
 ('b2-u03-l4-p4','b2-u03-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"dilemma","right":"tình thế lưỡng nan"},{"left":"take a risk","right":"chấp nhận rủi ro"},{"left":"with hindsight","right":"nhìn lại"},{"left":"irreversible","right":"không thể đảo ngược"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l4-p5','b2-u03-l4','multiple_choice',5,'practice','medium',false,'{"question":"Cấu trúc nào trong bài diễn đạt tiếc nuối về quá khứ?","options":[{"id":"a","text":"I wish I had taken that leap"},{"id":"b","text":"I would probably be working"},{"id":"c","text":"every decision shapes who you become"}],"correctOptionId":"a","explanationVi":"wish + past perfect = tiếc nuối quá khứ."}'::jsonb),
 ('b2-u03-l4-p6','b2-u03-l4','multiple_choice',6,'practice','medium',false,'{"question":"''If only we could see the full consequences...'' — câu này dùng cấu trúc nào?","options":[{"id":"a","text":"wish + past perfect"},{"id":"b","text":"if only + past simple (could)"},{"id":"c","text":"mixed conditional"}],"correctOptionId":"b","explanationVi":"if only + could (past simple của can) = mong ước hiện tại."}'::jsonb),
 ('b2-u03-l4-p7','b2-u03-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành câu của Maria: ''I wish I ___ (take) that leap.''","acceptedAnswers":["had taken"],"explanationVi":"Tiếc nuối quá khứ → wish + past perfect."}'::jsonb),
 ('b2-u03-l4-q1','b2-u03-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Maria chọn ở lại vì lý do gì?","options":[{"id":"a","text":"Không thích Paris"},{"id":"b","text":"Muốn ở gần gia đình và người yêu"},{"id":"c","text":"Không được nhận vào trường"}],"correctOptionId":"b","explanationVi":"''meant leaving her family and her partner behind'' — nên cô chọn ở lại."}'::jsonb),
 ('b2-u03-l4-q2','b2-u03-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Điều Maria trân trọng nhất từ quyết định ở lại là?","options":[{"id":"a","text":"Sự nghiệp quốc tế"},{"id":"b","text":"Công ty riêng cô đã xây dựng"},{"id":"c","text":"Giải thưởng cô đã nhận"}],"correctOptionId":"b","explanationVi":"''started my own company here — the most rewarding thing.''"}'::jsonb),
 ('b2-u03-l4-q3','b2-u03-l4','multiple_choice',10,'quiz','medium',true,'{"question":"''If I had gone, I might never have started my own company.'' — Đây là loại conditional nào?","options":[{"id":"a","text":"Type 2"},{"id":"b","text":"Type 3"},{"id":"c","text":"Mixed conditional"}],"correctOptionId":"b","explanationVi":"had gone + might have started = cùng ở quá khứ = type 3."}'::jsonb),
 ('b2-u03-l4-q4','b2-u03-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''I wish things ___ (turn out) differently.''","acceptedAnswers":["had turned out"],"explanationVi":"Tiếc nuối quá khứ → wish + past perfect."}'::jsonb),
 ('b2-u03-l4-q5','b2-u03-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Từ ''dilemma'' trong bài có nghĩa là?","options":[{"id":"a","text":"Cơ hội tốt"},{"id":"b","text":"Tình thế khó chọn lựa"},{"id":"c","text":"Bước ngoặt tích cực"}],"correctOptionId":"b","explanationVi":"dilemma = tình thế lưỡng nan."}'::jsonb),
 ('b2-u03-l4-q6','b2-u03-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"irreversible","right":"không thể đảo ngược"},{"left":"take a risk","right":"chấp nhận rủi ro"},{"left":"dilemma","right":"tình thế lưỡng nan"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l4-q7','b2-u03-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Hoàn thành mixed conditional: ''If she ___ (go) to Paris, she ___ (be) in international business now.''","acceptedAnswers":["had gone / would be"],"explanationVi":"had gone (quá khứ) → would be now (hiện tại) = mixed."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u03-l5','B2','reading','b2-u03','unit_review',5,'Unit 3 Review','Ôn tập Unit 3: Nếu như? — Suy đoán & giả định',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 3: conditional type 3, mixed conditionals và wish/if only.","objectives":["Tổng hợp can-do Unit 3","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u03-l5-q1','b2-u03-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Chia động từ (loại 3): ''If she ___ (study) harder, she ___ (pass).''","acceptedAnswers":["had studied / would have passed"],"explanationVi":"Loại 3: had studied + would have passed."}'::jsonb),
 ('b2-u03-l5-q2','b2-u03-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu mixed conditional ĐÚNG:","options":[{"id":"a","text":"If he had saved money, he would be rich now."},{"id":"b","text":"If he had saved money, he would have been rich."},{"id":"c","text":"If he saves money, he will be rich."}],"correctOptionId":"a","explanationVi":"Quá khứ (had saved) → hiện tại (would be now) = mixed."}'::jsonb),
 ('b2-u03-l5-q3','b2-u03-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG tiếc nuối quá khứ với wish:","options":[{"id":"a","text":"I wish I took that chance."},{"id":"b","text":"I wish I had taken that chance."},{"id":"c","text":"I wish I would take that chance."}],"correctOptionId":"b","explanationVi":"Tiếc nuối quá khứ → wish + past perfect."}'::jsonb),
 ('b2-u03-l5-q4','b2-u03-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Điền đúng: ''If only he ___ (not/make) that mistake — things would be different now.''","acceptedAnswers":["hadn''t made","had not made"],"explanationVi":"Tiếc quá khứ → if only + past perfect."}'::jsonb),
 ('b2-u03-l5-q5','b2-u03-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào diễn đạt ''muốn người khác ngừng làm điều gì đó''?","options":[{"id":"a","text":"I wish they stopped."},{"id":"b","text":"I wish they would stop."},{"id":"c","text":"I wish they had stopped."}],"correctOptionId":"b","explanationVi":"Muốn người khác thay đổi hành vi → wish + would."}'::jsonb),
 ('b2-u03-l5-q6','b2-u03-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"regret","right":"hối hận"},{"left":"consequence","right":"hậu quả"},{"left":"outcome","right":"kết cục"},{"left":"in retrospect","right":"nhìn lại"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u03-l5-q7','b2-u03-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Mixed conditional: ''If she ___ (be) more confident, she ___ (apply) for that job last year.''","acceptedAnswers":["were / would have applied"],"explanationVi":"Tính cách hiện tại (were) → quá khứ (would have applied)."}'::jsonb),
 ('b2-u03-l5-q8','b2-u03-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng (đảo ngữ loại 3):","tokens":["I","have","helped","Had","known","would","I"],"correctOrder":[3,0,4,1,2,5,6],"explanationVi":"Had I known, I would have helped."}'::jsonb),
 ('b2-u03-l5-q9','b2-u03-l5','multiple_choice',9,'quiz','medium',true,'{"question":"Điều gì phân biệt mixed conditional với loại 3?","options":[{"id":"a","text":"Mixed dùng would have trong mệnh đề kết quả"},{"id":"b","text":"Mixed kết hợp hai mốc thời gian khác nhau"},{"id":"c","text":"Mixed chỉ dùng với wish"}],"correctOptionId":"b","explanationVi":"Mixed conditional = điều kiện và kết quả ở hai thời điểm khác nhau."}'::jsonb),
 ('b2-u03-l5-q10','b2-u03-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Chia động từ: ''If he ___ (not/be) so shy, he ___ (speak) to her at the party last night.''","acceptedAnswers":["weren''t / would have spoken","wasn''t / would have spoken"],"explanationVi":"Tính cách hiện tại (weren''t) → hành động quá khứ (would have spoken) = mixed."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u03-l5' WHERE id = 'b2-u03';
