-- ══════════════════════════════════════════════════════════════════════════
-- B2 Units 04-05
-- Unit 04: On Condition That — Alternatives to 'if', Expressing Purpose
-- Unit 05: It Is Said That... — Passive Voice: Modals, Reporting, Need
-- ══════════════════════════════════════════════════════════════════════════

-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║ BƯỚC 0 — DỌN SẠCH (idempotent)                                           ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B2' AND id IN ('b2-u04','b2-u05');

DELETE FROM learning_lesson_activities
 WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B2' AND unit_id IN ('b2-u04','b2-u05'));

DELETE FROM learning_lessons WHERE level_code = 'B2' AND unit_id IN ('b2-u04','b2-u05');

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 04 — On Condition That
-- Alternatives to 'if'; Expressing Purpose (so as to / in order to)
-- ══════════════════════════════════════════════════════════════════════════

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u04-l1','B2','reading','b2-u04','normal',1,'Alternatives to "if"','unless / provided / as long as / on condition that / supposing',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn có thể nói ''You can go... (điều kiện)'' bằng cách nào khác ngoài ''if''? Nghĩ 30 giây.",
    "objectives":["Dùng unless, provided (that), as long as, on condition that, supposing để diễn đạt điều kiện","Phân biệt sắc thái giữa các liên từ điều kiện","Dùng đúng trong văn bản trang trọng và thông thường"],
    "grammarHtml":"<b>Các liên từ điều kiện thay thế ''if'':</b><br><b>unless</b> = if...not / except if: <i>You''ll fail unless you study.</i> (= if you don''t study)<br><b>provided (that) / providing (that)</b> = only if (nhấn mạnh điều kiện bắt buộc): <i>You can borrow it provided you return it.</i><br><b>as long as</b> = miễn là (điều kiện cần duy trì): <i>I''ll support you as long as you''re honest.</i><br><b>on condition that</b> = với điều kiện là (trang trọng): <i>He agreed on condition that he received payment first.</i><br><b>supposing (that) / suppose</b> = giả sử như (điều kiện giả định): <i>Supposing you won the lottery, what would you do?</i><br><b>in case</b> = phòng khi (để chuẩn bị cho khả năng): <i>Take an umbrella in case it rains.</i>",
    "vocabBlock":[
      {"word":"unless","ipa":"/ənˈles/","meaningVi":"trừ phi, nếu không","example":"You won''t succeed unless you try."},
      {"word":"provided that","ipa":"/prəˈvaɪdɪd ðæt/","meaningVi":"với điều kiện là, miễn là","example":"You can leave early provided that you finish your work."},
      {"word":"as long as","ipa":"/æz lɒŋ æz/","meaningVi":"miễn là, chừng nào","example":"I''ll help you as long as you need me."},
      {"word":"on condition that","ipa":"/ɒn kənˈdɪʃn ðæt/","meaningVi":"với điều kiện là","example":"He agreed on condition that he was paid."},
      {"word":"supposing","ipa":"/səˈpəʊzɪŋ/","meaningVi":"giả sử như","example":"Supposing you could fly, where would you go?"},
      {"word":"in case","ipa":"/ɪn keɪs/","meaningVi":"phòng khi, đề phòng","example":"Take your keys in case you come back late."}],
    "examples":[
      {"en":"You can stay unless you cause problems.","vi":"Bạn có thể ở lại trừ phi bạn gây rắc rối."},
      {"en":"I''ll lend you my car provided you drive carefully.","vi":"Tôi sẽ cho bạn mượn xe với điều kiện bạn lái cẩn thận."},
      {"en":"She''ll keep the job as long as the salary is good.","vi":"Cô ấy sẽ giữ công việc miễn là lương tốt."},
      {"en":"He signed the contract on condition that he received a bonus.","vi":"Anh ấy ký hợp đồng với điều kiện được nhận tiền thưởng."}],
    "commonMistakes":["❌ Unless you don''t come → ✅ Unless you come (unless đã có nghĩa phủ định)","in case (phòng khi) ≠ in case of (trong trường hợp có): In case it rains... vs In case of fire, leave the building.","provided/providing + that → both correct."],
    "tips":["unless = if not → không dùng thêm not.","in case nhấn sự chuẩn bị trước; if nhấn điều kiện thực sự."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u04-l1-p1','b2-u04-l1','multiple_choice',1,'practice','easy',false,'{"question":"''You won''t pass ___ you study harder.'' — Điền liên từ phù hợp:","options":[{"id":"a","text":"unless"},{"id":"b","text":"provided"},{"id":"c","text":"in case"}],"correctOptionId":"a","explanationVi":"unless = if...not → unless you study = if you don''t study."}'::jsonb),
 ('b2-u04-l1-p2','b2-u04-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''You can borrow my laptop ___ you return it by Friday.''","acceptedAnswers":["provided","provided that","providing","providing that","as long as"],"explanationVi":"provided that / as long as = điều kiện bắt buộc."}'::jsonb),
 ('b2-u04-l1-p3','b2-u04-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối liên từ với nghĩa:","pairs":[{"left":"unless","right":"trừ phi"},{"left":"as long as","right":"miễn là"},{"left":"in case","right":"phòng khi"},{"left":"supposing","right":"giả sử như"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l1-p4','b2-u04-l1','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''Unless you don''t bring your passport, you can''t board the plane.''","acceptedAnswers":["Unless you bring your passport, you can''t board the plane.","If you don''t bring your passport, you can''t board the plane."],"explanationVi":"unless đã có nghĩa phủ định → bỏ don''t."}'::jsonb),
 ('b2-u04-l1-p5','b2-u04-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Anh ấy đồng ý ký hợp đồng với điều kiện được tăng lương.","acceptedAnswers":["He agreed to sign the contract on condition that he received a pay rise.","He agreed on condition that his salary was increased."],"explanationVi":"on condition that = với điều kiện là."}'::jsonb),
 ('b2-u04-l1-p6','b2-u04-l1','grammar_fill_blank',6,'practice','medium',false,'{"question":"Điền đúng: ''Take your phone ___ you get lost.''","acceptedAnswers":["in case"],"explanationVi":"in case = phòng khi."}'::jsonb),
 ('b2-u04-l1-p7','b2-u04-l1','multiple_choice',7,'practice','medium',false,'{"question":"Phân biệt: ''unless'' và ''in case'' — câu nào dùng ''in case''?","options":[{"id":"a","text":"You''ll fail ___ you study."},{"id":"b","text":"Take notes ___ you forget."},{"id":"c","text":"I''ll go ___ the weather is good."}],"correctOptionId":"b","explanationVi":"in case = chuẩn bị trước phòng khi xảy ra."}'::jsonb),
 ('b2-u04-l1-q1','b2-u04-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''if...not''?","options":[{"id":"a","text":"provided"},{"id":"b","text":"unless"},{"id":"c","text":"supposing"}],"correctOptionId":"b","explanationVi":"unless = if not."}'::jsonb),
 ('b2-u04-l1-q2','b2-u04-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''___ you could travel anywhere, where would you go?''","acceptedAnswers":["Supposing","Suppose"],"explanationVi":"Supposing = giả sử như (điều kiện giả định)."}'::jsonb),
 ('b2-u04-l1-q3','b2-u04-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Chọn câu ĐÚNG (unless không dùng not):","options":[{"id":"a","text":"Unless you don''t hurry, you''ll be late."},{"id":"b","text":"Unless you hurry, you''ll be late."},{"id":"c","text":"Unless you not hurry, you''ll be late."}],"correctOptionId":"b","explanationVi":"unless đã có nghĩa phủ định → chỉ dùng unless + khẳng định."}'::jsonb),
 ('b2-u04-l1-q4','b2-u04-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng (trang trọng): ''She agreed to help ___ she was given credit.''","acceptedAnswers":["on condition that","provided that","providing that"],"explanationVi":"on condition that / provided that = trang trọng."}'::jsonb),
 ('b2-u04-l1-q5','b2-u04-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối cụm từ với nghĩa:","pairs":[{"left":"on condition that","right":"với điều kiện là"},{"left":"in case","right":"phòng khi"},{"left":"as long as","right":"miễn là"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l1-q6','b2-u04-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["provided","finish","the","that","you","go","can","you","work"],"correctOrder":[5,6,0,1,4,2,3,7,8],"explanationVi":"You can go provided that you finish the work."}'::jsonb),
 ('b2-u04-l1-q7','b2-u04-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền đúng: ''I''ll support the project ___ the budget doesn''t exceed $10,000.''","acceptedAnswers":["as long as","provided","provided that","providing","providing that","on condition that"],"explanationVi":"Điều kiện cần duy trì → as long as / provided that."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u04-l2','B2','reading','b2-u04','normal',2,'Expressing Purpose','in order to / so as to / so that / for the purpose of',12,25,70,'{}'::jsonb,
  '{"warmup":"''Tôi học tiếng Anh để... (mục đích).'' Bạn có thể nói câu này theo bao nhiêu cách khác nhau?",
    "objectives":["Dùng in order to, so as to, so that, for the purpose of để diễn đạt mục đích","Phân biệt cách dùng với to-infinitive đơn giản","Dùng đúng dạng phủ định in order not to / so as not to"],
    "grammarHtml":"<b>Diễn đạt mục đích:</b><br><b>to / in order to / so as to + infinitive:</b> cùng chủ ngữ<br><i>She studied hard to pass the exam.</i> = <i>...in order to pass</i> = <i>...so as to pass</i><br><b>Phủ định:</b> in order not to / so as not to (KHÔNG dùng ''to not'')<br><i>He left early so as not to miss the train.</i><br><b>so that + clause:</b> khác chủ ngữ hoặc nhấn kết quả<br><i>She spoke slowly so that everyone could understand.</i><br><b>for the purpose of + V-ing:</b> trang trọng<br><i>The form is used for the purpose of collecting data.</i><br><b>Thứ tự ưu tiên:</b> to > in order to (trang trọng hơn) > so as to (rất trang trọng) > so that (khi chủ ngữ khác nhau).",
    "vocabBlock":[
      {"word":"in order to","ipa":"/ɪn ˈɔːdə tə/","meaningVi":"để, nhằm","example":"She trained daily in order to run the marathon."},
      {"word":"so as to","ipa":"/səʊ æz tə/","meaningVi":"để, nhằm (trang trọng)","example":"He arrived early so as to get a good seat."},
      {"word":"so that","ipa":"/səʊ ðæt/","meaningVi":"để cho, nhằm mục đích","example":"Speak clearly so that everyone can hear."},
      {"word":"for the purpose of","ipa":"/fɔː ðə ˈpɜːpəs əv/","meaningVi":"nhằm mục đích (trang trọng)","example":"Data is collected for the purpose of research."},
      {"word":"aim","ipa":"/eɪm/","meaningVi":"nhằm, hướng đến","example":"The policy aims to reduce poverty."}],
    "examples":[
      {"en":"He saved money in order to buy a house.","vi":"Anh ấy tiết kiệm tiền để mua nhà."},
      {"en":"She spoke quietly so as not to wake the baby.","vi":"Cô ấy nói nhỏ để không đánh thức em bé."},
      {"en":"We hired a translator so that the clients could understand the presentation.","vi":"Chúng tôi thuê phiên dịch để khách hàng có thể hiểu bài thuyết trình."},
      {"en":"The system was designed for the purpose of improving efficiency.","vi":"Hệ thống được thiết kế nhằm mục đích cải thiện hiệu quả."}],
    "commonMistakes":["❌ so as not study → ✅ so as not to study","❌ in order that she study (cùng chủ ngữ) → ✅ in order to study","❌ for the purpose to + V → ✅ for the purpose of + V-ing"],
    "tips":["Cùng chủ ngữ: dùng in order to / so as to.","Khác chủ ngữ: dùng so that + can/could/would.","Trang trọng: in order to > to."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u04-l2-p1','b2-u04-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu diễn đạt mục đích ĐÚNG (cùng chủ ngữ, trang trọng):","options":[{"id":"a","text":"She studied so that to pass."},{"id":"b","text":"She studied in order to pass."},{"id":"c","text":"She studied for passing."}],"correctOptionId":"b","explanationVi":"Cùng chủ ngữ + trang trọng → in order to + infinitive."}'::jsonb),
 ('b2-u04-l2-p2','b2-u04-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''He left early ___ miss the train.'' (phủ định, trang trọng)","acceptedAnswers":["so as not to","in order not to"],"explanationVi":"Phủ định mục đích → so as not to / in order not to."}'::jsonb),
 ('b2-u04-l2-p3','b2-u04-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối cụm từ với nghĩa:","pairs":[{"left":"in order to","right":"để, nhằm"},{"left":"so that","right":"để cho"},{"left":"so as to","right":"để (trang trọng)"},{"left":"for the purpose of","right":"nhằm mục đích (trang trọng)"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l2-p4','b2-u04-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Chuyển sang so that: ''They hired a guide ___ (understand) the local culture.''","acceptedAnswers":["so that they could understand","so that the tourists could understand"],"explanationVi":"Khác chủ ngữ → so that + could."}'::jsonb),
 ('b2-u04-l2-p5','b2-u04-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Cô ấy nói chậm để mọi người có thể hiểu.","acceptedAnswers":["She spoke slowly so that everyone could understand.","She spoke slowly so that people could understand."],"explanationVi":"Khác chủ ngữ (she/everyone) → so that + could."}'::jsonb),
 ('b2-u04-l2-p6','b2-u04-l2','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''The app was designed for the purpose to collect user data.''","acceptedAnswers":["The app was designed for the purpose of collecting user data."],"explanationVi":"for the purpose of + V-ing."}'::jsonb),
 ('b2-u04-l2-p7','b2-u04-l2','multiple_choice',7,'practice','medium',false,'{"question":"Khi nào dùng ''so that'' thay vì ''in order to''?","options":[{"id":"a","text":"Khi chủ ngữ hai vế giống nhau"},{"id":"b","text":"Khi chủ ngữ hai vế khác nhau"},{"id":"c","text":"Khi muốn nói trang trọng hơn"}],"correctOptionId":"b","explanationVi":"so that dùng khi chủ ngữ mệnh đề mục đích khác chủ ngữ chính."}'::jsonb),
 ('b2-u04-l2-q1','b2-u04-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG: mục đích (phủ định, trang trọng):","options":[{"id":"a","text":"He whispered to not wake her."},{"id":"b","text":"He whispered in order not to wake her."},{"id":"c","text":"He whispered so as not wake her."}],"correctOptionId":"b","explanationVi":"in order not to + infinitive = mục đích phủ định."}'::jsonb),
 ('b2-u04-l2-q2','b2-u04-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''The notice was posted ___ students know the deadline.''","acceptedAnswers":["so that"],"explanationVi":"Khác chủ ngữ → so that."}'::jsonb),
 ('b2-u04-l2-q3','b2-u04-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Câu nào tương đương: ''She exercised in order to stay healthy.''?","options":[{"id":"a","text":"She exercised so that stay healthy."},{"id":"b","text":"She exercised so as to stay healthy."},{"id":"c","text":"She exercised for to stay healthy."}],"correctOptionId":"b","explanationVi":"in order to = so as to (cùng chủ ngữ)."}'::jsonb),
 ('b2-u04-l2-q4','b2-u04-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Viết lại dùng for the purpose of: ''The survey aims to measure customer satisfaction.''","acceptedAnswers":["The survey is used for the purpose of measuring customer satisfaction.","The survey was conducted for the purpose of measuring customer satisfaction."],"explanationVi":"for the purpose of + V-ing."}'::jsonb),
 ('b2-u04-l2-q5','b2-u04-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối cụm từ với nghĩa:","pairs":[{"left":"so as not to","right":"để không (phủ định)"},{"left":"in order to","right":"để, nhằm"},{"left":"for the purpose of","right":"nhằm mục đích"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l2-q6','b2-u04-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["disturb","so","as","the","not","neighbours","to","He","quietly","spoke"],"correctOrder":[7,9,1,2,4,5,3,6,8,0],"explanationVi":"He spoke quietly so as not to disturb the neighbours."}'::jsonb),
 ('b2-u04-l2-q7','b2-u04-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền đúng: ''The government reduced taxes ___ encourage foreign investment.''","acceptedAnswers":["in order to","so as to","to"],"explanationVi":"Mục đích cùng chủ ngữ → in order to / so as to / to."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u04-l3','B2','reading','b2-u04','normal',3,'Negotiation & Agreement Vocabulary','Từ vựng đàm phán & thương lượng B2',12,25,70,'{}'::jsonb,
  '{"warmup":"Trong đàm phán, bạn cần nói ''điều kiện'', ''nhượng bộ'', ''đồng ý có điều kiện''... Bạn biết những từ nào?",
    "objectives":["Học 10 từ vựng B2 về đàm phán và thoả thuận","Dùng từ trong ngữ cảnh điều kiện và mục đích","Phân biệt sắc thái trang trọng/thông thường"],
    "vocabBlock":[
      {"word":"negotiate","ipa":"/nɪˈɡəʊʃieɪt/","meaningVi":"đàm phán, thương lượng","example":"They negotiated a new contract."},
      {"word":"compromise","ipa":"/ˈkɒmprəmaɪz/","meaningVi":"nhượng bộ, thoả hiệp","example":"Both sides had to compromise."},
      {"word":"concession","ipa":"/kənˈseʃn/","meaningVi":"sự nhượng bộ","example":"The company made several concessions."},
      {"word":"stipulate","ipa":"/ˈstɪpjuleɪt/","meaningVi":"quy định, điều kiện hoá","example":"The contract stipulates a three-month notice period."},
      {"word":"clause","ipa":"/klɔːz/","meaningVi":"điều khoản (hợp đồng)","example":"There is a penalty clause in the agreement."},
      {"word":"breach","ipa":"/briːtʃ/","meaningVi":"vi phạm (hợp đồng)","example":"Failing to deliver is a breach of contract."},
      {"word":"comply with","ipa":"/kəmˈplaɪ wɪð/","meaningVi":"tuân thủ, chấp hành","example":"All staff must comply with safety regulations."},
      {"word":"obligation","ipa":"/ˌɒblɪˈɡeɪʃn/","meaningVi":"nghĩa vụ, bổn phận","example":"You have an obligation to inform us."},
      {"word":"mutual","ipa":"/ˈmjuːtʃuəl/","meaningVi":"lẫn nhau, tương hỗ","example":"The agreement is based on mutual trust."},
      {"word":"contingent on","ipa":"/kənˈtɪndʒənt ɒn/","meaningVi":"phụ thuộc vào, tuỳ theo","example":"The deal is contingent on board approval."}],
    "examples":[
      {"en":"The deal was signed on condition that both parties comply with all clauses.","vi":"Hợp đồng được ký với điều kiện cả hai bên tuân thủ tất cả điều khoản."},
      {"en":"She agreed to compromise provided that the salary was negotiated upward.","vi":"Cô ấy đồng ý nhượng bộ với điều kiện lương được thương lượng tăng lên."},
      {"en":"The project is contingent on securing funding by March.","vi":"Dự án phụ thuộc vào việc huy động tài trợ trước tháng Ba."}],
    "commonMistakes":["comply with (đúng) ≠ comply to (sai): you comply WITH regulations.","breach of contract (vi phạm hợp đồng) — breach dùng như danh từ.","contingent on (phụ thuộc vào) ≠ conditioned to."],
    "tips":["negotiate (đàm phán) → negotiation (danh từ) → negotiator (người đàm phán).","stipulate điều kiện trong văn bản pháp lý/hợp đồng."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u04-l3-p1','b2-u04-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"negotiate","right":"đàm phán"},{"left":"compromise","right":"nhượng bộ"},{"left":"clause","right":"điều khoản"},{"left":"breach","right":"vi phạm"}],"explanationVi":"Từ vựng hợp đồng và đàm phán."}'::jsonb),
 ('b2-u04-l3-p2','b2-u04-l3','vocabulary_match',2,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"stipulate","right":"quy định"},{"left":"comply with","right":"tuân thủ"},{"left":"obligation","right":"nghĩa vụ"},{"left":"mutual","right":"lẫn nhau"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l3-p3','b2-u04-l3','multiple_choice',3,'practice','easy',false,'{"question":"Điền từ đúng: ''The deal is ___ on board approval.''","options":[{"id":"a","text":"contingent"},{"id":"b","text":"mutual"},{"id":"c","text":"stipulate"}],"correctOptionId":"a","explanationVi":"contingent on = phụ thuộc vào."}'::jsonb),
 ('b2-u04-l3-p4','b2-u04-l3','multiple_choice',4,'practice','medium',false,'{"question":"Điền từ đúng: ''All employees must ___ company health and safety regulations.''","options":[{"id":"a","text":"comply with"},{"id":"b","text":"comply to"},{"id":"c","text":"breach"}],"correctOptionId":"a","explanationVi":"comply WITH (không dùng comply to)."}'::jsonb),
 ('b2-u04-l3-p5','b2-u04-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Hợp đồng quy định một khoảng thời gian thông báo ba tháng.","acceptedAnswers":["The contract stipulates a three-month notice period."],"explanationVi":"stipulate = quy định trong hợp đồng."}'::jsonb),
 ('b2-u04-l3-p6','b2-u04-l3','multiple_choice',6,'practice','medium',false,'{"question":"Từ nào mô tả ''khi một bên không thực hiện điều khoản hợp đồng''?","options":[{"id":"a","text":"concession"},{"id":"b","text":"breach of contract"},{"id":"c","text":"mutual agreement"}],"correctOptionId":"b","explanationVi":"breach of contract = vi phạm hợp đồng."}'::jsonb),
 ('b2-u04-l3-p7','b2-u04-l3','vocabulary_match',7,'practice','easy',false,'{"question":"Nối từ còn lại:","pairs":[{"left":"concession","right":"sự nhượng bộ"},{"left":"contingent on","right":"phụ thuộc vào"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l3-q1','b2-u04-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"negotiate","right":"đàm phán"},{"left":"obligation","right":"nghĩa vụ"},{"left":"clause","right":"điều khoản"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l3-q2','b2-u04-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''sự nhượng bộ''?","options":[{"id":"a","text":"stipulate"},{"id":"b","text":"concession"},{"id":"c","text":"comply"}],"correctOptionId":"b","explanationVi":"concession = nhượng bộ."}'::jsonb),
 ('b2-u04-l3-q3','b2-u04-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Điền đúng: ''The merger is ___ regulatory approval.''","options":[{"id":"a","text":"contingent on"},{"id":"b","text":"stipulating"},{"id":"c","text":"breaching"}],"correctOptionId":"a","explanationVi":"contingent on = phụ thuộc vào."}'::jsonb),
 ('b2-u04-l3-q4','b2-u04-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng: ''Both sides agreed to ___ so that the deal could proceed.''","acceptedAnswers":["compromise","negotiate"],"explanationVi":"compromise / negotiate = nhượng bộ / đàm phán."}'::jsonb),
 ('b2-u04-l3-q5','b2-u04-l3','multiple_choice',12,'quiz','medium',true,'{"question":"Điền từ đúng: ''The contract ___ that payment must be made within 30 days.''","options":[{"id":"a","text":"stipulates"},{"id":"b","text":"breaches"},{"id":"c","text":"complies"}],"correctOptionId":"a","explanationVi":"stipulate = quy định trong văn bản."}'::jsonb),
 ('b2-u04-l3-q6','b2-u04-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["with","All","comply","must","health","regulations","staff","safety","and"],"correctOrder":[1,5,2,3,4,7,8,6,0],"explanationVi":"All staff must comply with health and safety regulations."}'::jsonb),
 ('b2-u04-l3-q7','b2-u04-l3','vocabulary_match',14,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"mutual","right":"lẫn nhau, tương hỗ"},{"left":"breach","right":"vi phạm"},{"left":"obligation","right":"nghĩa vụ"}],"explanationVi":"Ghép đúng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u04-l4','B2','reading','b2-u04','normal',4,'A Fair Deal','Đọc hiểu: Thương lượng hợp đồng',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc cuộc thương lượng hợp đồng và chú ý cách dùng các liên từ điều kiện.",
    "objectives":["Đọc hiểu văn bản B2 về đàm phán","Nhận biết unless/provided/as long as trong ngữ cảnh","Trả lời câu hỏi suy luận"],
    "vocabBlock":[
      {"word":"terms","ipa":"/tɜːmz/","meaningVi":"điều kiện, điều khoản","example":"The terms of the contract were acceptable."},
      {"word":"deal-breaker","ipa":"/ˈdiːl breɪkər/","meaningVi":"điều khoản không thể chấp nhận","example":"The low salary was a deal-breaker for her."},
      {"word":"walk away","ipa":"/wɔːk əˈweɪ/","meaningVi":"bỏ đi, rút lui","example":"They walked away from the deal."},
      {"word":"binding","ipa":"/ˈbaɪndɪŋ/","meaningVi":"có tính ràng buộc","example":"A signed contract is legally binding."}],
    "examples":[
      {"en":"''The salary is acceptable as long as there is a performance bonus,'' said Ana. ''We can offer a bonus,'' replied the director, ''provided that you meet your quarterly targets. However, we cannot proceed unless you sign the non-disclosure agreement first.'' Ana reviewed the terms carefully. The non-disclosure clause was standard — not a deal-breaker. ''I''ll sign,'' she agreed, ''on condition that you increase the holiday allowance to twenty-five days.'' The director paused. ''We can do twenty-three days. In order to finalise the contract today, both parties should be willing to compromise.'' Ana nodded. They shook hands. The agreement was binding from that moment.","vi":"''Mức lương chấp nhận được miễn là có thưởng hiệu suất,'' Ana nói. ''Chúng tôi có thể cung cấp tiền thưởng,'' giám đốc trả lời, ''với điều kiện là bạn đạt chỉ tiêu hàng quý. Tuy nhiên, chúng tôi không thể tiến hành trừ phi bạn ký thỏa thuận bảo mật trước.'' Ana xem xét các điều khoản cẩn thận. Điều khoản bảo mật là tiêu chuẩn — không phải điều không thể chấp nhận. ''Tôi sẽ ký,'' cô đồng ý, ''với điều kiện bạn tăng phép năm lên hai mươi lăm ngày.'' Giám đốc dừng lại. ''Chúng tôi có thể làm hai mươi ba ngày. Để hoàn tất hợp đồng hôm nay, cả hai bên nên sẵn sàng nhượng bộ.'' Ana gật đầu. Họ bắt tay. Thỏa thuận có giá trị ràng buộc từ thời điểm đó."}],
    "commonMistakes":["Đọc kỹ: as long as = điều kiện duy trì; provided that = điều kiện bắt buộc một lần; unless = nếu không."],
    "tips":["Để tìm điều kiện trong văn bản → tìm unless, as long as, provided, on condition that.","deal-breaker = điều không thể thương lượng."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u04-l4-p1','b2-u04-l4','multiple_choice',1,'practice','easy',false,'{"question":"Ana chấp nhận mức lương với điều kiện gì?","options":[{"id":"a","text":"Ký thỏa thuận bảo mật"},{"id":"b","text":"Có thưởng hiệu suất"},{"id":"c","text":"Phép năm 25 ngày"}],"correctOptionId":"b","explanationVi":"''acceptable as long as there is a performance bonus.''"}'::jsonb),
 ('b2-u04-l4-p2','b2-u04-l4','multiple_choice',2,'practice','easy',false,'{"question":"Điều khoản bảo mật (NDA) có phải là deal-breaker với Ana không?","options":[{"id":"a","text":"Có"},{"id":"b","text":"Không, nó là tiêu chuẩn"},{"id":"c","text":"Cô chưa đọc"}],"correctOptionId":"b","explanationVi":"''The non-disclosure clause was standard — not a deal-breaker.''"}'::jsonb),
 ('b2-u04-l4-p3','b2-u04-l4','multiple_choice',3,'practice','medium',false,'{"question":"Công ty không thể tiến hành trừ phi điều gì?","options":[{"id":"a","text":"Ana đồng ý giảm lương"},{"id":"b","text":"Ana ký thỏa thuận bảo mật"},{"id":"c","text":"Ana từ bỏ yêu cầu phép"}],"correctOptionId":"b","explanationVi":"''we cannot proceed unless you sign the non-disclosure agreement first.''"}'::jsonb),
 ('b2-u04-l4-p4','b2-u04-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"terms","right":"điều kiện, điều khoản"},{"left":"deal-breaker","right":"điều khoản không thể chấp nhận"},{"left":"walk away","right":"bỏ đi, rút lui"},{"left":"binding","right":"có tính ràng buộc"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l4-p5','b2-u04-l4','multiple_choice',5,'practice','medium',false,'{"question":"Liên từ nào trong bài mang nghĩa ''với điều kiện duy trì''?","options":[{"id":"a","text":"unless"},{"id":"b","text":"as long as"},{"id":"c","text":"on condition that"}],"correctOptionId":"b","explanationVi":"as long as = miễn là (điều kiện cần duy trì)."}'::jsonb),
 ('b2-u04-l4-p6','b2-u04-l4','multiple_choice',6,'practice','medium',false,'{"question":"Cuộc đàm phán kết thúc như thế nào?","options":[{"id":"a","text":"Ana bỏ đi không ký"},{"id":"b","text":"Họ nhượng bộ và ký hợp đồng"},{"id":"c","text":"Công ty rút lui"}],"correctOptionId":"b","explanationVi":"''They shook hands. The agreement was binding.''"}'::jsonb),
 ('b2-u04-l4-p7','b2-u04-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành câu của giám đốc: ''We cannot proceed ___ you sign the NDA.''","acceptedAnswers":["unless"],"explanationVi":"unless = if not."}'::jsonb),
 ('b2-u04-l4-q1','b2-u04-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Ana yêu cầu bao nhiêu ngày phép?","options":[{"id":"a","text":"20 ngày"},{"id":"b","text":"23 ngày"},{"id":"c","text":"25 ngày"}],"correctOptionId":"c","explanationVi":"''on condition that you increase the holiday allowance to twenty-five days.''"}'::jsonb),
 ('b2-u04-l4-q2','b2-u04-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Công ty đề xuất bao nhiêu ngày phép cuối cùng?","options":[{"id":"a","text":"25 ngày"},{"id":"b","text":"23 ngày"},{"id":"c","text":"20 ngày"}],"correctOptionId":"b","explanationVi":"''We can do twenty-three days.''"}'::jsonb),
 ('b2-u04-l4-q3','b2-u04-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Liên từ điều kiện nào được dùng để chỉ điều kiện một lần, bắt buộc?","options":[{"id":"a","text":"as long as"},{"id":"b","text":"provided that"},{"id":"c","text":"in case"}],"correctOptionId":"b","explanationVi":"provided that = only if (điều kiện bắt buộc một lần)."}'::jsonb),
 ('b2-u04-l4-q4','b2-u04-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''A signed contract is legally ___.''","acceptedAnswers":["binding"],"explanationVi":"binding = có tính ràng buộc pháp lý."}'::jsonb),
 ('b2-u04-l4-q5','b2-u04-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Từ ''terms'' trong bài có nghĩa là?","options":[{"id":"a","text":"Thời hạn học"},{"id":"b","text":"Điều kiện, điều khoản"},{"id":"c","text":"Vấn đề"}],"correctOptionId":"b","explanationVi":"terms = điều kiện/điều khoản (của hợp đồng)."}'::jsonb),
 ('b2-u04-l4-q6','b2-u04-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"deal-breaker","right":"điều không thể chấp nhận"},{"left":"binding","right":"có tính ràng buộc"},{"left":"walk away","right":"rút lui"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l4-q7','b2-u04-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền đúng: ''In order ___ finalise the contract, both parties must compromise.''","acceptedAnswers":["to"],"explanationVi":"in order to + infinitive."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u04-l5','B2','reading','b2-u04','unit_review',5,'Unit 4 Review','Ôn tập Unit 4: Với điều kiện là...',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 4: liên từ điều kiện, diễn đạt mục đích và từ vựng đàm phán.","objectives":["Tổng hợp can-do Unit 4","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u04-l5-q1','b2-u04-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Điền đúng: ''You won''t get the job ___ you impress the panel.''","acceptedAnswers":["unless"],"explanationVi":"unless = if not."}'::jsonb),
 ('b2-u04-l5-q2','b2-u04-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu diễn đạt mục đích ĐÚNG (cùng chủ ngữ):","options":[{"id":"a","text":"He left early so that catch the train."},{"id":"b","text":"He left early so as to catch the train."},{"id":"c","text":"He left early for catching the train."}],"correctOptionId":"b","explanationVi":"so as to + infinitive = mục đích cùng chủ ngữ."}'::jsonb),
 ('b2-u04-l5-q3','b2-u04-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''vi phạm hợp đồng''?","options":[{"id":"a","text":"concession"},{"id":"b","text":"breach of contract"},{"id":"c","text":"mutual agreement"}],"correctOptionId":"b","explanationVi":"breach of contract = vi phạm."}'::jsonb),
 ('b2-u04-l5-q4','b2-u04-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Điền đúng: ''She reduced her speed ___ not to cause an accident.''","acceptedAnswers":["so as","in order"],"explanationVi":"so as not to / in order not to = mục đích phủ định."}'::jsonb),
 ('b2-u04-l5-q5','b2-u04-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào SAIУ (lỗi unless)?","options":[{"id":"a","text":"Unless you hurry, you''ll miss the bus."},{"id":"b","text":"Unless you don''t hurry, you''ll miss the bus."},{"id":"c","text":"Unless she calls, I won''t go."}],"correctOptionId":"b","explanationVi":"unless đã có nghĩa phủ định → không thêm don''t."}'::jsonb),
 ('b2-u04-l5-q6','b2-u04-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"stipulate","right":"quy định"},{"left":"comply with","right":"tuân thủ"},{"left":"contingent on","right":"phụ thuộc vào"},{"left":"obligation","right":"nghĩa vụ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u04-l5-q7','b2-u04-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Điền đúng (khác chủ ngữ): ''The teacher wrote it on the board ___ all students could see.''","acceptedAnswers":["so that"],"explanationVi":"Khác chủ ngữ → so that."}'::jsonb),
 ('b2-u04-l5-q8','b2-u04-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["as","long","stay","you","can","quiet","as","You"],"correctOrder":[7,4,0,1,2,3,5,6],"explanationVi":"You can stay as long as you are quiet."}'::jsonb),
 ('b2-u04-l5-q9','b2-u04-l5','multiple_choice',9,'quiz','medium',true,'{"question":"Liên từ nào phù hợp nhất (trang trọng, nhấn điều kiện):","options":[{"id":"a","text":"if"},{"id":"b","text":"on condition that"},{"id":"c","text":"supposing"}],"correctOptionId":"b","explanationVi":"on condition that = trang trọng, nhấn điều kiện bắt buộc."}'::jsonb),
 ('b2-u04-l5-q10','b2-u04-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Điền đúng (cho the purpose of): ''The survey was conducted ___ measuring customer satisfaction.''","acceptedAnswers":["for the purpose of"],"explanationVi":"for the purpose of + V-ing."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u04-l5' WHERE id = 'b2-u04';

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 05 — It Is Said That...
-- Passive + Modals; Passive Reporting Structures; Need + Passive
-- ══════════════════════════════════════════════════════════════════════════

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u05-l1','B2','reading','b2-u05','normal',1,'Passive with Modal Verbs','Modal + be + V3 và tất cả các thì bị động',12,25,70,'{}'::jsonb,
  '{"warmup":"''Luật này phải được thực thi.'' / ''Báo cáo có thể đã được gửi.'' — bạn tạo các câu bị động này như thế nào?",
    "objectives":["Tạo câu bị động với modal verbs (must, should, can, might, will...)","Dùng đúng modal + be + V3 (hiện tại) và modal + have been + V3 (quá khứ)","Nhận biết khi nào dùng bị động với modal"],
    "grammarHtml":"<b>Bị động với modal verbs:</b><br><b>Hiện tại/tương lai:</b> modal + be + V3<br><i>must be checked, should be done, can be solved, will be announced</i><br><b>Quá khứ:</b> modal + have been + V3<br><i>must have been stolen, should have been fixed, might have been delayed</i><br><b>Công thức đầy đủ:</b><br>Active: They must test the system. → Passive: The system must be tested.<br>Active: Someone might have taken it. → Passive: It might have been taken.<br><b>Bị động liên tục với modal:</b> modal + be being + V3 (ít gặp)<br><i>The road is being repaired → The road must be being repaired right now.</i><br><b>Các modal thường gặp:</b> must, should, ought to, can, could, may, might, will, would, need to, have to.",
    "vocabBlock":[
      {"word":"be enforced","ipa":"/biː ɪnˈfɔːst/","meaningVi":"được thực thi","example":"The law must be enforced strictly."},
      {"word":"be submitted","ipa":"/biː səbˈmɪtɪd/","meaningVi":"được nộp","example":"All reports must be submitted by Friday."},
      {"word":"be investigated","ipa":"/biː ɪnˈvestɪɡeɪtɪd/","meaningVi":"được điều tra","example":"The matter should be investigated."},
      {"word":"be delayed","ipa":"/biː dɪˈleɪd/","meaningVi":"bị trì hoãn","example":"The flight might be delayed."},
      {"word":"be resolved","ipa":"/biː rɪˈzɒlvd/","meaningVi":"được giải quyết","example":"This issue needs to be resolved."}],
    "examples":[
      {"en":"The results should be announced tomorrow.","vi":"Kết quả nên được thông báo vào ngày mai."},
      {"en":"The documents must have been lost in transit.","vi":"Các tài liệu chắc hẳn đã bị thất lạc trong quá trình vận chuyển."},
      {"en":"This problem can be solved with the right approach.","vi":"Vấn đề này có thể được giải quyết bằng cách tiếp cận đúng."},
      {"en":"Safety regulations must be followed at all times.","vi":"Các quy định an toàn phải được tuân thủ mọi lúc."}],
    "commonMistakes":["❌ must been done → ✅ must be done","❌ should been finished → ✅ should have been finished (quá khứ)","❌ might be being repaired (chỉ dùng trong ngữ cảnh rất đặc biệt)"],
    "tips":["Hiện tại: modal + be + V3.","Quá khứ: modal + have been + V3.","Khi chuyển: active ''they'' / ''someone'' thường bị bỏ trong bị động."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u05-l1-p1','b2-u05-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chuyển sang bị động: ''They must check the system.'' →","options":[{"id":"a","text":"The system must checked."},{"id":"b","text":"The system must be checked."},{"id":"c","text":"The system must have been checked."}],"correctOptionId":"b","explanationVi":"Hiện tại: must + be + V3 → must be checked."}'::jsonb),
 ('b2-u05-l1-p2','b2-u05-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chuyển sang bị động: ''Someone might have taken my wallet.''","acceptedAnswers":["My wallet might have been taken."],"explanationVi":"Quá khứ bị động: might + have been + V3."}'::jsonb),
 ('b2-u05-l1-p3','b2-u05-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối cụm bị động với nghĩa:","pairs":[{"left":"be enforced","right":"được thực thi"},{"left":"be submitted","right":"được nộp"},{"left":"be delayed","right":"bị trì hoãn"},{"left":"be resolved","right":"được giải quyết"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l1-p4','b2-u05-l1','grammar_fill_blank',4,'practice','medium',false,'{"question":"Chia động từ: ''The report should ___ (submit) by Monday.''","acceptedAnswers":["be submitted"],"explanationVi":"Hiện tại bị động với modal: should be submitted."}'::jsonb),
 ('b2-u05-l1-p5','b2-u05-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Vấn đề an toàn này cần được điều tra ngay lập tức.","acceptedAnswers":["This safety issue needs to be investigated immediately.","The safety issue should be investigated immediately.","This safety problem must be investigated immediately."],"explanationVi":"need to be investigated / should be investigated."}'::jsonb),
 ('b2-u05-l1-p6','b2-u05-l1','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''The documents must been delivered by courier.''","acceptedAnswers":["The documents must be delivered by courier."],"explanationVi":"Hiện tại bị động: must be delivered (không phải must been)."}'::jsonb),
 ('b2-u05-l1-p7','b2-u05-l1','multiple_choice',7,'practice','medium',false,'{"question":"Chuyển sang bị động quá khứ: ''They should have fixed the problem.'' →","options":[{"id":"a","text":"The problem should be fixed."},{"id":"b","text":"The problem should have been fixed."},{"id":"c","text":"The problem should have fixed."}],"correctOptionId":"b","explanationVi":"Quá khứ bị động: should have been fixed."}'::jsonb),
 ('b2-u05-l1-q1','b2-u05-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Công thức bị động HIỆN TẠI với modal:","options":[{"id":"a","text":"modal + have been + V3"},{"id":"b","text":"modal + be + V3"},{"id":"c","text":"modal + been + V3"}],"correctOptionId":"b","explanationVi":"Hiện tại: modal + be + V3."}'::jsonb),
 ('b2-u05-l1-q2','b2-u05-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chia động từ: ''Safety regulations must ___ (follow) at all times.''","acceptedAnswers":["be followed"],"explanationVi":"must be followed = bị động hiện tại."}'::jsonb),
 ('b2-u05-l1-q3','b2-u05-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Chuyển sang bị động: ''Hackers might have stolen the data.'' →","options":[{"id":"a","text":"The data might be stolen."},{"id":"b","text":"The data might have been stolen."},{"id":"c","text":"The data might have stolen."}],"correctOptionId":"b","explanationVi":"Quá khứ bị động: might have been stolen."}'::jsonb),
 ('b2-u05-l1-q4','b2-u05-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chia động từ: ''This mistake could ___ (avoid) with better planning.''","acceptedAnswers":["have been avoided"],"explanationVi":"Quá khứ bị động: could have been avoided."}'::jsonb),
 ('b2-u05-l1-q5','b2-u05-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối cụm bị động với nghĩa:","pairs":[{"left":"be investigated","right":"được điều tra"},{"left":"be enforced","right":"được thực thi"},{"left":"be resolved","right":"được giải quyết"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l1-q6','b2-u05-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["announced","be","will","results","The","tomorrow"],"correctOrder":[4,0,2,1,3,5],"explanationVi":"The results will be announced tomorrow."}'::jsonb),
 ('b2-u05-l1-q7','b2-u05-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''The package should ___ (deliver) last week but it hasn''t arrived.''","acceptedAnswers":["have been delivered"],"explanationVi":"Kỳ vọng trong quá khứ nhưng không xảy ra: should have been delivered."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u05-l2','B2','reading','b2-u05','normal',2,'Passive Reporting Structures','It is said / reported / believed + that — He is thought to have...',12,25,70,'{}'::jsonb,
  '{"warmup":"Báo chí thường viết ''Được cho là...'' / ''Được báo cáo là...'' thay vì nói thẳng. Bạn có biết cấu trúc này trong tiếng Anh không?",
    "objectives":["Dùng It is said/reported/believed/thought/known/claimed + that","Dùng Subject + is said/believed/thought to (have) + infinitive","Chuyển đổi giữa hai cấu trúc"],
    "grammarHtml":"<b>Passive Reporting Structures:</b><br><b>Dạng 1 — It + passive + that:</b><br>It is said that he lives in Paris. (người ta nói rằng...)<br>It is believed that the fire started at midnight.<br>It is reported that hundreds are missing.<br><b>Động từ reporting:</b> say, report, believe, think, know, claim, consider, allege, understand<br><b>Dạng 2 — Subject + passive + to-infinitive:</b><br>Cùng thời với mệnh đề chính: He is said to live in Paris.<br>Trước thời điểm mệnh đề chính: He is said to have lived in Paris. (dùng perfect infinitive)<br><b>Chuyển đổi:</b><br>It is believed that she wrote the book. → She is believed to have written the book.<br>It is reported that they are hiding. → They are reported to be hiding.<br><b>Thì quá khứ:</b> It was said / They were reported to...",
    "vocabBlock":[
      {"word":"be alleged","ipa":"/biː əˈledʒd/","meaningVi":"bị cáo buộc","example":"He is alleged to have stolen the money."},
      {"word":"be considered","ipa":"/biː kənˈsɪdəd/","meaningVi":"được coi là","example":"She is considered to be an expert."},
      {"word":"be understood","ipa":"/biː ˌʌndəˈstʊd/","meaningVi":"được hiểu là","example":"It is understood that talks will resume."},
      {"word":"be claimed","ipa":"/biː kleɪmd/","meaningVi":"được cho là, tuyên bố","example":"It is claimed that the drug is safe."}],
    "examples":[
      {"en":"It is said that the ancient temple is over 2,000 years old.","vi":"Người ta nói rằng ngôi đền cổ đại đã hơn 2.000 năm tuổi."},
      {"en":"The suspect is believed to have left the country.","vi":"Nghi phạm được cho là đã rời khỏi đất nước."},
      {"en":"It was reported that the earthquake measured 6.5 on the Richter scale.","vi":"Được báo cáo rằng trận động đất đo 6.5 độ Richter."},
      {"en":"The CEO is said to be considering resignation.","vi":"CEO được cho là đang cân nhắc từ chức."}],
    "commonMistakes":["❌ She is said that she lives in Paris → ✅ She is said to live in Paris (dạng 2 dùng to-infinitive)","Hành động trước → perfect infinitive: is said to HAVE done.","❌ It is said that he has stolen it. → It is said that he stole it. hoặc He is said to have stolen it."],
    "tips":["Dạng 1 (It is...) = trọng tâm thông tin.","Dạng 2 (Subject is...) = trọng tâm đối tượng.","Perfect infinitive (to have done) = hành động đã xảy ra trước thời điểm nói."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u05-l2-p1','b2-u05-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG (dạng 2 — Subject + passive):","options":[{"id":"a","text":"He is said that lives in London."},{"id":"b","text":"He is said to live in London."},{"id":"c","text":"He is said living in London."}],"correctOptionId":"b","explanationVi":"Dạng 2: Subject + is said + to-infinitive."}'::jsonb),
 ('b2-u05-l2-p2','b2-u05-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chuyển sang dạng 2: ''It is believed that she has written the report.'' →","acceptedAnswers":["She is believed to have written the report."],"explanationVi":"Hành động đã xảy ra trước → is believed to have written."}'::jsonb),
 ('b2-u05-l2-p3','b2-u05-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối cụm bị động báo cáo với nghĩa:","pairs":[{"left":"be alleged","right":"bị cáo buộc"},{"left":"be considered","right":"được coi là"},{"left":"be understood","right":"được hiểu là"},{"left":"be claimed","right":"được tuyên bố là"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l2-p4','b2-u05-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Chuyển sang dạng 1: ''Scientists believe that the comet is approaching Earth.'' →","acceptedAnswers":["It is believed that the comet is approaching Earth."],"explanationVi":"It is believed that + clause."}'::jsonb),
 ('b2-u05-l2-p5','b2-u05-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Nghi phạm được cho là đã rời khỏi đất nước vào đêm qua.","acceptedAnswers":["The suspect is said to have left the country last night.","The suspect is believed to have left the country last night."],"explanationVi":"is said/believed to have left (perfect infinitive = hành động đã xảy ra)."}'::jsonb),
 ('b2-u05-l2-p6','b2-u05-l2','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''The CEO is said that she is considering resignation.''","acceptedAnswers":["The CEO is said to be considering resignation."],"explanationVi":"Dạng 2: is said to be (+ V-ing cho ongoing action)."}'::jsonb),
 ('b2-u05-l2-p7','b2-u05-l2','multiple_choice',7,'practice','medium',false,'{"question":"Khi nào dùng perfect infinitive (to have done) trong dạng 2?","options":[{"id":"a","text":"Khi hành động xảy ra sau thời điểm nói"},{"id":"b","text":"Khi hành động đã xảy ra trước thời điểm nói"},{"id":"c","text":"Luôn luôn"}],"correctOptionId":"b","explanationVi":"Perfect infinitive = hành động đã xảy ra trước thời điểm mệnh đề chính."}'::jsonb),
 ('b2-u05-l2-q1','b2-u05-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (hành động đã xảy ra):","options":[{"id":"a","text":"She is believed to steal the jewels."},{"id":"b","text":"She is believed to have stolen the jewels."},{"id":"c","text":"She is believed stealing the jewels."}],"correctOptionId":"b","explanationVi":"Hành động đã xảy ra → is believed to HAVE stolen."}'::jsonb),
 ('b2-u05-l2-q2','b2-u05-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền dạng 1: ''___ reported that several buildings collapsed.''","acceptedAnswers":["It is","It was"],"explanationVi":"It is/was reported that..."}'::jsonb),
 ('b2-u05-l2-q3','b2-u05-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Chuyển đổi: ''It is said that he escaped from prison.'' →","options":[{"id":"a","text":"He is said to escape from prison."},{"id":"b","text":"He is said to have escaped from prison."},{"id":"c","text":"He is said that escaped from prison."}],"correctOptionId":"b","explanationVi":"Đã xảy ra trước → to have escaped."}'::jsonb),
 ('b2-u05-l2-q4','b2-u05-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chuyển sang dạng 2: ''It is claimed that the drug has no side effects.'' →","acceptedAnswers":["The drug is claimed to have no side effects.","The drug is claimed not to have side effects."],"explanationVi":"is claimed to have no side effects."}'::jsonb),
 ('b2-u05-l2-q5','b2-u05-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối động từ reporting với nghĩa:","pairs":[{"left":"be alleged","right":"bị cáo buộc"},{"left":"be considered","right":"được coi là"},{"left":"be claimed","right":"được tuyên bố là"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l2-q6','b2-u05-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["the","is","to","have","escaped","suspect","believed","country","the"],"correctOrder":[5,1,2,3,4,6,7,8,0],"explanationVi":"The suspect is believed to have escaped the country."}'::jsonb),
 ('b2-u05-l2-q7','b2-u05-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chuyển sang dạng 1: ''Experts think that the situation is improving.'' →","acceptedAnswers":["It is thought that the situation is improving."],"explanationVi":"It is thought that + clause."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u05-l3','B2','reading','b2-u05','normal',3,'News & Media Vocabulary','Từ vựng báo chí & truyền thông B2',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn thường đọc tin tức bằng tiếng Anh không? Bạn biết những từ nào liên quan đến báo chí?",
    "objectives":["Học 10 từ vựng B2 về báo chí và truyền thông","Dùng từ trong ngữ cảnh bị động báo cáo","Phân biệt sắc thái từ về nguồn tin và độ chắc chắn"],
    "vocabBlock":[
      {"word":"allege","ipa":"/əˈledʒ/","meaningVi":"cáo buộc, cho là","example":"The newspaper alleged fraud."},
      {"word":"authority","ipa":"/ɔːˈθɒrəti/","meaningVi":"cơ quan thẩm quyền","example":"Authorities are investigating the incident."},
      {"word":"eyewitness","ipa":"/ˈaɪwɪtnəs/","meaningVi":"nhân chứng mắt thấy","example":"An eyewitness said the suspect fled."},
      {"word":"speculation","ipa":"/ˌspekjuˈleɪʃn/","meaningVi":"sự suy đoán, đồn đoán","example":"There is speculation about the resignation."},
      {"word":"statement","ipa":"/ˈsteɪtmənt/","meaningVi":"tuyên bố, phát biểu","example":"The minister issued a statement."},
      {"word":"denial","ipa":"/dɪˈnaɪəl/","meaningVi":"sự phủ nhận","example":"The company issued a denial."},
      {"word":"source","ipa":"/sɔːs/","meaningVi":"nguồn tin","example":"According to our sources, the deal is off."},
      {"word":"coverage","ipa":"/ˈkʌvərɪdʒ/","meaningVi":"sự đưa tin, phạm vi đưa tin","example":"The event received wide coverage."},
      {"word":"breaking news","ipa":"/ˈbreɪkɪŋ njuːz/","meaningVi":"tin tức nóng hổi","example":"Breaking news: a major earthquake has struck."},
      {"word":"reliable","ipa":"/rɪˈlaɪəbl/","meaningVi":"đáng tin cậy","example":"We need a reliable source."}],
    "examples":[
      {"en":"It is alleged that the minister accepted bribes.","vi":"Bị cáo buộc rằng vị bộ trưởng đã nhận hối lộ."},
      {"en":"According to reliable sources, a deal is believed to have been reached.","vi":"Theo các nguồn tin đáng tin cậy, một thỏa thuận được cho là đã đạt được."},
      {"en":"The statement was issued in response to widespread speculation.","vi":"Tuyên bố được đưa ra để đáp lại những đồn đoán lan rộng."}],
    "commonMistakes":["allege (dùng trong báo chí/pháp lý) ≠ say (thông thường): allege nhấn nguồn chưa xác nhận.","coverage (uncountable): wide/extensive/media coverage.","denial ≠ refusal: denial = phủ nhận sự việc; refusal = từ chối làm gì."],
    "tips":["according to sources / it is reported/alleged = báo chí giữ trung lập, chưa xác nhận.","reliable, credible, anonymous sources = mô tả chất lượng nguồn tin."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u05-l3-p1','b2-u05-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"allege","right":"cáo buộc"},{"left":"eyewitness","right":"nhân chứng mắt thấy"},{"left":"source","right":"nguồn tin"},{"left":"coverage","right":"sự đưa tin"}],"explanationVi":"Từ vựng báo chí."}'::jsonb),
 ('b2-u05-l3-p2','b2-u05-l3','vocabulary_match',2,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"statement","right":"tuyên bố"},{"left":"denial","right":"sự phủ nhận"},{"left":"speculation","right":"đồn đoán"},{"left":"reliable","right":"đáng tin cậy"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l3-p3','b2-u05-l3','multiple_choice',3,'practice','easy',false,'{"question":"Điền từ đúng: ''___ news: the prime minister has announced an early election.''","options":[{"id":"a","text":"Breaking"},{"id":"b","text":"Wide"},{"id":"c","text":"Reliable"}],"correctOptionId":"a","explanationVi":"Breaking news = tin tức nóng hổi."}'::jsonb),
 ('b2-u05-l3-p4','b2-u05-l3','multiple_choice',4,'practice','medium',false,'{"question":"Từ nào khác biệt về nghĩa: ''The company issued a ___ saying the reports were false.''","options":[{"id":"a","text":"denial"},{"id":"b","text":"statement"},{"id":"c","text":"source"}],"correctOptionId":"b","explanationVi":"issue a statement = đưa ra tuyên bố (phát biểu chính thức)."}'::jsonb),
 ('b2-u05-l3-p5','b2-u05-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Bị cáo buộc rằng vị giám đốc đã thao túng dữ liệu tài chính.","acceptedAnswers":["It is alleged that the director manipulated financial data.","The director is alleged to have manipulated financial data."],"explanationVi":"It is alleged that / is alleged to have done."}'::jsonb),
 ('b2-u05-l3-p6','b2-u05-l3','multiple_choice',6,'practice','medium',false,'{"question":"Điền từ đúng: ''There is a lot of ___ about who will be the next leader.''","options":[{"id":"a","text":"speculation"},{"id":"b","text":"denial"},{"id":"c","text":"coverage"}],"correctOptionId":"a","explanationVi":"speculation = đồn đoán."}'::jsonb),
 ('b2-u05-l3-p7','b2-u05-l3','vocabulary_match',7,'practice','easy',false,'{"question":"Nối từ còn lại:","pairs":[{"left":"authority","right":"cơ quan thẩm quyền"},{"left":"breaking news","right":"tin tức nóng hổi"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l3-q1','b2-u05-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"allege","right":"cáo buộc"},{"left":"reliable","right":"đáng tin cậy"},{"left":"source","right":"nguồn tin"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l3-q2','b2-u05-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Từ nào mô tả khi một công ty phủ nhận cáo buộc?","options":[{"id":"a","text":"statement"},{"id":"b","text":"denial"},{"id":"c","text":"coverage"}],"correctOptionId":"b","explanationVi":"denial = sự phủ nhận."}'::jsonb),
 ('b2-u05-l3-q3','b2-u05-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Điền từ đúng: ''An ___ reported seeing the suspect near the scene.''","options":[{"id":"a","text":"authority"},{"id":"b","text":"eyewitness"},{"id":"c","text":"allege"}],"correctOptionId":"b","explanationVi":"eyewitness = nhân chứng mắt thấy."}'::jsonb),
 ('b2-u05-l3-q4','b2-u05-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền từ đúng: ''The scandal received ___ media ___ around the world.''","acceptedAnswers":["wide coverage","extensive coverage","widespread coverage"],"explanationVi":"wide/extensive coverage = đưa tin rộng rãi."}'::jsonb),
 ('b2-u05-l3-q5','b2-u05-l3','multiple_choice',12,'quiz','medium',true,'{"question":"Sắc thái nào phù hợp khi nguồn tin chưa xác nhận?","options":[{"id":"a","text":"It is confirmed that"},{"id":"b","text":"It is alleged / reported that"},{"id":"c","text":"It is obvious that"}],"correctOptionId":"b","explanationVi":"alleged/reported = chưa chính thức xác nhận."}'::jsonb),
 ('b2-u05-l3-q6','b2-u05-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["sources","reliable","deal","a","to","According","been","is","have","reached","believed"],"correctOrder":[5,0,1,8,3,7,2,9,6,10,4],"explanationVi":"According to reliable sources, a deal is believed to have been reached."}'::jsonb),
 ('b2-u05-l3-q7','b2-u05-l3','vocabulary_match',14,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"speculation","right":"đồn đoán"},{"left":"authority","right":"cơ quan thẩm quyền"},{"left":"statement","right":"tuyên bố"}],"explanationVi":"Ghép đúng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u05-l4','B2','reading','b2-u05','normal',4,'The Investigation','Đọc hiểu: Phóng sự điều tra',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc một phóng sự báo chí về vụ điều tra — chú ý cách dùng bị động báo cáo và need + passive.",
    "objectives":["Đọc hiểu văn bản báo chí B2","Nhận biết passive reporting structures, passive+modal, need+passive trong ngữ cảnh","Suy luận thái độ của tác giả"],
    "vocabBlock":[
      {"word":"inquiry","ipa":"/ɪnˈkwaɪəri/","meaningVi":"cuộc điều tra","example":"A formal inquiry has been launched."},
      {"word":"misconduct","ipa":"/ˌmɪsˈkɒndʌkt/","meaningVi":"hành vi sai trái","example":"The officer was charged with misconduct."},
      {"word":"transparent","ipa":"/trænsˈpærənt/","meaningVi":"minh bạch","example":"The process must be transparent."},
      {"word":"accountability","ipa":"/əˌkaʊntəˈbɪlɪti/","meaningVi":"trách nhiệm giải trình","example":"There needs to be greater accountability."}],
    "examples":[
      {"en":"THREE senior officials are alleged to have misused public funds, according to a report published yesterday. It is believed that the funds were transferred to private accounts over a period of two years. The matter is being investigated by a special committee and a formal inquiry is expected to be launched next week. An eyewitness is reported to have provided evidence to the authorities. ''Questions need to be asked and answers need to be given,'' said a spokesperson. ''The process must be transparent, and those responsible must be held accountable.'' It is understood that several arrests could be made in the coming days. The authorities have issued a statement, but no further details have been released.","vi":"Ba quan chức cấp cao bị cáo buộc đã lạm dụng công quỹ, theo một báo cáo được công bố hôm qua. Được cho là số tiền đã được chuyển vào tài khoản cá nhân trong hai năm. Vấn đề này đang được một ủy ban đặc biệt điều tra và một cuộc điều tra chính thức dự kiến sẽ được khởi động vào tuần tới. Một nhân chứng được cho là đã cung cấp bằng chứng cho cơ quan chức năng. ''Những câu hỏi cần được đặt ra và câu trả lời cần được đưa ra,'' một người phát ngôn nói. ''Quá trình phải minh bạch, và những người có trách nhiệm phải bị quy trách nhiệm.'' Được hiểu rằng một số vụ bắt giữ có thể xảy ra trong những ngày tới. Chính quyền đã ra tuyên bố, nhưng không có thêm chi tiết nào được công bố."}],
    "commonMistakes":["need to be asked (bị động với need to) = questions need to be asked.","must be held accountable = phải chịu trách nhiệm."],
    "tips":["Báo chí thường dùng alleged, reported, believed để giữ trung lập.","need to be + V3 = cần được (làm gì đó) — bị động với need to."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u05-l4-p1','b2-u05-l4','multiple_choice',1,'practice','easy',false,'{"question":"Theo bài, các quan chức bị cáo buộc điều gì?","options":[{"id":"a","text":"Lạm dụng công quỹ"},{"id":"b","text":"Nhận hối lộ từ công ty"},{"id":"c","text":"Tiết lộ thông tin mật"}],"correctOptionId":"a","explanationVi":"''alleged to have misused public funds.''"}'::jsonb),
 ('b2-u05-l4-p2','b2-u05-l4','multiple_choice',2,'practice','easy',false,'{"question":"Ai cung cấp bằng chứng?","options":[{"id":"a","text":"Ủy ban đặc biệt"},{"id":"b","text":"Một nhân chứng"},{"id":"c","text":"Người phát ngôn"}],"correctOptionId":"b","explanationVi":"''An eyewitness is reported to have provided evidence.''"}'::jsonb),
 ('b2-u05-l4-p3','b2-u05-l4','multiple_choice',3,'practice','medium',false,'{"question":"Cấu trúc nào xuất hiện trong: ''Questions need to be asked''?","options":[{"id":"a","text":"Passive reporting"},{"id":"b","text":"Modal + be + V3"},{"id":"c","text":"Need + passive (need to be + V3)"}],"correctOptionId":"c","explanationVi":"need to be asked = need + passive."}'::jsonb),
 ('b2-u05-l4-p4','b2-u05-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"inquiry","right":"cuộc điều tra"},{"left":"misconduct","right":"hành vi sai trái"},{"left":"transparent","right":"minh bạch"},{"left":"accountability","right":"trách nhiệm giải trình"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l4-p5','b2-u05-l4','multiple_choice',5,'practice','medium',false,'{"question":"Câu ''It is understood that several arrests could be made'' thuộc cấu trúc gì?","options":[{"id":"a","text":"Active reporting"},{"id":"b","text":"Passive reporting (dạng 1)"},{"id":"c","text":"Modal + be + V3"}],"correctOptionId":"b","explanationVi":"It is understood that + clause = dạng 1 passive reporting."}'::jsonb),
 ('b2-u05-l4-p6','b2-u05-l4','multiple_choice',6,'practice','medium',false,'{"question":"Theo bài, điều gì dự kiến xảy ra vào tuần tới?","options":[{"id":"a","text":"Bắt giữ thủ phạm"},{"id":"b","text":"Khởi động cuộc điều tra chính thức"},{"id":"c","text":"Công bố báo cáo cuối cùng"}],"correctOptionId":"b","explanationVi":"''a formal inquiry is expected to be launched next week.''"}'::jsonb),
 ('b2-u05-l4-p7','b2-u05-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành theo bài: ''Those responsible must ___ (hold) accountable.''","acceptedAnswers":["be held"],"explanationVi":"must be held = bị động với modal."}'::jsonb),
 ('b2-u05-l4-q1','b2-u05-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Tiền bị chuyển vào đâu?","options":[{"id":"a","text":"Tài khoản nước ngoài"},{"id":"b","text":"Tài khoản cá nhân"},{"id":"c","text":"Quỹ từ thiện"}],"correctOptionId":"b","explanationVi":"''transferred to private accounts.''"}'::jsonb),
 ('b2-u05-l4-q2','b2-u05-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Người phát ngôn nhấn mạnh điều gì phải có?","options":[{"id":"a","text":"Bằng chứng trực tiếp"},{"id":"b","text":"Sự minh bạch và trách nhiệm giải trình"},{"id":"c","text":"Bồi thường cho nạn nhân"}],"correctOptionId":"b","explanationVi":"''The process must be transparent... those responsible must be held accountable.''"}'::jsonb),
 ('b2-u05-l4-q3','b2-u05-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Từ ''alleged'' trong bài có nghĩa:","options":[{"id":"a","text":"Đã được xác nhận"},{"id":"b","text":"Được cáo buộc (chưa xác nhận)"},{"id":"c","text":"Bị phủ nhận"}],"correctOptionId":"b","explanationVi":"alleged = bị cáo buộc nhưng chưa chứng minh."}'::jsonb),
 ('b2-u05-l4-q4','b2-u05-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''Several arrests ___ (could/make) in coming days.''","acceptedAnswers":["could be made"],"explanationVi":"Modal bị động: could be made."}'::jsonb),
 ('b2-u05-l4-q5','b2-u05-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Cấu trúc ''An eyewitness is reported to have provided evidence'' — loại nào?","options":[{"id":"a","text":"Dạng 1: It is reported that"},{"id":"b","text":"Dạng 2: Subject + is reported to have"},{"id":"c","text":"Need + passive"}],"correctOptionId":"b","explanationVi":"Subject + is reported to have + V3 = dạng 2 passive reporting."}'::jsonb),
 ('b2-u05-l4-q6','b2-u05-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"inquiry","right":"cuộc điều tra"},{"left":"accountability","right":"trách nhiệm giải trình"},{"left":"transparent","right":"minh bạch"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l4-q7','b2-u05-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Hoàn thành passive reporting: ''___ that the officials misused funds.'' (dạng 1)","acceptedAnswers":["It is alleged","It is believed","It is reported","It has been alleged","It has been reported"],"explanationVi":"It is alleged/believed/reported + that."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u05-l5','B2','reading','b2-u05','unit_review',5,'Unit 5 Review','Ôn tập Unit 5: Người ta nói rằng...',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 5: passive+modal, passive reporting structures và từ vựng báo chí.","objectives":["Tổng hợp can-do Unit 5","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u05-l5-q1','b2-u05-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Chia động từ: ''The report must ___ (submit) before the deadline.''","acceptedAnswers":["be submitted"],"explanationVi":"must be submitted = bị động hiện tại với modal."}'::jsonb),
 ('b2-u05-l5-q2','b2-u05-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (passive reporting dạng 2):","options":[{"id":"a","text":"She is believed that she escaped."},{"id":"b","text":"She is believed to have escaped."},{"id":"c","text":"She believed to escape."}],"correctOptionId":"b","explanationVi":"Dạng 2: is believed to have + V3."}'::jsonb),
 ('b2-u05-l5-q3','b2-u05-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''nhân chứng mắt thấy''?","options":[{"id":"a","text":"source"},{"id":"b","text":"authority"},{"id":"c","text":"eyewitness"}],"correctOptionId":"c","explanationVi":"eyewitness = nhân chứng trực tiếp."}'::jsonb),
 ('b2-u05-l5-q4','b2-u05-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Chuyển sang dạng 1: ''Scientists believe the drug is effective.'' →","acceptedAnswers":["It is believed that the drug is effective."],"explanationVi":"It is believed that + clause."}'::jsonb),
 ('b2-u05-l5-q5','b2-u05-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Chọn câu ĐÚNG (bị động quá khứ với modal):","options":[{"id":"a","text":"The package should been delivered."},{"id":"b","text":"The package should have been delivered."},{"id":"c","text":"The package should be delivered yesterday."}],"correctOptionId":"b","explanationVi":"Quá khứ bị động: should have been delivered."}'::jsonb),
 ('b2-u05-l5-q6','b2-u05-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"allege","right":"cáo buộc"},{"left":"speculation","right":"đồn đoán"},{"left":"denial","right":"sự phủ nhận"},{"left":"transparent","right":"minh bạch"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u05-l5-q7','b2-u05-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Điền đúng: ''___ reported that several people are missing.''","acceptedAnswers":["It is","It was"],"explanationVi":"It is/was reported that..."}'::jsonb),
 ('b2-u05-l5-q8','b2-u05-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["stolen","might","data","The","have","been"],"correctOrder":[3,0,1,2,4,5],"explanationVi":"The data might have been stolen."}'::jsonb),
 ('b2-u05-l5-q9','b2-u05-l5','multiple_choice',9,'quiz','medium',true,'{"question":"''Questions need to be asked.'' — Cấu trúc này là gì?","options":[{"id":"a","text":"Modal + be + V3"},{"id":"b","text":"Need + passive (need to be + V3)"},{"id":"c","text":"Passive reporting"}],"correctOptionId":"b","explanationVi":"need to be + V3 = need + passive."}'::jsonb),
 ('b2-u05-l5-q10','b2-u05-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Chuyển sang dạng 2: ''It is said that he left the company.'' →","acceptedAnswers":["He is said to have left the company."],"explanationVi":"is said to have left (perfect infinitive = hành động đã xảy ra)."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u05-l5' WHERE id = 'b2-u05';
