-- ══════════════════════════════════════════════════════════════════════════
-- B2 Units 06-07
-- Unit 06: Getting Things Done — Causative have/get; Reported Orders
-- Unit 07: Detective Work — Past Deduction Modals; Criticism/Regret
-- ══════════════════════════════════════════════════════════════════════════

-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║ BƯỚC 0 — DỌN SẠCH (idempotent)                                           ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B2' AND id IN ('b2-u06','b2-u07');

DELETE FROM learning_lesson_activities
 WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B2' AND unit_id IN ('b2-u06','b2-u07'));

DELETE FROM learning_lessons WHERE level_code = 'B2' AND unit_id IN ('b2-u06','b2-u07');

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 06 — Getting Things Done
-- Causative have/get; Reported Orders & Requests
-- ══════════════════════════════════════════════════════════════════════════

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u06-l1','B2','reading','b2-u06','normal',1,'Causative Have & Get','have/get + something + done — nhờ người khác làm',12,25,70,'{}'::jsonb,
  '{"warmup":"''Tôi đã sửa xe.'' vs ''Tôi đã nhờ người sửa xe cho tôi.'' — Hai câu này khác nhau không? Tiếng Anh phân biệt bằng cách nào?",
    "objectives":["Dùng have/get + object + past participle để diễn đạt nhờ làm","Phân biệt have something done (nhờ làm) và do something yourself","Dùng get/have causative trong các ngữ cảnh khác nhau"],
    "grammarHtml":"<b>Causative Have:</b> have + object + V3 (past participle)<br><i>I had my hair cut. (Tôi đã cắt tóc — nhờ thợ cắt)</i><br><i>She has her car serviced every year.</i><br><b>Causative Get:</b> get + object + V3 (thông thường hơn have)<br><i>I got my laptop fixed. (Tôi nhờ ai đó sửa máy tính)</i><br><b>Sắc thái:</b><br>have = trang trọng hơn, nhấn kết quả dịch vụ<br>get = thông thường hơn, đôi khi nhấn nỗ lực đạt được<br><b>Các thì:</b><br>Present: I''m having the house painted. (đang thuê sơn)<br>Past: She had the contract checked.<br>Future: I''m going to have my teeth checked.<br><b>Lưu ý:</b> have + person + base verb = sai ngữ cảnh này; đúng là have + thing + V3<br><b>Causative get someone TO DO:</b><br>I got my brother to fix it. (thuyết phục/nhờ vả ai đó làm gì)",
    "vocabBlock":[
      {"word":"have something done","ipa":"/hæv ˈsʌmθɪŋ dʌn/","meaningVi":"nhờ ai làm gì (bị động nhân quả)","example":"I had my passport renewed last week."},
      {"word":"get something done","ipa":"/ɡet ˈsʌmθɪŋ dʌn/","meaningVi":"nhờ làm (thông thường)","example":"She got her nails done before the party."},
      {"word":"renovate","ipa":"/ˈrenəveɪt/","meaningVi":"cải tạo, tu sửa","example":"They renovated the old building."},
      {"word":"tailor-made","ipa":"/ˌteɪlə ˈmeɪd/","meaningVi":"may riêng, đặt làm","example":"He had a suit tailor-made."},
      {"word":"install","ipa":"/ɪnˈstɔːl/","meaningVi":"lắp đặt","example":"We had solar panels installed."}],
    "examples":[
      {"en":"I need to have my car repaired — the brakes are failing.","vi":"Tôi cần nhờ sửa xe — phanh đang hỏng."},
      {"en":"She got her wedding dress specially designed.","vi":"Cô ấy đặt thiết kế riêng cho váy cưới."},
      {"en":"They''re having their house renovated at the moment.","vi":"Họ đang nhờ người cải tạo nhà."},
      {"en":"I got my brother to help me move the furniture.","vi":"Tôi nhờ anh trai giúp chuyển đồ đạc."}],
    "commonMistakes":["❌ I had cut my hair. (tôi tự cắt) ≠ I had my hair cut. (nhờ thợ)","❌ I had my car to repair → ✅ I had my car repaired","get someone to do (infinitive) ≠ get something done (V3)"],
    "tips":["have/get + THING + V3 = nhờ làm dịch vụ.","get + PERSON + to do = thuyết phục/nhờ người cụ thể.","Progressive: be having/getting something done = đang trong quá trình thuê làm."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u06-l1-p1','b2-u06-l1','multiple_choice',1,'practice','easy',false,'{"question":"''Tôi nhờ người sửa máy tính.'' — Câu nào ĐÚNG?","options":[{"id":"a","text":"I repaired my computer."},{"id":"b","text":"I had my computer repaired."},{"id":"c","text":"I had repaired my computer."}],"correctOptionId":"b","explanationVi":"Nhờ người khác làm: have + object + V3."}'::jsonb),
 ('b2-u06-l1-p2','b2-u06-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chia động từ: ''She ___ her nails ___ (do) before the party.''","acceptedAnswers":["got / done","had / done"],"explanationVi":"Causative: got/had + object + V3."}'::jsonb),
 ('b2-u06-l1-p3','b2-u06-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"renovate","right":"cải tạo, tu sửa"},{"left":"install","right":"lắp đặt"},{"left":"tailor-made","right":"may riêng"},{"left":"get something done","right":"nhờ làm (thông thường)"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l1-p4','b2-u06-l1','grammar_fill_blank',4,'practice','medium',false,'{"question":"Hoàn thành: ''They ___ solar panels ___ (install) on their roof last summer.''","acceptedAnswers":["had / installed","got / installed"],"explanationVi":"have/get + object + V3."}'::jsonb),
 ('b2-u06-l1-p5','b2-u06-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Chúng tôi đang nhờ người cải tạo nhà lúc này.","acceptedAnswers":["We are having our house renovated at the moment.","We''re having the house renovated at the moment.","We are getting the house renovated at the moment."],"explanationVi":"Progressive causative: be having/getting something done."}'::jsonb),
 ('b2-u06-l1-p6','b2-u06-l1','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''I got my brother fix the car.''","acceptedAnswers":["I got my brother to fix the car."],"explanationVi":"get + person + TO DO (infinitive)."}'::jsonb),
 ('b2-u06-l1-p7','b2-u06-l1','multiple_choice',7,'practice','medium',false,'{"question":"Phân biệt: ''I cut my hair'' vs ''I had my hair cut'' — câu nào nghĩa là nhờ thợ?","options":[{"id":"a","text":"I cut my hair."},{"id":"b","text":"I had my hair cut."},{"id":"c","text":"Cả hai đều như nhau."}],"correctOptionId":"b","explanationVi":"have + hair + cut = nhờ thợ cắt; I cut = tự cắt."}'::jsonb),
 ('b2-u06-l1-q1','b2-u06-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Cấu trúc causative đúng là?","options":[{"id":"a","text":"have + V3 + object"},{"id":"b","text":"have + object + V3"},{"id":"c","text":"have + object + to V"}],"correctOptionId":"b","explanationVi":"Causative: have + object + V3."}'::jsonb),
 ('b2-u06-l1-q2','b2-u06-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chia động từ: ''I''m going to have my teeth ___ (check) next week.''","acceptedAnswers":["checked"],"explanationVi":"have + teeth + checked."}'::jsonb),
 ('b2-u06-l1-q3','b2-u06-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Chọn câu ĐÚNG nghĩa ''nhờ thợ sơn nhà'':","options":[{"id":"a","text":"I painted the house."},{"id":"b","text":"I had the house painted."},{"id":"c","text":"I had painted the house."}],"correctOptionId":"b","explanationVi":"had + house + painted = nhờ thợ sơn."}'::jsonb),
 ('b2-u06-l1-q4','b2-u06-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chia động từ: ''She ___ her dress ___ (design) especially for the event.''","acceptedAnswers":["had / designed","got / designed"],"explanationVi":"have/get + dress + designed."}'::jsonb),
 ('b2-u06-l1-q5','b2-u06-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"renovate","right":"cải tạo"},{"left":"install","right":"lắp đặt"},{"left":"tailor-made","right":"may riêng"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l1-q6','b2-u06-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["installed","We","solar","panels","had","our","roof","on"],"correctOrder":[1,4,2,3,0,5,6,7],"explanationVi":"We had solar panels installed on our roof."}'::jsonb),
 ('b2-u06-l1-q7','b2-u06-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chia động từ: ''He got his assistant ___ (book) the flights.''","acceptedAnswers":["to book"],"explanationVi":"get + person + to do."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u06-l2','B2','reading','b2-u06','normal',2,'Reported Speech: Orders & Requests','tell/ask/order/warn + object + to-infinitive',12,25,70,'{}'::jsonb,
  '{"warmup":"Sếp bạn nói: ''Nộp báo cáo trước thứ Sáu!'' — Bạn kể lại điều đó như thế nào? ''Sếp nói rằng...'' hay ''Sếp bảo tôi...''?",
    "objectives":["Dùng tell/ask/order/warn/advise/remind + object + to-infinitive để tường thuật lệnh, yêu cầu","Chuyển đổi câu mệnh lệnh trực tiếp → gián tiếp","Dùng đúng phủ định not to do"],
    "grammarHtml":"<b>Reported Orders & Requests:</b><br>Trực tiếp → Gián tiếp (câu mệnh lệnh)<br>''Submit the report!'' → He told me to submit the report.<br>''Don''t be late!'' → She told me not to be late.<br><b>Các động từ thường dùng:</b><br>tell + object + to do (lệnh, thông thường)<br>ask + object + to do (yêu cầu lịch sự)<br>order + object + to do (lệnh mạnh, chính thức)<br>warn + object + not to do (cảnh báo)<br>advise + object + to do (khuyên)<br>remind + object + to do (nhắc nhở)<br>forbid + object + to do (cấm)<br>encourage + object + to do (khuyến khích)<br><b>Lưu ý:</b> không dùng that-clause sau tell (mệnh lệnh):<br>❌ He told me that submit the report. → ✅ He told me to submit.",
    "vocabBlock":[
      {"word":"order","ipa":"/ˈɔːdə/","meaningVi":"ra lệnh (động từ)","example":"The commander ordered them to retreat."},
      {"word":"warn","ipa":"/wɔːn/","meaningVi":"cảnh báo","example":"She warned me not to touch it."},
      {"word":"forbid","ipa":"/fəˈbɪd/","meaningVi":"cấm","example":"He was forbidden to leave."},
      {"word":"remind","ipa":"/rɪˈmaɪnd/","meaningVi":"nhắc nhở","example":"Can you remind him to call?"},
      {"word":"encourage","ipa":"/ɪnˈkʌrɪdʒ/","meaningVi":"khuyến khích","example":"She encouraged me to apply."}],
    "examples":[
      {"en":"''Leave the office!'' → He ordered them to leave the office.","vi":"''Rời văn phòng!'' → Anh ấy ra lệnh cho họ rời văn phòng."},
      {"en":"''Please don''t touch the exhibits.'' → The guide asked us not to touch the exhibits.","vi":"''Vui lòng không chạm vào hiện vật.'' → Hướng dẫn viên đề nghị chúng tôi không chạm vào."},
      {"en":"''You should see a doctor.'' → She advised him to see a doctor.","vi":"''Bạn nên gặp bác sĩ.'' → Cô ấy khuyên anh ấy đi khám."},
      {"en":"''Remember to lock the door.'' → She reminded me to lock the door.","vi":"''Nhớ khoá cửa nhé.'' → Cô ấy nhắc tôi khoá cửa."}],
    "commonMistakes":["❌ She told to go → ✅ She told me to go (tell cần object)","❌ He said me to leave → ✅ He told me to leave (say không dùng với object + to)","❌ She warned me don''t touch → ✅ She warned me not to touch"],
    "tips":["Phủ định: tell/ask + object + NOT to do.","say ≠ tell: say không có object; tell cần object.","order/forbid = trang trọng, mạnh hơn tell/ask."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u06-l2-p1','b2-u06-l2','multiple_choice',1,'practice','easy',false,'{"question":"''Don''t open the door.'' → She warned me ___ the door.","options":[{"id":"a","text":"not to open"},{"id":"b","text":"don''t open"},{"id":"c","text":"to not opening"}],"correctOptionId":"a","explanationVi":"Phủ định reported: warn + object + not to do."}'::jsonb),
 ('b2-u06-l2-p2','b2-u06-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Chuyển sang gián tiếp: ''Submit the report by Friday!'' → The manager told me ___ the report by Friday.","acceptedAnswers":["to submit"],"explanationVi":"tell + object + to do."}'::jsonb),
 ('b2-u06-l2-p3','b2-u06-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối động từ với nghĩa:","pairs":[{"left":"order","right":"ra lệnh"},{"left":"warn","right":"cảnh báo"},{"left":"forbid","right":"cấm"},{"left":"encourage","right":"khuyến khích"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l2-p4','b2-u06-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Chuyển sang gián tiếp: ''You should apply for the scholarship.'' → She advised him ___ for the scholarship.","acceptedAnswers":["to apply"],"explanationVi":"advise + object + to do."}'::jsonb),
 ('b2-u06-l2-p5','b2-u06-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Anh ấy nhắc tôi nhớ mang theo hộ chiếu.","acceptedAnswers":["He reminded me to bring my passport.","He reminded me to take my passport."],"explanationVi":"remind + object + to do."}'::jsonb),
 ('b2-u06-l2-p6','b2-u06-l2','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''He said me to leave immediately.''","acceptedAnswers":["He told me to leave immediately."],"explanationVi":"say không có object + to; dùng tell + object + to do."}'::jsonb),
 ('b2-u06-l2-p7','b2-u06-l2','multiple_choice',7,'practice','medium',false,'{"question":"''Stop talking in class!'' → The teacher ___ them ___ in class.","options":[{"id":"a","text":"told / to stop talking"},{"id":"b","text":"said / stop talking"},{"id":"c","text":"ordered / not stop talking"}],"correctOptionId":"a","explanationVi":"told + object + to stop talking."}'::jsonb),
 ('b2-u06-l2-q1','b2-u06-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (reported request):","options":[{"id":"a","text":"She asked me helping her."},{"id":"b","text":"She asked me to help her."},{"id":"c","text":"She asked that I help her."}],"correctOptionId":"b","explanationVi":"ask + object + to do."}'::jsonb),
 ('b2-u06-l2-q2','b2-u06-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Chuyển sang gián tiếp: ''Don''t worry!'' → She told me ___ worry.","acceptedAnswers":["not to"],"explanationVi":"tell + object + not to do."}'::jsonb),
 ('b2-u06-l2-q3','b2-u06-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Động từ nào cần object trực tiếp trước to-infinitive?","options":[{"id":"a","text":"say"},{"id":"b","text":"tell"},{"id":"c","text":"suggest"}],"correctOptionId":"b","explanationVi":"tell + object + to do; say không có object trực tiếp."}'::jsonb),
 ('b2-u06-l2-q4','b2-u06-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chuyển sang gián tiếp: ''You must not enter this area!'' → The officer forbade them ___ that area.","acceptedAnswers":["to enter"],"explanationVi":"forbid + object + to do."}'::jsonb),
 ('b2-u06-l2-q5','b2-u06-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối động từ với nghĩa:","pairs":[{"left":"remind","right":"nhắc nhở"},{"left":"encourage","right":"khuyến khích"},{"left":"warn","right":"cảnh báo"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l2-q6','b2-u06-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["late","told","not","She","be","me","to"],"correctOrder":[3,1,2,4,5,0,6],"explanationVi":"She told me not to be late."}'::jsonb),
 ('b2-u06-l2-q7','b2-u06-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chuyển sang gián tiếp: ''Work harder!'' → The coach encouraged them ___ harder.","acceptedAnswers":["to work"],"explanationVi":"encourage + object + to do."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u06-l3','B2','reading','b2-u06','normal',3,'Services & Daily Life Vocabulary','Từ vựng dịch vụ & cuộc sống hàng ngày B2',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn thường nhờ ai làm gì? Sửa xe? Cắt tóc? Thiết kế? Bạn biết những từ nào liên quan đến dịch vụ?",
    "objectives":["Học 10 từ vựng B2 về dịch vụ và cuộc sống","Dùng từ trong ngữ cảnh causative","Phân biệt từ theo ngữ cảnh dịch vụ chuyên nghiệp và đời thường"],
    "vocabBlock":[
      {"word":"premises","ipa":"/ˈpremɪsɪz/","meaningVi":"cơ sở, địa điểm (kinh doanh)","example":"The restaurant has just had its premises renovated."},
      {"word":"contractor","ipa":"/ˈkɒntræktə/","meaningVi":"nhà thầu","example":"We hired a contractor to fix the roof."},
      {"word":"maintenance","ipa":"/ˈmeɪntənəns/","meaningVi":"bảo trì, bảo dưỡng","example":"Regular maintenance prevents breakdowns."},
      {"word":"plumber","ipa":"/ˈplʌmə/","meaningVi":"thợ sửa ống nước","example":"We had a plumber fix the leaking pipe."},
      {"word":"electrician","ipa":"/ɪˌlekˈtrɪʃn/","meaningVi":"thợ điện","example":"Get an electrician to check the wiring."},
      {"word":"refurbish","ipa":"/ˌriːˈfɜːbɪʃ/","meaningVi":"tân trang lại","example":"The office was completely refurbished."},
      {"word":"upkeep","ipa":"/ˈʌpkiːp/","meaningVi":"chi phí bảo dưỡng","example":"The upkeep of the building is expensive."},
      {"word":"alter","ipa":"/ˈɔːltə/","meaningVi":"chỉnh sửa (quần áo/thiết kế)","example":"I had my suit altered to fit better."},
      {"word":"dry-clean","ipa":"/ˈdraɪ kliːn/","meaningVi":"giặt khô","example":"I have my coat dry-cleaned once a year."},
      {"word":"on-site","ipa":"/ˈɒn saɪt/","meaningVi":"tại chỗ","example":"We can do on-site repairs."}],
    "examples":[
      {"en":"We''re having the office premises refurbished next month.","vi":"Chúng tôi sẽ nhờ tân trang lại cơ sở văn phòng tháng tới."},
      {"en":"She had her dress altered to fit her perfectly.","vi":"Cô ấy nhờ chỉnh lại váy cho vừa hơn."},
      {"en":"We need to get the electrical wiring checked by a qualified electrician.","vi":"Chúng tôi cần nhờ thợ điện có trình độ kiểm tra hệ thống điện."}],
    "commonMistakes":["premises (số nhiều, nhưng chỉ một địa điểm): the premises are → đúng, dù chỉ 1 toà nhà.","maintenance (uncountable): regular maintenance (không có ''a maintenance'').","contractor (nhà thầu lớn) ≠ tradesperson (thợ như plumber, electrician)."],
    "tips":["have/get something done + từ vựng dịch vụ = ngữ cảnh tự nhiên.","on-site = tại chỗ (trái với remote)."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u06-l3-p1','b2-u06-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"contractor","right":"nhà thầu"},{"left":"maintenance","right":"bảo trì"},{"left":"plumber","right":"thợ sửa ống nước"},{"left":"electrician","right":"thợ điện"}],"explanationVi":"Từ vựng dịch vụ."}'::jsonb),
 ('b2-u06-l3-p2','b2-u06-l3','vocabulary_match',2,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"refurbish","right":"tân trang lại"},{"left":"alter","right":"chỉnh sửa"},{"left":"dry-clean","right":"giặt khô"},{"left":"upkeep","right":"chi phí bảo dưỡng"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l3-p3','b2-u06-l3','multiple_choice',3,'practice','easy',false,'{"question":"Điền từ đúng: ''We had the office ___ — it looks completely different now.''","options":[{"id":"a","text":"refurbished"},{"id":"b","text":"altered"},{"id":"c","text":"dry-cleaned"}],"correctOptionId":"a","explanationVi":"refurbish = tân trang lại cơ sở/văn phòng."}'::jsonb),
 ('b2-u06-l3-p4','b2-u06-l3','multiple_choice',4,'practice','medium',false,'{"question":"Điền từ đúng: ''The ___ of a large property can be very costly.''","options":[{"id":"a","text":"upkeep"},{"id":"b","text":"premises"},{"id":"c","text":"on-site"}],"correctOptionId":"a","explanationVi":"upkeep = chi phí bảo dưỡng thường xuyên."}'::jsonb),
 ('b2-u06-l3-p5','b2-u06-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Chúng tôi đã thuê một nhà thầu để sửa lại mái nhà.","acceptedAnswers":["We hired a contractor to fix the roof.","We got a contractor to repair the roof."],"explanationVi":"hire/get + contractor + to do."}'::jsonb),
 ('b2-u06-l3-p6','b2-u06-l3','multiple_choice',6,'practice','medium',false,'{"question":"Từ nào mô tả dịch vụ được thực hiện ngay tại địa điểm?","options":[{"id":"a","text":"on-site"},{"id":"b","text":"tailor-made"},{"id":"c","text":"upkeep"}],"correctOptionId":"a","explanationVi":"on-site = tại chỗ."}'::jsonb),
 ('b2-u06-l3-p7','b2-u06-l3','vocabulary_match',7,'practice','easy',false,'{"question":"Nối từ còn lại:","pairs":[{"left":"premises","right":"cơ sở, địa điểm"},{"left":"on-site","right":"tại chỗ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l3-q1','b2-u06-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"electrician","right":"thợ điện"},{"left":"refurbish","right":"tân trang"},{"left":"maintenance","right":"bảo trì"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l3-q2','b2-u06-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Từ nào chỉ người sửa đường ống nước?","options":[{"id":"a","text":"contractor"},{"id":"b","text":"plumber"},{"id":"c","text":"electrician"}],"correctOptionId":"b","explanationVi":"plumber = thợ sửa ống nước."}'::jsonb),
 ('b2-u06-l3-q3','b2-u06-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Điền từ đúng: ''I had my coat ___ — it''s much cleaner now.''","options":[{"id":"a","text":"altered"},{"id":"b","text":"dry-cleaned"},{"id":"c","text":"refurbished"}],"correctOptionId":"b","explanationVi":"have + coat + dry-cleaned."}'::jsonb),
 ('b2-u06-l3-q4','b2-u06-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền từ đúng: ''The company has had its ___ completely renovated.''","acceptedAnswers":["premises"],"explanationVi":"premises = cơ sở (business location)."}'::jsonb),
 ('b2-u06-l3-q5','b2-u06-l3','multiple_choice',12,'quiz','medium',true,'{"question":"Điền từ đúng: ''We need to get the wiring checked by a qualified ___.''","options":[{"id":"a","text":"contractor"},{"id":"b","text":"plumber"},{"id":"c","text":"electrician"}],"correctOptionId":"c","explanationVi":"electrician = thợ điện."}'::jsonb),
 ('b2-u06-l3-q6','b2-u06-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["suit","had","his","He","altered","tailor-made","a"],"correctOrder":[3,1,2,0,4,5,6],"explanationVi":"He had his suit altered — or He had a tailor-made suit."}'::jsonb),
 ('b2-u06-l3-q7','b2-u06-l3','vocabulary_match',14,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"upkeep","right":"chi phí bảo dưỡng"},{"left":"on-site","right":"tại chỗ"},{"left":"alter","right":"chỉnh sửa"}],"explanationVi":"Ghép đúng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u06-l4','B2','reading','b2-u06','normal',4,'Home Renovation Project','Đọc hiểu: Dự án cải tạo nhà',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc bài viết về dự án cải tạo nhà — chú ý cách dùng causative have/get và reported orders.",
    "objectives":["Đọc hiểu văn bản B2 về dịch vụ","Nhận biết causative have/get và reported speech trong ngữ cảnh","Trả lời câu hỏi suy luận"],
    "vocabBlock":[
      {"word":"quote","ipa":"/kwəʊt/","meaningVi":"báo giá","example":"Get several quotes before choosing a contractor."},
      {"word":"overrun","ipa":"/ˌəʊvəˈrʌn/","meaningVi":"vượt mức (chi phí/thời gian)","example":"The project overran by three weeks."},
      {"word":"disruption","ipa":"/dɪsˈrʌpʃn/","meaningVi":"sự gián đoạn","example":"The renovation caused a lot of disruption."},
      {"word":"deadline","ipa":"/ˈdedlaɪn/","meaningVi":"hạn chót","example":"They missed the deadline by two weeks."}],
    "examples":[
      {"en":"When Minh and Lan decided to have their apartment renovated, they expected it to take six weeks. They had the walls replastered, the floors retiled, and the kitchen completely refitted. They got a local contractor to provide a quote and were pleased with the price. However, the project overran significantly. ''Don''t worry,'' the contractor had told them, ''we''ll be done by Friday.'' But Friday came and went, and the electrician still hadn''t been called. Minh reminded the contractor to arrange the electrical work. Lan advised him to get everything in writing next time. ''We should have had the contract checked by a lawyer,'' she said. Despite the disruption, the finished apartment was exactly what they had imagined. They''re now having new furniture delivered and are having the place professionally cleaned before moving back in.","vi":"Khi Minh và Lan quyết định nhờ cải tạo căn hộ, họ kỳ vọng sẽ mất sáu tuần. Họ nhờ trát lại tường, lát lại sàn và tân trang hoàn toàn nhà bếp. Họ nhờ một nhà thầu địa phương báo giá và hài lòng với giá cả. Tuy nhiên, dự án bị chậm đáng kể. ''Đừng lo,'' nhà thầu đã nói với họ, ''chúng tôi sẽ xong trước thứ Sáu.'' Nhưng thứ Sáu đến rồi đi, và thợ điện vẫn chưa được gọi đến. Minh nhắc nhở nhà thầu thu xếp công việc điện. Lan khuyên anh ấy lần sau hãy lấy mọi thứ bằng văn bản. ''Lẽ ra chúng ta nên nhờ luật sư kiểm tra hợp đồng,'' cô nói. Dù có sự gián đoạn, căn hộ hoàn thiện đúng như những gì họ đã hình dung. Bây giờ họ đang nhờ giao nội thất mới và đang nhờ dọn dẹp chuyên nghiệp trước khi dọn vào ở lại."}],
    "commonMistakes":["Chú ý causative trong bài: had the walls replastered, got a contractor to provide, are having furniture delivered."],
    "tips":["Bài dùng nhiều thì khác nhau của causative (past, future, progressive).","We should have had... = tiếc nuối quá khứ với causative."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u06-l4-p1','b2-u06-l4','multiple_choice',1,'practice','easy',false,'{"question":"Minh và Lan dự kiến dự án mất bao lâu?","options":[{"id":"a","text":"Ba tuần"},{"id":"b","text":"Sáu tuần"},{"id":"c","text":"Hai tháng"}],"correctOptionId":"b","explanationVi":"''expected it to take six weeks.''"}'::jsonb),
 ('b2-u06-l4-p2','b2-u06-l4','multiple_choice',2,'practice','easy',false,'{"question":"Họ nhờ làm những gì trong căn hộ? (chọn sai)","options":[{"id":"a","text":"Trát lại tường và lát lại sàn"},{"id":"b","text":"Tân trang nhà bếp"},{"id":"c","text":"Xây thêm phòng ngủ"}],"correctOptionId":"c","explanationVi":"Bài không đề cập xây thêm phòng."}'::jsonb),
 ('b2-u06-l4-p3','b2-u06-l4','multiple_choice',3,'practice','medium',false,'{"question":"Vấn đề chính xảy ra với dự án là gì?","options":[{"id":"a","text":"Nhà thầu bỏ việc"},{"id":"b","text":"Dự án bị chậm và thợ điện chưa được gọi"},{"id":"c","text":"Họ không có ngân sách"}],"correctOptionId":"b","explanationVi":"''the project overran'' + ''electrician still hadn''t been called.''"}'::jsonb),
 ('b2-u06-l4-p4','b2-u06-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"quote","right":"báo giá"},{"left":"overrun","right":"vượt mức"},{"left":"disruption","right":"sự gián đoạn"},{"left":"deadline","right":"hạn chót"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l4-p5','b2-u06-l4','multiple_choice',5,'practice','medium',false,'{"question":"Lan khuyên Minh điều gì cho lần sau?","options":[{"id":"a","text":"Chọn nhà thầu khác"},{"id":"b","text":"Lấy mọi thứ bằng văn bản"},{"id":"c","text":"Tự làm không thuê thầu"}],"correctOptionId":"b","explanationVi":"''advised him to get everything in writing next time.''"}'::jsonb),
 ('b2-u06-l4-p6','b2-u06-l4','multiple_choice',6,'practice','medium',false,'{"question":"Cấu trúc nào xuất hiện trong: ''They''re now having new furniture delivered''?","options":[{"id":"a","text":"Reported speech"},{"id":"b","text":"Passive reporting"},{"id":"c","text":"Progressive causative"}],"correctOptionId":"c","explanationVi":"be having something delivered = causative progressive."}'::jsonb),
 ('b2-u06-l4-p7','b2-u06-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành câu tiếc nuối trong bài: ''We should ___ the contract checked by a lawyer.''","acceptedAnswers":["have had"],"explanationVi":"should have had + object + V3 = tiếc nuối causative."}'::jsonb),
 ('b2-u06-l4-q1','b2-u06-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Cuối cùng họ có hài lòng với kết quả không?","options":[{"id":"a","text":"Không, quá thất vọng"},{"id":"b","text":"Có, đúng như hình dung"},{"id":"c","text":"Chỉ hài lòng một phần"}],"correctOptionId":"b","explanationVi":"''the finished apartment was exactly what they had imagined.''"}'::jsonb),
 ('b2-u06-l4-q2','b2-u06-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Ai nhắc nhà thầu thu xếp công việc điện?","options":[{"id":"a","text":"Lan"},{"id":"b","text":"Minh"},{"id":"c","text":"Thợ điện"}],"correctOptionId":"b","explanationVi":"''Minh reminded the contractor to arrange the electrical work.''"}'::jsonb),
 ('b2-u06-l4-q3','b2-u06-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Cấu trúc trong ''got a local contractor to provide a quote'' là?","options":[{"id":"a","text":"have + object + V3"},{"id":"b","text":"get + person + to do"},{"id":"c","text":"reported speech"}],"correctOptionId":"b","explanationVi":"get + person + to do = nhờ/thuê người cụ thể."}'::jsonb),
 ('b2-u06-l4-q4','b2-u06-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''They had the walls ___ (replaster).''","acceptedAnswers":["replastered"],"explanationVi":"have + walls + replastered."}'::jsonb),
 ('b2-u06-l4-q5','b2-u06-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Từ ''overrun'' trong bài có nghĩa là?","options":[{"id":"a","text":"Hoàn thành sớm"},{"id":"b","text":"Vượt thời gian/chi phí dự kiến"},{"id":"c","text":"Huỷ bỏ"}],"correctOptionId":"b","explanationVi":"overrun = vượt mức kế hoạch."}'::jsonb),
 ('b2-u06-l4-q6','b2-u06-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"disruption","right":"sự gián đoạn"},{"left":"quote","right":"báo giá"},{"left":"deadline","right":"hạn chót"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l4-q7','b2-u06-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chuyển sang gián tiếp: ''We''ll be done by Friday!'' → The contractor told them they ___ done by Friday.","acceptedAnswers":["would be"],"explanationVi":"Tường thuật: will → would."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u06-l5','B2','reading','b2-u06','unit_review',5,'Unit 6 Review','Ôn tập Unit 6: Nhờ người làm',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 6: causative have/get, reported orders và từ vựng dịch vụ.","objectives":["Tổng hợp can-do Unit 6","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u06-l5-q1','b2-u06-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Chia động từ: ''I need to have my passport ___ (renew).''","acceptedAnswers":["renewed"],"explanationVi":"have + passport + renewed."}'::jsonb),
 ('b2-u06-l5-q2','b2-u06-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (nhờ thợ sơn nhà):","options":[{"id":"a","text":"I painted the house last week."},{"id":"b","text":"I had the house painted last week."},{"id":"c","text":"I had painted the house last week."}],"correctOptionId":"b","explanationVi":"Causative: had + house + painted."}'::jsonb),
 ('b2-u06-l5-q3','b2-u06-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Chuyển sang gián tiếp: ''Please help me.'' → She asked me ___ her.","options":[{"id":"a","text":"help"},{"id":"b","text":"to help"},{"id":"c","text":"helping"}],"correctOptionId":"b","explanationVi":"ask + object + to do."}'::jsonb),
 ('b2-u06-l5-q4','b2-u06-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Chia động từ: ''They are having the office ___ (refurbish) at the moment.''","acceptedAnswers":["refurbished"],"explanationVi":"Progressive causative: are having + office + refurbished."}'::jsonb),
 ('b2-u06-l5-q5','b2-u06-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào ĐÚNG (get + person + to do):","options":[{"id":"a","text":"I got my assistant fixed the problem."},{"id":"b","text":"I got my assistant to fix the problem."},{"id":"c","text":"I got my assistant fixing the problem."}],"correctOptionId":"b","explanationVi":"get + person + to do (infinitive)."}'::jsonb),
 ('b2-u06-l5-q6','b2-u06-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"contractor","right":"nhà thầu"},{"left":"plumber","right":"thợ ống nước"},{"left":"maintenance","right":"bảo trì"},{"left":"refurbish","right":"tân trang"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u06-l5-q7','b2-u06-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Chuyển sang gián tiếp: ''Don''t touch the equipment!'' → The supervisor warned them ___ the equipment.","acceptedAnswers":["not to touch"],"explanationVi":"warn + object + not to do."}'::jsonb),
 ('b2-u06-l5-q8','b2-u06-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["checked","the","have","should","contract","We","by","a","have","lawyer"],"correctOrder":[5,8,1,4,3,2,6,7,0,9],"explanationVi":"We should have had the contract checked by a lawyer."}'::jsonb),
 ('b2-u06-l5-q9','b2-u06-l5','multiple_choice',9,'quiz','medium',true,'{"question":"Động từ nào KHÔNG dùng theo mẫu tell/ask + object + to do?","options":[{"id":"a","text":"order"},{"id":"b","text":"say"},{"id":"c","text":"remind"}],"correctOptionId":"b","explanationVi":"say không có object trực tiếp trước to-infinitive."}'::jsonb),
 ('b2-u06-l5-q10','b2-u06-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Chia động từ: ''They got a specialist ___ (assess) the damage.''","acceptedAnswers":["to assess"],"explanationVi":"get + person + to do."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u06-l5' WHERE id = 'b2-u06';

-- ══════════════════════════════════════════════════════════════════════════
-- UNIT 07 — Detective Work
-- Past Deduction Modals; Criticism/Regret (should/ought to have)
-- ══════════════════════════════════════════════════════════════════════════

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u07-l1','B2','reading','b2-u07','normal',1,'Deduction About the Past','must/can''t/could/might + have + V3 — suy luận quá khứ',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn về nhà thấy cửa mở. Bạn nghĩ: ''Ai đó đã vào!'' hay ''Chắc là tôi quên khoá.'' — Bạn diễn đạt điều này trong tiếng Anh như thế nào?",
    "objectives":["Dùng must have/can''t have/could have/might have + V3 để suy luận về quá khứ","Phân biệt mức độ chắc chắn (almost certain → possible → impossible)","Nhận biết bằng chứng dẫn đến suy luận"],
    "grammarHtml":"<b>Suy luận về quá khứ:</b><br><b>must have + V3</b> = gần như chắc chắn ĐÃ xảy ra (positive deduction)<br><i>She must have left early — her car is gone.</i><br><b>can''t have + V3</b> = gần như chắc chắn KHÔNG xảy ra (negative deduction)<br><i>He can''t have eaten it — he''s allergic.</i><br><b>could have + V3</b> = có thể ĐÃ xảy ra (open possibility)<br><i>She could have taken the wrong bus.</i><br><b>might have + V3</b> = có lẽ ĐÃ xảy ra (weak possibility)<br><i>He might have forgotten about the meeting.</i><br><b>may have + V3</b> = tương tự might have, hơi trang trọng hơn<br><b>Scale độ chắc chắn:</b><br>must have (90-99%) > could have > might have (30-50%) > can''t have (1-10%)",
    "vocabBlock":[
      {"word":"deduce","ipa":"/dɪˈdjuːs/","meaningVi":"suy luận, suy diễn","example":"From the evidence, we can deduce what happened."},
      {"word":"clue","ipa":"/kluː/","meaningVi":"manh mối","example":"The detective found an important clue."},
      {"word":"suspect","ipa":"/ˈsʌspekt/","meaningVi":"nghi phạm","example":"The suspect could have fled the scene."},
      {"word":"evidence","ipa":"/ˈevɪdəns/","meaningVi":"bằng chứng","example":"The evidence suggests he was there."},
      {"word":"alibi","ipa":"/ˈælɪbaɪ/","meaningVi":"bằng chứng ngoại phạm","example":"She had a solid alibi."}],
    "examples":[
      {"en":"The lights are on — she must have come home already.","vi":"Đèn sáng — chắc cô ấy đã về nhà rồi."},
      {"en":"He can''t have stolen it — he was on holiday.","vi":"Anh ấy không thể đã lấy nó — anh ấy đang đi nghỉ."},
      {"en":"The door was unlocked — someone might have broken in.","vi":"Cửa không khoá — có lẽ ai đó đã đột nhập."},
      {"en":"She could have taken a different route to avoid the traffic.","vi":"Cô ấy có thể đã đi đường khác để tránh tắc đường."}],
    "commonMistakes":["❌ She must left early → ✅ She must have left (cần have + V3)","❌ He can''t has eaten → ✅ He can''t have eaten (sau modal luôn dùng have)","Phân biệt must have (suy luận) ≠ had to (obligation ở quá khứ thực tế)."],
    "tips":["Bằng chứng hiện tại → suy luận nguyên nhân quá khứ: must have / can''t have.","Không chắc → might have / could have.","could have ≠ was able to: could have = khả năng; was able to = thực sự làm được."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u07-l1-p1','b2-u07-l1','multiple_choice',1,'practice','easy',false,'{"question":"''The lights are on but nobody answers.'' → She ___ home.","options":[{"id":"a","text":"must be"},{"id":"b","text":"must have gone"},{"id":"c","text":"can''t have been"}],"correctOptionId":"b","explanationVi":"Đèn sáng → gần chắc đã về: must have gone."}'::jsonb),
 ('b2-u07-l1-p2','b2-u07-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền modal đúng: ''He ___ (eat) the cake — he''s allergic to eggs.''","acceptedAnswers":["can''t have eaten","couldn''t have eaten"],"explanationVi":"Không thể đã ăn vì dị ứng → can''t have eaten."}'::jsonb),
 ('b2-u07-l1-p3','b2-u07-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"deduce","right":"suy luận"},{"left":"clue","right":"manh mối"},{"left":"suspect","right":"nghi phạm"},{"left":"alibi","right":"bằng chứng ngoại phạm"}],"explanationVi":"Từ vựng điều tra."}'::jsonb),
 ('b2-u07-l1-p4','b2-u07-l1','grammar_fill_blank',4,'practice','medium',false,'{"question":"Điền modal đúng (yếu, không chắc): ''She ___ (take) the wrong bus — she''s 30 minutes late.''","acceptedAnswers":["might have taken","could have taken","may have taken"],"explanationVi":"Không chắc → might/could/may have taken."}'::jsonb),
 ('b2-u07-l1-p5','b2-u07-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Nghi phạm chắc hẳn đã biết về kế hoạch — anh ta có mặt tại cuộc họp.","acceptedAnswers":["The suspect must have known about the plan — he was at the meeting.","The suspect must have known the plan — he was present at the meeting."],"explanationVi":"Gần chắc đã biết: must have known."}'::jsonb),
 ('b2-u07-l1-p6','b2-u07-l1','multiple_choice',6,'practice','medium',false,'{"question":"''There are muddy footprints on the floor.'' → Someone ___ through the garden.","options":[{"id":"a","text":"must have walked"},{"id":"b","text":"must walk"},{"id":"c","text":"could walk"}],"correctOptionId":"a","explanationVi":"Bằng chứng rõ ràng → must have walked."}'::jsonb),
 ('b2-u07-l1-p7','b2-u07-l1','error_correction',7,'practice','medium',false,'{"question":"Sửa lỗi: ''She must left her keys inside.''","acceptedAnswers":["She must have left her keys inside."],"explanationVi":"Suy luận quá khứ: must have + V3."}'::jsonb),
 ('b2-u07-l1-q1','b2-u07-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Modal nào diễn đạt ''gần như chắc chắn không xảy ra''?","options":[{"id":"a","text":"must have"},{"id":"b","text":"might have"},{"id":"c","text":"can''t have"}],"correctOptionId":"c","explanationVi":"can''t have = gần như chắc chắn không."}'::jsonb),
 ('b2-u07-l1-q2','b2-u07-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''The door is locked — they ___ (leave) already.''","acceptedAnswers":["must have left"],"explanationVi":"Cửa khoá → gần chắc đã đi: must have left."}'::jsonb),
 ('b2-u07-l1-q3','b2-u07-l1','multiple_choice',10,'quiz','medium',true,'{"question":"''She has a perfect alibi — she was in hospital.'' → She ___ the crime.","options":[{"id":"a","text":"must have committed"},{"id":"b","text":"might have committed"},{"id":"c","text":"can''t have committed"}],"correctOptionId":"c","explanationVi":"Có alibi → không thể đã làm: can''t have committed."}'::jsonb),
 ('b2-u07-l1-q4','b2-u07-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng (khả năng yếu): ''He ___ (forget) the password — he always forgets things.''","acceptedAnswers":["might have forgotten","could have forgotten","may have forgotten"],"explanationVi":"Khả năng có thể → might/could/may have forgotten."}'::jsonb),
 ('b2-u07-l1-q5','b2-u07-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"evidence","right":"bằng chứng"},{"left":"deduce","right":"suy luận"},{"left":"clue","right":"manh mối"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l1-q6','b2-u07-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["must","She","the","have","early","meeting","left","before"],"correctOrder":[1,0,3,4,2,5,6,7],"explanationVi":"She must have left before the early meeting."}'::jsonb),
 ('b2-u07-l1-q7','b2-u07-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền đúng: ''The wallet is gone — someone ___ (steal) it while we were distracted.''","acceptedAnswers":["must have stolen","could have stolen","might have stolen"],"explanationVi":"Ví đã mất → suy luận đã bị lấy."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u07-l2','B2','reading','b2-u07','normal',2,'Criticism & Regret','should/ought to + have + V3 — phê bình & tiếc nuối',12,25,70,'{}'::jsonb,
  '{"warmup":"''Lẽ ra anh ấy không nên nói điều đó.'' / ''Lẽ ra tôi đã phải đến sớm hơn.'' — Bạn nói những câu này như thế nào?",
    "objectives":["Dùng should have / ought to have + V3 để phê bình hoặc tiếc nuối về quá khứ","Dùng needn''t have + V3 (làm nhưng không cần thiết)","Phân biệt với didn''t need to (không làm vì không cần)"],
    "grammarHtml":"<b>Phê bình & tiếc nuối về quá khứ:</b><br><b>should have + V3</b> = lẽ ra nên (nhưng không làm)<br><i>You should have called me. (Lẽ ra bạn gọi cho tôi — nhưng không gọi)</i><br><b>shouldn''t have + V3</b> = lẽ ra không nên (nhưng đã làm)<br><i>He shouldn''t have said that. (Lẽ ra anh ấy không nói điều đó)</i><br><b>ought to have + V3</b> = tương tự should have, hơi trang trọng<br><i>She ought to have read the instructions first.</i><br><b>needn''t have + V3</b> = đã làm nhưng thực ra không cần thiết<br><i>You needn''t have brought food — there''s plenty. (Bạn đã mang thức ăn nhưng không cần)</i><br><b>didn''t need to + V</b> = không làm vì biết không cần<br><i>I didn''t need to pay — it was free. (Không trả tiền, vì biết miễn phí)</i>",
    "vocabBlock":[
      {"word":"in hindsight","ipa":"/ɪn ˈhaɪndsaɪt/","meaningVi":"nhìn lại","example":"In hindsight, I should have prepared more."},
      {"word":"oversight","ipa":"/ˈəʊvəsaɪt/","meaningVi":"sự bỏ sót, thiếu sót","example":"That was a serious oversight on my part."},
      {"word":"negligent","ipa":"/ˈneɡlɪdʒənt/","meaningVi":"cẩu thả, bất cẩn","example":"The driver was negligent."},
      {"word":"precaution","ipa":"/prɪˈkɔːʃn/","meaningVi":"biện pháp phòng ngừa","example":"We should have taken more precautions."}],
    "examples":[
      {"en":"You should have told me earlier — I could have helped.","vi":"Lẽ ra bạn nói với tôi sớm hơn — tôi có thể đã giúp."},
      {"en":"She shouldn''t have left the meeting without permission.","vi":"Lẽ ra cô ấy không nên rời cuộc họp mà không xin phép."},
      {"en":"You needn''t have cooked so much food — we already had dinner.","vi":"Bạn đã nấu nhiều thức ăn nhưng không cần thiết — chúng tôi đã ăn tối rồi."},
      {"en":"In hindsight, we ought to have checked the weather forecast.","vi":"Nhìn lại, lẽ ra chúng tôi nên xem dự báo thời tiết."}],
    "commonMistakes":["❌ You should have tell me → ✅ should have told (V3)","needn''t have done ≠ didn''t need to do: needn''t have = đã làm (lãng phí); didn''t need to = không làm.","ought to have = should have (không phải ought have)."],
    "tips":["should have + V3 = phê bình hay tiếc nuối (ai đó không làm đúng).","shouldn''t have + V3 = phê bình (ai đó làm điều không nên).","needn''t have + V3 = làm rồi nhưng không cần."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u07-l2-p1','b2-u07-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG: ''Lẽ ra anh ấy không nên nói điều đó.''","options":[{"id":"a","text":"He should have said that."},{"id":"b","text":"He shouldn''t have said that."},{"id":"c","text":"He needn''t have said that."}],"correctOptionId":"b","explanationVi":"Phê bình đã làm điều không nên: shouldn''t have said."}'::jsonb),
 ('b2-u07-l2-p2','b2-u07-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''You ___ (call) an ambulance immediately.''","acceptedAnswers":["should have called","ought to have called"],"explanationVi":"Lẽ ra nên gọi (nhưng không gọi): should have called."}'::jsonb),
 ('b2-u07-l2-p3','b2-u07-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"in hindsight","right":"nhìn lại"},{"left":"oversight","right":"sự bỏ sót"},{"left":"negligent","right":"cẩu thả"},{"left":"precaution","right":"biện pháp phòng ngừa"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l2-p4','b2-u07-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Điền đúng: ''You ___ (bring) an umbrella — it wasn''t necessary, the sun shone all day.''","acceptedAnswers":["needn''t have brought"],"explanationVi":"Đã mang nhưng không cần: needn''t have brought."}'::jsonb),
 ('b2-u07-l2-p5','b2-u07-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Nhìn lại, lẽ ra chúng tôi nên đặt vé máy bay sớm hơn.","acceptedAnswers":["In hindsight, we should have booked the flights earlier.","Looking back, we ought to have booked the tickets earlier."],"explanationVi":"In hindsight + should have booked."}'::jsonb),
 ('b2-u07-l2-p6','b2-u07-l2','multiple_choice',6,'practice','medium',false,'{"question":"Phân biệt: ''I needn''t have paid'' vs ''I didn''t need to pay'' — câu nào nghĩa là KHÔNG trả tiền?","options":[{"id":"a","text":"I needn''t have paid."},{"id":"b","text":"I didn''t need to pay."},{"id":"c","text":"Cả hai giống nhau."}],"correctOptionId":"b","explanationVi":"didn''t need to pay = biết không cần → không trả. needn''t have paid = đã trả nhưng không cần."}'::jsonb),
 ('b2-u07-l2-p7','b2-u07-l2','error_correction',7,'practice','medium',false,'{"question":"Sửa lỗi: ''She ought have told the truth.''","acceptedAnswers":["She ought to have told the truth."],"explanationVi":"ought TO have + V3 (không bỏ to)."}'::jsonb),
 ('b2-u07-l2-q1','b2-u07-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG: phê bình người đã làm điều không nên:","options":[{"id":"a","text":"You should have done that."},{"id":"b","text":"You shouldn''t have done that."},{"id":"c","text":"You needn''t have done that."}],"correctOptionId":"b","explanationVi":"Phê bình đã làm: shouldn''t have done."}'::jsonb),
 ('b2-u07-l2-q2','b2-u07-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''They ___ (read) the safety instructions before operating the machine.''","acceptedAnswers":["should have read","ought to have read"],"explanationVi":"Lẽ ra nên đọc: should/ought to have read."}'::jsonb),
 ('b2-u07-l2-q3','b2-u07-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Câu nào diễn đạt ''đã làm nhưng không cần thiết''?","options":[{"id":"a","text":"I should have prepared."},{"id":"b","text":"I needn''t have prepared."},{"id":"c","text":"I didn''t need to prepare."}],"correctOptionId":"b","explanationVi":"needn''t have prepared = đã chuẩn bị nhưng không cần."}'::jsonb),
 ('b2-u07-l2-q4','b2-u07-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng (phê bình): ''He ___ (take) more precautions — the accident could have been avoided.''","acceptedAnswers":["should have taken","ought to have taken"],"explanationVi":"Lẽ ra nên cẩn thận hơn."}'::jsonb),
 ('b2-u07-l2-q5','b2-u07-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"negligent","right":"cẩu thả"},{"left":"precaution","right":"biện pháp phòng ngừa"},{"left":"oversight","right":"sự bỏ sót"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l2-q6','b2-u07-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["have","You","told","me","earlier","should"],"correctOrder":[1,5,0,2,3,4],"explanationVi":"You should have told me earlier."}'::jsonb),
 ('b2-u07-l2-q7','b2-u07-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Phân biệt: ''She ___ (rush) — the meeting was cancelled.'' (biết trước, không vội)","acceptedAnswers":["didn''t need to rush"],"explanationVi":"Biết không cần thiết → didn''t need to rush (không vội)."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u07-l3','B2','reading','b2-u07','normal',3,'Crime & Investigation Vocabulary','Từ vựng tội phạm & điều tra B2',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn có xem phim hình sự không? Bạn biết những từ nào về điều tra tội phạm?",
    "objectives":["Học 10 từ vựng B2 về tội phạm và điều tra","Dùng từ trong ngữ cảnh suy luận quá khứ","Phân biệt từ theo vai trò trong vụ án"],
    "vocabBlock":[
      {"word":"detective","ipa":"/dɪˈtektɪv/","meaningVi":"thám tử, điều tra viên","example":"The detective examined the crime scene."},
      {"word":"forensic","ipa":"/fəˈrensɪk/","meaningVi":"pháp y, điều tra khoa học","example":"Forensic evidence was crucial."},
      {"word":"motive","ipa":"/ˈməʊtɪv/","meaningVi":"động cơ (tội phạm)","example":"The detective established a motive."},
      {"word":"testimony","ipa":"/ˈtestɪməni/","meaningVi":"lời khai, chứng từ","example":"Her testimony was reliable."},
      {"word":"charge","ipa":"/tʃɑːdʒ/","meaningVi":"buộc tội, cáo buộc","example":"He was charged with fraud."},
      {"word":"acquit","ipa":"/əˈkwɪt/","meaningVi":"tuyên bố trắng án","example":"The jury acquitted her."},
      {"word":"convict","ipa":"/kənˈvɪkt/","meaningVi":"kết tội","example":"He was convicted of theft."},
      {"word":"witness","ipa":"/ˈwɪtnəs/","meaningVi":"nhân chứng","example":"A witness saw the incident."},
      {"word":"scene of the crime","ipa":"/siːn əv ðə kraɪm/","meaningVi":"hiện trường vụ án","example":"Police sealed the scene of the crime."},
      {"word":"frame","ipa":"/freɪm/","meaningVi":"vu oan, dàn dựng","example":"She claimed she had been framed."}],
    "examples":[
      {"en":"The detective must have found crucial evidence at the scene of the crime.","vi":"Thám tử chắc hẳn đã tìm thấy bằng chứng quan trọng tại hiện trường."},
      {"en":"The suspect can''t have been there — three witnesses confirmed his alibi.","vi":"Nghi phạm không thể đã có mặt ở đó — ba nhân chứng xác nhận bằng chứng ngoại phạm."},
      {"en":"She was convicted based on forensic evidence and witness testimony.","vi":"Cô bị kết tội dựa trên bằng chứng pháp y và lời khai của nhân chứng."}],
    "commonMistakes":["charge (buộc tội) ≠ convict (kết tội): charged = cáo buộc (chưa kết tội); convicted = đã kết tội.","acquit ≠ release: acquit = tuyên vô tội; release = thả (sau thụ án hoặc tạm giam).","frame (vu oan) = dàn dựng bằng chứng giả."],
    "tips":["scene of the crime / crime scene — cả hai đều đúng.","forensic + evidence/analysis/science.","charge → charged with + tội danh."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u07-l3-p1','b2-u07-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"detective","right":"thám tử"},{"left":"motive","right":"động cơ"},{"left":"testimony","right":"lời khai"},{"left":"witness","right":"nhân chứng"}],"explanationVi":"Từ vựng tội phạm."}'::jsonb),
 ('b2-u07-l3-p2','b2-u07-l3','vocabulary_match',2,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"charge","right":"buộc tội"},{"left":"acquit","right":"tuyên trắng án"},{"left":"convict","right":"kết tội"},{"left":"frame","right":"vu oan"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l3-p3','b2-u07-l3','multiple_choice',3,'practice','easy',false,'{"question":"Điền từ đúng: ''The police sealed the ___ of the crime.''","options":[{"id":"a","text":"scene"},{"id":"b","text":"forensic"},{"id":"c","text":"motive"}],"correctOptionId":"a","explanationVi":"scene of the crime = hiện trường."}'::jsonb),
 ('b2-u07-l3-p4','b2-u07-l3','multiple_choice',4,'practice','medium',false,'{"question":"Phân biệt: bị ''charged'' vs bị ''convicted'' — đâu là đã kết tội?","options":[{"id":"a","text":"charged"},{"id":"b","text":"convicted"},{"id":"c","text":"Cả hai giống nhau"}],"correctOptionId":"b","explanationVi":"convicted = đã bị tòa kết tội. charged = mới bị cáo buộc."}'::jsonb),
 ('b2-u07-l3-p5','b2-u07-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Cô ấy bị kết tội dựa trên bằng chứng pháp y.","acceptedAnswers":["She was convicted based on forensic evidence.","She was convicted on the basis of forensic evidence."],"explanationVi":"convicted based on forensic evidence."}'::jsonb),
 ('b2-u07-l3-p6','b2-u07-l3','multiple_choice',6,'practice','medium',false,'{"question":"Điền từ đúng: ''The detective established a clear ___ for the crime.''","options":[{"id":"a","text":"alibi"},{"id":"b","text":"motive"},{"id":"c","text":"testimony"}],"correctOptionId":"b","explanationVi":"motive = động cơ."}'::jsonb),
 ('b2-u07-l3-p7','b2-u07-l3','vocabulary_match',7,'practice','easy',false,'{"question":"Nối từ còn lại:","pairs":[{"left":"forensic","right":"pháp y"},{"left":"scene of the crime","right":"hiện trường vụ án"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l3-q1','b2-u07-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"motive","right":"động cơ"},{"left":"acquit","right":"tuyên trắng án"},{"left":"frame","right":"vu oan"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l3-q2','b2-u07-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''nhân chứng''?","options":[{"id":"a","text":"suspect"},{"id":"b","text":"witness"},{"id":"c","text":"detective"}],"correctOptionId":"b","explanationVi":"witness = nhân chứng."}'::jsonb),
 ('b2-u07-l3-q3','b2-u07-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Điền từ đúng: ''He was ___ with three counts of fraud.''","options":[{"id":"a","text":"convicted"},{"id":"b","text":"charged"},{"id":"c","text":"acquitted"}],"correctOptionId":"b","explanationVi":"charged with = bị cáo buộc (chưa kết tội)."}'::jsonb),
 ('b2-u07-l3-q4','b2-u07-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền từ đúng: ''___ evidence showed that the crime occurred at midnight.''","acceptedAnswers":["Forensic"],"explanationVi":"Forensic evidence = bằng chứng pháp y."}'::jsonb),
 ('b2-u07-l3-q5','b2-u07-l3','multiple_choice',12,'quiz','medium',true,'{"question":"''The jury found her not guilty.'' = The jury ___ her.","options":[{"id":"a","text":"convicted"},{"id":"b","text":"acquitted"},{"id":"c","text":"charged"}],"correctOptionId":"b","explanationVi":"not guilty → acquitted = tuyên trắng án."}'::jsonb),
 ('b2-u07-l3-q6','b2-u07-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["evidence","convicted","forensic","He","was","on","based"],"correctOrder":[3,1,4,5,2,0,6],"explanationVi":"He was convicted based on forensic evidence."}'::jsonb),
 ('b2-u07-l3-q7','b2-u07-l3','vocabulary_match',14,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"testimony","right":"lời khai"},{"left":"detective","right":"thám tử"},{"left":"scene of the crime","right":"hiện trường"}],"explanationVi":"Ghép đúng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u07-l4','B2','reading','b2-u07','normal',4,'The Missing Painting','Đọc hiểu: Vụ mất tranh',12,25,70,'{}'::jsonb,
  '{"warmup":"Một bức tranh nổi tiếng bị mất tại bảo tàng. Đọc báo cáo và thử suy luận chuyện gì đã xảy ra.",
    "objectives":["Đọc hiểu văn bản B2 kiểu điều tra","Nhận biết past deduction modals và should have trong ngữ cảnh","Suy luận từ bằng chứng được đưa ra"],
    "vocabBlock":[
      {"word":"retrieve","ipa":"/rɪˈtriːv/","meaningVi":"tìm lại, thu hồi","example":"Police hoped to retrieve the stolen painting."},
      {"word":"whereabouts","ipa":"/ˈweərəbaʊts/","meaningVi":"tung tích, nơi ở","example":"His whereabouts were unknown."},
      {"word":"surveillance","ipa":"/səˈveɪləns/","meaningVi":"sự giám sát","example":"The building had surveillance cameras."},
      {"word":"tamper with","ipa":"/ˈtæmpə wɪð/","meaningVi":"can thiệp, giả mạo","example":"Someone had tampered with the alarm."}],
    "examples":[
      {"en":"The painting must have been removed between midnight and 6am, when the museum was closed. The alarm hadn''t gone off, so the thief must have known the security code — or someone might have tampered with the system. The guard on duty should have checked the cameras every hour, but witnesses say he was absent. ''He ought to have stayed at his post,'' said the director. A forensic team found traces of paint on a fire exit, suggesting the thief could have left through the back of the building. No suspect has been charged yet, but police believe the theft can''t have been carried out by one person alone. Anyone with information on the whereabouts of the painting should contact the authorities.","vi":"Bức tranh chắc hẳn đã bị lấy đi giữa nửa đêm và 6 giờ sáng, khi bảo tàng đóng cửa. Chuông báo động không reo, vậy nên tên trộm chắc đã biết mã bảo mật — hoặc có người đã giả mạo hệ thống. Bảo vệ trực ca lẽ ra phải kiểm tra camera mỗi giờ, nhưng nhân chứng nói anh ta vắng mặt. ''Lẽ ra anh ta phải ở vị trí của mình,'' giám đốc nói. Đội pháp y tìm thấy vết sơn ở một lối thoát hiểm, cho thấy tên trộm có thể đã rời qua phía sau tòa nhà. Chưa có nghi phạm nào bị buộc tội, nhưng cảnh sát tin rằng vụ trộm không thể chỉ do một người thực hiện. Ai có thông tin về tung tích của bức tranh nên liên hệ nhà chức trách."}],
    "commonMistakes":["Để ý: must have been removed (bị động + suy luận), must have known, should have checked, ought to have stayed, could have left."],
    "tips":["Tìm bằng chứng trong văn bản → tìm cấu trúc suy luận đi kèm.","should/ought to have = phê bình người không thực hiện đúng trách nhiệm."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u07-l4-p1','b2-u07-l4','multiple_choice',1,'practice','easy',false,'{"question":"Theo bài, tranh bị lấy khi nào?","options":[{"id":"a","text":"Khi bảo tàng đông khách"},{"id":"b","text":"Giữa nửa đêm và 6 giờ sáng"},{"id":"c","text":"Trong giờ mở cửa"}],"correctOptionId":"b","explanationVi":"''between midnight and 6am, when the museum was closed.''"}'::jsonb),
 ('b2-u07-l4-p2','b2-u07-l4','multiple_choice',2,'practice','easy',false,'{"question":"Tại sao chuông không reo? Suy luận trong bài là?","options":[{"id":"a","text":"Chuông bị hỏng từ trước"},{"id":"b","text":"Tên trộm biết mã hoặc ai đó giả mạo hệ thống"},{"id":"c","text":"Bảo vệ tắt chuông"}],"correctOptionId":"b","explanationVi":"''must have known the security code — or might have tampered with the system.''"}'::jsonb),
 ('b2-u07-l4-p3','b2-u07-l4','multiple_choice',3,'practice','medium',false,'{"question":"Bảo vệ bị phê bình vì điều gì?","options":[{"id":"a","text":"Không kiểm tra camera mỗi giờ"},{"id":"b","text":"Không gọi cảnh sát"},{"id":"c","text":"Rời bảo tàng trước giờ"}],"correctOptionId":"a","explanationVi":"''should have checked the cameras every hour, but...was absent.''"}'::jsonb),
 ('b2-u07-l4-p4','b2-u07-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"retrieve","right":"tìm lại"},{"left":"whereabouts","right":"tung tích"},{"left":"surveillance","right":"sự giám sát"},{"left":"tamper with","right":"can thiệp, giả mạo"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l4-p5','b2-u07-l4','multiple_choice',5,'practice','medium',false,'{"question":"Bằng chứng nào cho thấy tên trộm có thể ra cửa sau?","options":[{"id":"a","text":"Dấu giày"},{"id":"b","text":"Vết sơn ở lối thoát hiểm"},{"id":"c","text":"Camera ghi lại"}],"correctOptionId":"b","explanationVi":"''traces of paint on a fire exit.''"}'::jsonb),
 ('b2-u07-l4-p6','b2-u07-l4','multiple_choice',6,'practice','medium',false,'{"question":"Cảnh sát tin gì về số lượng kẻ trộm?","options":[{"id":"a","text":"Chắc chắn chỉ một người"},{"id":"b","text":"Không thể chỉ một người"},{"id":"c","text":"Không có kết luận"}],"correctOptionId":"b","explanationVi":"''can''t have been carried out by one person alone.''"}'::jsonb),
 ('b2-u07-l4-p7','b2-u07-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành câu phê bình trong bài: ''He ought to ___ (stay) at his post.''","acceptedAnswers":["have stayed"],"explanationVi":"ought to have stayed = lẽ ra phải ở lại."}'::jsonb),
 ('b2-u07-l4-q1','b2-u07-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Modal nào được dùng để suy luận CHẮC CHẮN trong bài?","options":[{"id":"a","text":"might have"},{"id":"b","text":"must have"},{"id":"c","text":"could have"}],"correctOptionId":"b","explanationVi":"must have = gần như chắc chắn đã xảy ra."}'::jsonb),
 ('b2-u07-l4-q2','b2-u07-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Tung tích bức tranh hiện tại như thế nào?","options":[{"id":"a","text":"Đã tìm thấy"},{"id":"b","text":"Vẫn chưa biết"},{"id":"c","text":"Đã thu hồi"}],"correctOptionId":"b","explanationVi":"''Anyone with information on the whereabouts...should contact the authorities.'' — chưa tìm thấy."}'::jsonb),
 ('b2-u07-l4-q3','b2-u07-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Cấu trúc trong ''should have checked the cameras'' diễn đạt điều gì?","options":[{"id":"a","text":"Suy luận chắc chắn"},{"id":"b","text":"Phê bình việc không làm đúng"},{"id":"c","text":"Khả năng yếu"}],"correctOptionId":"b","explanationVi":"should have = phê bình người không thực hiện trách nhiệm."}'::jsonb),
 ('b2-u07-l4-q4','b2-u07-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''The thief ___ (know) the security code — that''s why no alarm went off.''","acceptedAnswers":["must have known"],"explanationVi":"Gần chắc đã biết: must have known."}'::jsonb),
 ('b2-u07-l4-q5','b2-u07-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Từ ''tamper with'' trong bài có nghĩa là?","options":[{"id":"a","text":"Sửa chữa đúng cách"},{"id":"b","text":"Can thiệp/giả mạo trái phép"},{"id":"c","text":"Lắp đặt mới"}],"correctOptionId":"b","explanationVi":"tamper with = can thiệp trái phép để phá hoại/gian lận."}'::jsonb),
 ('b2-u07-l4-q6','b2-u07-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"surveillance","right":"sự giám sát"},{"left":"whereabouts","right":"tung tích"},{"left":"retrieve","right":"tìm lại"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l4-q7','b2-u07-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Hoàn thành: ''The theft ___ (carry out) by one person — it was too complex.''","acceptedAnswers":["can''t have been carried out","couldn''t have been carried out"],"explanationVi":"can''t have been carried out = không thể chỉ một người."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u07-l5','B2','reading','b2-u07','unit_review',5,'Unit 7 Review','Ôn tập Unit 7: Suy luận & Phê bình',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 7: past deduction modals, should have và từ vựng điều tra.","objectives":["Tổng hợp can-do Unit 7","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u07-l5-q1','b2-u07-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Điền đúng (suy luận chắc): ''She ___ (leave) — her bag is gone.''","acceptedAnswers":["must have left"],"explanationVi":"Bằng chứng rõ → must have left."}'::jsonb),
 ('b2-u07-l5-q2','b2-u07-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Modal nào diễn đạt ''không thể đã xảy ra''?","options":[{"id":"a","text":"must have"},{"id":"b","text":"might have"},{"id":"c","text":"can''t have"}],"correctOptionId":"c","explanationVi":"can''t have = gần như chắc chắn không."}'::jsonb),
 ('b2-u07-l5-q3','b2-u07-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (phê bình đã làm điều không nên):","options":[{"id":"a","text":"You should have done that."},{"id":"b","text":"You shouldn''t have done that."},{"id":"c","text":"You needn''t have done that."}],"correctOptionId":"b","explanationVi":"Phê bình đã làm sai: shouldn''t have done."}'::jsonb),
 ('b2-u07-l5-q4','b2-u07-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Điền đúng: ''You ___ (prepare) more — the exam was really hard.''","acceptedAnswers":["should have prepared","ought to have prepared"],"explanationVi":"Lẽ ra nên chuẩn bị hơn: should/ought to have prepared."}'::jsonb),
 ('b2-u07-l5-q5','b2-u07-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Phân biệt: câu nào có nghĩa là ''đã làm nhưng không cần thiết''?","options":[{"id":"a","text":"I didn''t need to hurry."},{"id":"b","text":"I needn''t have hurried."},{"id":"c","text":"I should have hurried."}],"correctOptionId":"b","explanationVi":"needn''t have hurried = đã vội nhưng không cần."}'::jsonb),
 ('b2-u07-l5-q6','b2-u07-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"motive","right":"động cơ"},{"left":"acquit","right":"tuyên trắng án"},{"left":"forensic","right":"pháp y"},{"left":"tamper with","right":"can thiệp trái phép"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u07-l5-q7','b2-u07-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Điền đúng (khả năng yếu): ''He ___ (take) the wrong turn — he''s never been here before.''","acceptedAnswers":["might have taken","could have taken","may have taken"],"explanationVi":"Không chắc → might/could/may have taken."}'::jsonb),
 ('b2-u07-l5-q8','b2-u07-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["have","She","locked","the","should","door"],"correctOrder":[1,4,0,2,3,5],"explanationVi":"She should have locked the door."}'::jsonb),
 ('b2-u07-l5-q9','b2-u07-l5','multiple_choice',9,'quiz','medium',true,'{"question":"''She was at the gym when the robbery happened.'' → She ___ the shop.","options":[{"id":"a","text":"must have robbed"},{"id":"b","text":"might have robbed"},{"id":"c","text":"can''t have robbed"}],"correctOptionId":"c","explanationVi":"Có alibi → can''t have robbed."}'::jsonb),
 ('b2-u07-l5-q10','b2-u07-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Điền đúng (phê bình): ''The engineer ought ___ (test) the system before launch.''","acceptedAnswers":["to have tested"],"explanationVi":"ought TO have tested = lẽ ra phải kiểm tra."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u07-l5' WHERE id = 'b2-u07';
