-- ══════════════════════════════════════════════════════════════════════════
-- B2 Unit 08 — In Other Words
-- Reduced Relative Clauses; Advanced Relatives; Participle Clauses
-- ══════════════════════════════════════════════════════════════════════════

UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B2' AND id = 'b2-u08';
DELETE FROM learning_lesson_activities WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B2' AND unit_id = 'b2-u08');
DELETE FROM learning_lessons WHERE level_code = 'B2' AND unit_id = 'b2-u08';

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u08-l1','B2','reading','b2-u08','normal',1,'Relative Clauses: Defining & Non-defining','who/which/that/whose/where/when — ôn và nâng cao',12,25,70,'{}'::jsonb,
  '{"warmup":"''Người mà tôi gặp hôm qua...'' vs ''Anh Nam, người mà tôi gặp hôm qua...'' — Hai câu này khác nhau không? Tại sao?",
    "objectives":["Phân biệt defining (không có dấu phẩy) và non-defining (có dấu phẩy) relative clauses","Dùng đúng who/which/that/whose/where/when/whom","Nhận biết khi nào có thể bỏ relative pronoun"],
    "grammarHtml":"<b>Defining relative clause</b> (không dấu phẩy — thông tin cần thiết):<br><i>The book that I bought is fascinating.</i> (that = có thể bỏ khi là object)<br><i>The man who called is my uncle.</i> (who = không bỏ khi là subject)<br><b>Non-defining relative clause</b> (có dấu phẩy — thêm thông tin):<br><i>My sister, who lives in Hanoi, is a doctor.</i> (KHÔNG dùng that; KHÔNG bỏ who)<br><i>The report, which was published yesterday, shocked everyone.</i><br><b>Relative pronouns nâng cao:</b><br><b>whose</b> = sở hữu: <i>The student whose essay won the prize...</i><br><b>whom</b> = object, trang trọng: <i>The person whom I admire most...</i><br><b>whereby</b> = bằng cách mà, theo đó (trang trọng): <i>a system whereby payments are automated</i><br><b>wherein</b> = trong đó (trang trọng): <i>a situation wherein no solution exists</i><br><b>what</b> = the thing(s) that: <i>What surprised me was the result.</i>",
    "vocabBlock":[
      {"word":"whereby","ipa":"/weəˈbaɪ/","meaningVi":"bằng cách đó, theo đó","example":"A system whereby data is shared securely."},
      {"word":"in which","ipa":"/ɪn wɪtʃ/","meaningVi":"trong đó","example":"A world in which everyone is equal."},
      {"word":"whom","ipa":"/huːm/","meaningVi":"người mà (object, trang trọng)","example":"The director, whom I respect, resigned."},
      {"word":"whose","ipa":"/huːz/","meaningVi":"của người/vật mà","example":"The artist whose work inspired me."}],
    "examples":[
      {"en":"The scientist who discovered the vaccine won the Nobel Prize.","vi":"Nhà khoa học đã khám phá vắc-xin đã giành giải Nobel."},
      {"en":"Paris, which I visited last summer, is beautiful.","vi":"Paris, mà tôi thăm hè năm ngoái, rất đẹp."},
      {"en":"The company whose CEO resigned is now struggling.","vi":"Công ty mà CEO đã từ chức đang gặp khó khăn."},
      {"en":"This is the room where the agreement was signed.","vi":"Đây là căn phòng nơi thỏa thuận được ký kết."}],
    "commonMistakes":["Non-defining: KHÔNG dùng that → ✅ which/who.","Non-defining: KHÔNG bỏ relative pronoun.","whom = object (formal): The person whom I met / The person I met (informal)."],
    "tips":["Dấu phẩy = thêm thông tin (có thể bỏ câu vẫn đúng).","Không dấu phẩy = thông tin cần thiết để xác định.","whose dùng cho cả người và vật."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u08-l1-p1','b2-u08-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu NON-DEFINING ĐÚNG:","options":[{"id":"a","text":"My brother, that works in London, called me."},{"id":"b","text":"My brother, who works in London, called me."},{"id":"c","text":"My brother who works in London called me."}],"correctOptionId":"b","explanationVi":"Non-defining: dấu phẩy + who (không dùng that)."}'::jsonb),
 ('b2-u08-l1-p2','b2-u08-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''The student ___ essay won the prize received a scholarship.''","acceptedAnswers":["whose"],"explanationVi":"Sở hữu → whose."}'::jsonb),
 ('b2-u08-l1-p3','b2-u08-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"whereby","right":"bằng cách đó"},{"left":"whom","right":"người mà (object)"},{"left":"whose","right":"của người/vật mà"},{"left":"in which","right":"trong đó"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l1-p4','b2-u08-l1','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi (non-defining): ''The Eiffel Tower, that was built in 1889, is 330m tall.''","acceptedAnswers":["The Eiffel Tower, which was built in 1889, is 330m tall."],"explanationVi":"Non-defining: không dùng that → which."}'::jsonb),
 ('b2-u08-l1-p5','b2-u08-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Công ty mà CEO của nó đã từ chức đang gặp khó khăn.","acceptedAnswers":["The company whose CEO resigned is now struggling.","The company whose CEO left is struggling."],"explanationVi":"Sở hữu → whose CEO."}'::jsonb),
 ('b2-u08-l1-p6','b2-u08-l1','multiple_choice',6,'practice','medium',false,'{"question":"Relative pronoun nào có thể BỎ trong câu: ''The book (___) I read was amazing.''?","options":[{"id":"a","text":"who"},{"id":"b","text":"that/which"},{"id":"c","text":"whose"}],"correctOptionId":"b","explanationVi":"Object relative pronoun có thể bỏ trong defining clause: The book I read..."}'::jsonb),
 ('b2-u08-l1-p7','b2-u08-l1','grammar_fill_blank',7,'practice','medium',false,'{"question":"Điền đúng (trang trọng): ''The director, ___ I admire greatly, resigned today.''","acceptedAnswers":["whom"],"explanationVi":"Object + trang trọng → whom."}'::jsonb),
 ('b2-u08-l1-q1','b2-u08-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Câu nào là DEFINING relative clause?","options":[{"id":"a","text":"My car, which is red, needs a service."},{"id":"b","text":"The car that I bought is red."},{"id":"c","text":"London, where I grew up, is busy."}],"correctOptionId":"b","explanationVi":"Không dấu phẩy = defining."}'::jsonb),
 ('b2-u08-l1-q2','b2-u08-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''The city ___ I was born has changed a lot.''","acceptedAnswers":["where","in which"],"explanationVi":"Địa điểm → where / in which."}'::jsonb),
 ('b2-u08-l1-q3','b2-u08-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Non-defining clause — chọn câu ĐÚNG:","options":[{"id":"a","text":"Shakespeare, that wrote Hamlet, was born in 1564."},{"id":"b","text":"Shakespeare, who wrote Hamlet, was born in 1564."},{"id":"c","text":"Shakespeare who wrote Hamlet was born in 1564."}],"correctOptionId":"b","explanationVi":"Non-defining: dấu phẩy + who."}'::jsonb),
 ('b2-u08-l1-q4','b2-u08-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng: ''It''s a system ___ all data is encrypted before transfer.''","acceptedAnswers":["whereby","in which","where"],"explanationVi":"whereby/in which/where = trong đó / theo đó."}'::jsonb),
 ('b2-u08-l1-q5','b2-u08-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"whereby","right":"theo đó"},{"left":"whom","right":"người mà (object)"},{"left":"whose","right":"của người/vật"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l1-q6','b2-u08-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["won","The","scientist","discovered","who","vaccine","the","the","prize"],"correctOrder":[1,2,4,3,6,5,7,8,0],"explanationVi":"The scientist who discovered the vaccine won the prize."}'::jsonb),
 ('b2-u08-l1-q7','b2-u08-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền đúng: ''___ surprised me most was how quickly it happened.''","acceptedAnswers":["What"],"explanationVi":"What = the thing that — làm chủ ngữ."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u08-l2','B2','reading','b2-u08','normal',2,'Reduced Relative Clauses','Rút gọn mệnh đề quan hệ: V-ing / V3 / to-infinitive',12,25,70,'{}'::jsonb,
  '{"warmup":"''Người đang đứng ở cửa'' — có thể nói ngắn hơn không? ''The man standing at the door'' — bạn có nhận ra không?",
    "objectives":["Rút gọn relative clause bằng V-ing (active) và V3 (passive)","Rút gọn bằng to-infinitive (chỉ thứ nhất, duy nhất)","Phân biệt khi nào được rút gọn"],
    "grammarHtml":"<b>Rút gọn Relative Clause:</b><br><b>Active → V-ing:</b><br>The man who is standing at the door → The man standing at the door<br>The girl who was singing → The girl singing<br>Students who study hard → Students studying hard<br><b>Passive → V3 (past participle):</b><br>The book which was written by Tolstoy → The book written by Tolstoy<br>The bridge that is being repaired → The bridge being repaired<br><b>To-infinitive (first, only, last, superlative):</b><br>He was the first person who arrived → He was the first person to arrive<br>She is the only one who knows → She is the only one to know<br><b>Điều kiện rút gọn:</b><br>- Chỉ rút gọn được khi chủ ngữ của relative clause = antecedent<br>- Non-defining clause: có thể rút gọn nhưng ít phổ biến hơn",
    "vocabBlock":[
      {"word":"reduced clause","ipa":"/rɪˈdjuːst klɔːz/","meaningVi":"mệnh đề rút gọn","example":"A sentence with a reduced clause is more concise."},
      {"word":"antecedent","ipa":"/ˌæntɪˈsiːdənt/","meaningVi":"từ tiền thân (từ mà mệnh đề quan hệ bổ nghĩa)","example":"The noun that the clause modifies is the antecedent."},
      {"word":"concise","ipa":"/kənˈsaɪs/","meaningVi":"súc tích","example":"Academic writing should be concise."},
      {"word":"modify","ipa":"/ˈmɒdɪfaɪ/","meaningVi":"bổ nghĩa, chỉnh sửa","example":"Adjectives modify nouns."}],
    "examples":[
      {"en":"The students who are waiting outside are from Class B. → The students waiting outside are from Class B.","vi":"Những học sinh đang chờ bên ngoài → những học sinh chờ bên ngoài."},
      {"en":"The report that was submitted yesterday contains errors. → The report submitted yesterday contains errors.","vi":"Báo cáo được nộp hôm qua → báo cáo nộp hôm qua."},
      {"en":"Neil Armstrong was the first person who walked on the moon. → ...the first person to walk on the moon.","vi":"Neil Armstrong là người đầu tiên đặt chân lên mặt trăng."}],
    "commonMistakes":["❌ The stolen man (passive) khi active: The man stealing (đang ăn cắp) ≠ The man stolen (bị ăn cắp).","Không rút gọn khi chủ ngữ khác: The book that I wrote (tôi viết, không rút gọn thành the book writing).","to-infinitive chỉ sau: first, last, only, next, ordinal numbers, superlatives."],
    "tips":["V-ing = active; V3 = passive.","Sau first/last/only/superlative → to-infinitive.","Bỏ who/which/that + be → còn lại V-ing hoặc V3."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u08-l2-p1','b2-u08-l2','multiple_choice',1,'practice','easy',false,'{"question":"Rút gọn: ''The woman who is standing by the window'' →","options":[{"id":"a","text":"The woman stood by the window"},{"id":"b","text":"The woman standing by the window"},{"id":"c","text":"The woman to stand by the window"}],"correctOptionId":"b","explanationVi":"Active progressive → V-ing."}'::jsonb),
 ('b2-u08-l2-p2','b2-u08-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Rút gọn: ''The letter that was sent yesterday'' →","acceptedAnswers":["The letter sent yesterday"],"explanationVi":"Passive → V3: sent."}'::jsonb),
 ('b2-u08-l2-p3','b2-u08-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"concise","right":"súc tích"},{"left":"modify","right":"bổ nghĩa"},{"left":"antecedent","right":"từ tiền thân"},{"left":"reduced clause","right":"mệnh đề rút gọn"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l2-p4','b2-u08-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Rút gọn: ''She was the last person who left the office.'' →","acceptedAnswers":["She was the last person to leave the office."],"explanationVi":"last + to-infinitive."}'::jsonb),
 ('b2-u08-l2-p5','b2-u08-l2','translation',5,'practice','medium',false,'{"question":"Dịch dùng reduced clause: ''Những sinh viên đang học trong thư viện rất chăm chỉ.''","acceptedAnswers":["The students studying in the library are very hardworking.","Students studying in the library are very diligent."],"explanationVi":"who are studying → studying."}'::jsonb),
 ('b2-u08-l2-p6','b2-u08-l2','multiple_choice',6,'practice','medium',false,'{"question":"''The documents destroyed in the fire'' — V3 ở đây là?","options":[{"id":"a","text":"Active"},{"id":"b","text":"Passive"},{"id":"c","text":"To-infinitive"}],"correctOptionId":"b","explanationVi":"destroyed = past participle = passive reduced clause."}'::jsonb),
 ('b2-u08-l2-p7','b2-u08-l2','error_correction',7,'practice','medium',false,'{"question":"Sửa lỗi: ''She is the only student knowing the answer.''","acceptedAnswers":["She is the only student to know the answer."],"explanationVi":"only → to-infinitive."}'::jsonb),
 ('b2-u08-l2-q1','b2-u08-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Rút gọn: ''The car that was parked outside'' →","options":[{"id":"a","text":"The car parking outside"},{"id":"b","text":"The car parked outside"},{"id":"c","text":"The car to park outside"}],"correctOptionId":"b","explanationVi":"Passive → V3: parked."}'::jsonb),
 ('b2-u08-l2-q2','b2-u08-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Rút gọn: ''The children who are playing in the park'' →","acceptedAnswers":["The children playing in the park"],"explanationVi":"Active → V-ing: playing."}'::jsonb),
 ('b2-u08-l2-q3','b2-u08-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Sau từ ''first'' nên dùng dạng rút gọn nào?","options":[{"id":"a","text":"V-ing"},{"id":"b","text":"V3"},{"id":"c","text":"to-infinitive"}],"correctOptionId":"c","explanationVi":"first/last/only + to-infinitive."}'::jsonb),
 ('b2-u08-l2-q4','b2-u08-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Rút gọn: ''He was the first astronaut who walked on the moon.'' →","acceptedAnswers":["He was the first astronaut to walk on the moon."],"explanationVi":"first + to walk."}'::jsonb),
 ('b2-u08-l2-q5','b2-u08-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"concise","right":"súc tích"},{"left":"modify","right":"bổ nghĩa"},{"left":"antecedent","right":"từ tiền thân"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l2-q6','b2-u08-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu rút gọn đúng:","tokens":["report","The","contains","submitted","yesterday","errors"],"correctOrder":[1,0,3,4,2,5],"explanationVi":"The report submitted yesterday contains errors."}'::jsonb),
 ('b2-u08-l2-q7','b2-u08-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Rút gọn: ''Anyone who wants to apply should contact HR.'' →","acceptedAnswers":["Anyone wanting to apply should contact HR."],"explanationVi":"who wants → wanting."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u08-l3','B2','reading','b2-u08','normal',3,'Participle Clauses','V-ing / V3 / having + V3 — mệnh đề phân từ',12,25,70,'{}'::jsonb,
  '{"warmup":"''Sau khi hoàn thành bài luận, tôi đi ngủ.'' — Tiếng Anh có thể viết ngắn hơn: ''Having finished the essay, I went to bed.'' Bạn có nhận ra cấu trúc này không?",
    "objectives":["Dùng V-ing clause để nói về hành động đồng thời hoặc nguyên nhân","Dùng having + V3 để nói về hành động xảy ra trước","Dùng V3 (past participle) clause cho nghĩa bị động rút gọn"],
    "grammarHtml":"<b>Participle Clauses:</b><br><b>1. V-ing clause (present participle):</b><br>Đồng thời: <i>Walking down the street, she noticed a bookshop.</i><br>Nguyên nhân: <i>Not knowing the answer, he stayed silent.</i><br>Kết quả: <i>She studied hard, achieving top marks.</i><br><b>2. Having + V3 (perfect participle):</b><br>Hành động xảy ra TRƯỚC mệnh đề chính:<br><i>Having finished the report, she sent it to her manager.</i><br><i>Having been rejected twice, he tried a different approach.</i><br><b>3. V3 clause (past participle — passive meaning):</b><br><i>Exhausted by the journey, they fell asleep immediately.</i><br><i>Written in 1850, the novel is still relevant today.</i><br><b>Quy tắc quan trọng:</b> Chủ ngữ của participle clause PHẢI giống chủ ngữ của mệnh đề chính (dangling participle là lỗi).",
    "vocabBlock":[
      {"word":"participle","ipa":"/ˈpɑːtɪsɪpl/","meaningVi":"phân từ","example":"''Running'' and ''broken'' are participles."},
      {"word":"simultaneous","ipa":"/ˌsɪmlˈteɪniəs/","meaningVi":"đồng thời","example":"Two simultaneous events happened."},
      {"word":"preceded by","ipa":"/prɪˈsiːdɪd baɪ/","meaningVi":"trước đó có","example":"Having V3 is preceded by an earlier action."},
      {"word":"dangling participle","ipa":"/ˈdæŋɡlɪŋ ˈpɑːtɪsɪpl/","meaningVi":"phân từ lơ lửng (lỗi)","example":"Walking down the road, the trees were beautiful. (WRONG)"}],
    "examples":[
      {"en":"Feeling tired, she decided to cancel the meeting.","vi":"Cảm thấy mệt, cô ấy quyết định huỷ cuộc họp."},
      {"en":"Having saved enough money, they booked a trip to Europe.","vi":"Sau khi tiết kiệm đủ tiền, họ đặt chuyến đi đến châu Âu."},
      {"en":"Surprised by the question, he paused before answering.","vi":"Bị bất ngờ bởi câu hỏi, anh ấy dừng lại trước khi trả lời."},
      {"en":"Not knowing what to do, she asked for advice.","vi":"Không biết phải làm gì, cô ấy xin lời khuyên."}],
    "commonMistakes":["Dangling participle: ❌ Walking down the road, the trees were beautiful. (cây không đi) → ✅ Walking down the road, I admired the trees.","Having + V3 ≠ V-ing: having finished (xong trước) ≠ finishing (đồng thời/nguyên nhân).","Not + V-ing: Not knowing = vì không biết."],
    "tips":["V-ing clause = chủ ngữ giống mệnh đề chính, hành động đồng thời hoặc nguyên nhân.","Having + V3 = hành động xong TRƯỚC mệnh đề chính.","V3 at start = passive meaning: Exhausted... / Written..."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u08-l3-p1','b2-u08-l3','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG (hành động xảy ra TRƯỚC):","options":[{"id":"a","text":"Finishing the report, she sent it."},{"id":"b","text":"Having finished the report, she sent it."},{"id":"c","text":"Finished the report, she sent it."}],"correctOptionId":"b","explanationVi":"Hành động trước → having + V3."}'::jsonb),
 ('b2-u08-l3-p2','b2-u08-l3','grammar_fill_blank',2,'practice','easy',false,'{"question":"Rút gọn: ''Because she didn''t know the way, she asked for help.'' →","acceptedAnswers":["Not knowing the way, she asked for help."],"explanationVi":"Nguyên nhân → V-ing clause. Phủ định → Not knowing."}'::jsonb),
 ('b2-u08-l3-p3','b2-u08-l3','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"participle","right":"phân từ"},{"left":"simultaneous","right":"đồng thời"},{"left":"dangling participle","right":"phân từ lơ lửng (lỗi)"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l3-p4','b2-u08-l3','grammar_fill_blank',4,'practice','medium',false,'{"question":"Rút gọn: ''After they had saved enough money, they bought a house.'' →","acceptedAnswers":["Having saved enough money, they bought a house."],"explanationVi":"Trước → having saved."}'::jsonb),
 ('b2-u08-l3-p5','b2-u08-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh dùng participle clause:","sourceText":"Cảm thấy mệt, anh ấy quyết định về sớm.","acceptedAnswers":["Feeling tired, he decided to leave early.","Feeling exhausted, he decided to go home early."],"explanationVi":"Feeling tired, + mệnh đề chính."}'::jsonb),
 ('b2-u08-l3-p6','b2-u08-l3','multiple_choice',6,'practice','medium',false,'{"question":"Câu nào là DANGLING PARTICIPLE (lỗi)?","options":[{"id":"a","text":"Walking home, I saw a rainbow."},{"id":"b","text":"Walking home, a rainbow appeared."},{"id":"c","text":"Having walked home, I made tea."}],"correctOptionId":"b","explanationVi":"Cầu vồng không đi bộ về nhà → dangling participle."}'::jsonb),
 ('b2-u08-l3-p7','b2-u08-l3','grammar_fill_blank',7,'practice','medium',false,'{"question":"Điền đúng: ''___ (write) in 1984, the novel predicts a dystopian society.''","acceptedAnswers":["Written"],"explanationVi":"Passive meaning → V3: Written."}'::jsonb),
 ('b2-u08-l3-q1','b2-u08-l3','multiple_choice',8,'quiz','easy',true,'{"question":"Participle clause nào diễn đạt hành động xảy ra TRƯỚC?","options":[{"id":"a","text":"Seeing the news, she cried."},{"id":"b","text":"Having seen the news, she cried."},{"id":"c","text":"Seen the news, she cried."}],"correctOptionId":"b","explanationVi":"Having + V3 = trước mệnh đề chính."}'::jsonb),
 ('b2-u08-l3-q2','b2-u08-l3','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Rút gọn: ''Because he was exhausted by the journey, he fell asleep.'' →","acceptedAnswers":["Exhausted by the journey, he fell asleep."],"explanationVi":"Passive cause → V3 clause."}'::jsonb),
 ('b2-u08-l3-q3','b2-u08-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Câu nào ĐÚNG?","options":[{"id":"a","text":"Not knowing the answer, the question was left blank."},{"id":"b","text":"Not knowing the answer, she left it blank."},{"id":"c","text":"Not know the answer, she left it blank."}],"correctOptionId":"b","explanationVi":"Chủ ngữ phải giống: she là người không biết."}'::jsonb),
 ('b2-u08-l3-q4','b2-u08-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Rút gọn: ''After she had been rejected twice, she tried again.'' →","acceptedAnswers":["Having been rejected twice, she tried again."],"explanationVi":"Passive + trước → Having been rejected."}'::jsonb),
 ('b2-u08-l3-q5','b2-u08-l3','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"simultaneous","right":"đồng thời"},{"left":"participle","right":"phân từ"},{"left":"preceded by","right":"trước đó có"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l3-q6','b2-u08-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["Having","the","she","report","sent","finished","it"],"correctOrder":[0,3,1,5,2,4,6],"explanationVi":"Having finished the report, she sent it."}'::jsonb),
 ('b2-u08-l3-q7','b2-u08-l3','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Rút gọn: ''While she was listening to music, she did her homework.'' →","acceptedAnswers":["Listening to music, she did her homework."],"explanationVi":"Đồng thời → V-ing clause."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u08-l4','B2','reading','b2-u08','normal',4,'Language & Communication','Đọc hiểu: Ngôn ngữ & giao tiếp',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc bài viết về ngôn ngữ học và chú ý các mệnh đề quan hệ và phân từ được dùng.",
    "objectives":["Đọc hiểu văn bản B2 về ngôn ngữ","Nhận biết relative clauses, reduced clauses và participle clauses trong ngữ cảnh","Trả lời câu hỏi suy luận"],
    "vocabBlock":[
      {"word":"linguist","ipa":"/ˈlɪŋɡwɪst/","meaningVi":"nhà ngôn ngữ học","example":"The linguist studied endangered languages."},
      {"word":"dialect","ipa":"/ˈdaɪəlekt/","meaningVi":"phương ngữ","example":"Regional dialects vary greatly."},
      {"word":"extinct","ipa":"/ɪkˈstɪŋkt/","meaningVi":"tuyệt chủng, không còn tồn tại","example":"Many languages are now extinct."},
      {"word":"evolve","ipa":"/ɪˈvɒlv/","meaningVi":"tiến hóa, phát triển","example":"Language evolves constantly."}],
    "examples":[
      {"en":"Language, which has been studied for thousands of years, remains one of the most complex phenomena known to science. Linguists studying endangered languages are working to preserve dialects that have been spoken for centuries but are now facing extinction. Having documented fewer than a hundred speakers, researchers worry that some languages will disappear within a generation. The last known speaker of a language whose grammar contained no written form died in 2014, taking centuries of oral history with her. Languages evolving naturally often borrow words from neighbouring cultures, creating rich, layered vocabularies. Understanding how people communicate — and what drives language change — requires examining not just words, but the social structures shaping them.","vi":"Ngôn ngữ, đã được nghiên cứu hàng ngàn năm, vẫn là một trong những hiện tượng phức tạp nhất được khoa học biết đến. Các nhà ngôn ngữ học nghiên cứu các ngôn ngữ có nguy cơ biến mất đang cố bảo tồn các phương ngữ đã được nói trong nhiều thế kỷ nhưng hiện đang đối mặt với sự tuyệt chủng. Sau khi ghi chép ít hơn một trăm người nói, các nhà nghiên cứu lo ngại một số ngôn ngữ sẽ biến mất trong vòng một thế hệ. Người nói cuối cùng được biết đến của một ngôn ngữ không có dạng viết qua đời năm 2014, mang theo hàng thế kỷ lịch sử truyền miệng. Các ngôn ngữ phát triển tự nhiên thường vay mượn từ từ các nền văn hóa lân cận, tạo ra vốn từ vựng phong phú. Hiểu cách con người giao tiếp đòi hỏi xem xét không chỉ từ ngữ mà còn cả cấu trúc xã hội định hình chúng."}],
    "commonMistakes":["Để ý: ''Linguists studying'' (reduced clause) và ''having documented'' (participle) và ''whose grammar'' (relative clause)."],
    "tips":["Đọc kỹ tìm các dạng rút gọn trong văn bản học thuật.","Academic texts thường dùng reduced clauses và participle clauses để súc tích."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u08-l4-p1','b2-u08-l4','multiple_choice',1,'practice','easy',false,'{"question":"Theo bài, các nhà ngôn ngữ học đang làm gì?","options":[{"id":"a","text":"Tạo ngôn ngữ mới"},{"id":"b","text":"Bảo tồn các phương ngữ có nguy cơ tuyệt chủng"},{"id":"c","text":"Dịch văn bản cổ đại"}],"correctOptionId":"b","explanationVi":"''working to preserve dialects...facing extinction.''"}'::jsonb),
 ('b2-u08-l4-p2','b2-u08-l4','multiple_choice',2,'practice','easy',false,'{"question":"Người nói cuối cùng của ngôn ngữ không có dạng viết mất năm nào?","options":[{"id":"a","text":"2004"},{"id":"b","text":"2014"},{"id":"c","text":"2024"}],"correctOptionId":"b","explanationVi":"''died in 2014.''"}'::jsonb),
 ('b2-u08-l4-p3','b2-u08-l4','multiple_choice',3,'practice','medium',false,'{"question":"Cấu trúc nào trong ''Linguists studying endangered languages''?","options":[{"id":"a","text":"Participle clause (having + V3)"},{"id":"b","text":"Reduced relative clause (V-ing)"},{"id":"c","text":"Non-defining relative clause"}],"correctOptionId":"b","explanationVi":"who are studying → studying = reduced relative clause."}'::jsonb),
 ('b2-u08-l4-p4','b2-u08-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"linguist","right":"nhà ngôn ngữ học"},{"left":"dialect","right":"phương ngữ"},{"left":"extinct","right":"tuyệt chủng"},{"left":"evolve","right":"tiến hóa"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l4-p5','b2-u08-l4','multiple_choice',5,'practice','medium',false,'{"question":"''Having documented fewer than a hundred speakers'' — cấu trúc này diễn đạt điều gì?","options":[{"id":"a","text":"Hành động đồng thời với mệnh đề chính"},{"id":"b","text":"Hành động xảy ra trước mệnh đề chính"},{"id":"c","text":"Hành động bị động"}],"correctOptionId":"b","explanationVi":"Having + V3 = xảy ra trước lo ngại của các nhà nghiên cứu."}'::jsonb),
 ('b2-u08-l4-p6','b2-u08-l4','multiple_choice',6,'practice','medium',false,'{"question":"Ngôn ngữ vay mượn từ ở đâu theo bài?","options":[{"id":"a","text":"Các nền văn hóa lân cận"},{"id":"b","text":"Các ngôn ngữ cổ đại"},{"id":"c","text":"Tài liệu khoa học"}],"correctOptionId":"a","explanationVi":"''borrow words from neighbouring cultures.''"}'::jsonb),
 ('b2-u08-l4-p7','b2-u08-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Trong bài, ''a language whose grammar contained no written form'' — ''whose'' thay thế cho gì?","acceptedAnswers":["the language''s"],"explanationVi":"whose = sở hữu của language."}'::jsonb),
 ('b2-u08-l4-q1','b2-u08-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Theo bài, ngôn ngữ phát triển như thế nào?","options":[{"id":"a","text":"Theo quy định của chính phủ"},{"id":"b","text":"Tự nhiên, vay mượn từ văn hóa lân cận"},{"id":"c","text":"Chỉ trong môi trường học thuật"}],"correctOptionId":"b","explanationVi":"''Languages evolving naturally often borrow words from neighbouring cultures.''"}'::jsonb),
 ('b2-u08-l4-q2','b2-u08-l4','multiple_choice',9,'quiz','easy',true,'{"question":"''Language, which has been studied for thousands of years'' — đây là loại mệnh đề quan hệ nào?","options":[{"id":"a","text":"Defining"},{"id":"b","text":"Non-defining"},{"id":"c","text":"Reduced"}],"correctOptionId":"b","explanationVi":"Dấu phẩy + thêm thông tin = non-defining."}'::jsonb),
 ('b2-u08-l4-q3','b2-u08-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Từ ''extinct'' trong bài có nghĩa là?","options":[{"id":"a","text":"Rất hiếm"},{"id":"b","text":"Không còn tồn tại"},{"id":"c","text":"Đang phát triển"}],"correctOptionId":"b","explanationVi":"extinct = đã biến mất hoàn toàn."}'::jsonb),
 ('b2-u08-l4-q4','b2-u08-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Rút gọn từ bài: ''dialects that have been spoken for centuries'' →","acceptedAnswers":["dialects spoken for centuries"],"explanationVi":"Passive → V3: spoken."}'::jsonb),
 ('b2-u08-l4-q5','b2-u08-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Hiểu ngôn ngữ đòi hỏi xem xét điều gì theo bài?","options":[{"id":"a","text":"Chỉ từ ngữ"},{"id":"b","text":"Cả từ ngữ lẫn cấu trúc xã hội"},{"id":"c","text":"Chỉ ngữ pháp"}],"correctOptionId":"b","explanationVi":"''examining not just words, but the social structures shaping them.''"}'::jsonb),
 ('b2-u08-l4-q6','b2-u08-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"linguist","right":"nhà ngôn ngữ học"},{"left":"evolve","right":"tiến hóa"},{"left":"dialect","right":"phương ngữ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l4-q7','b2-u08-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Cấu trúc ''the social structures shaping them'' — rút gọn từ?","acceptedAnswers":["the social structures that shape them","the social structures which shape them"],"explanationVi":"Active → V-ing: shaping."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u08-l5','B2','reading','b2-u08','unit_review',5,'Unit 8 Review','Ôn tập Unit 8: Nói cách khác',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 8: relative clauses, reduced clauses và participle clauses.","objectives":["Tổng hợp can-do Unit 8","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u08-l5-q1','b2-u08-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Điền đúng: ''The scientist ___ discovered the cure won a prize.''","acceptedAnswers":["who"],"explanationVi":"Defining relative clause: who."}'::jsonb),
 ('b2-u08-l5-q2','b2-u08-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Rút gọn: ''The woman who is sitting at the desk'' →","options":[{"id":"a","text":"The woman sat at the desk"},{"id":"b","text":"The woman sitting at the desk"},{"id":"c","text":"The woman to sit at the desk"}],"correctOptionId":"b","explanationVi":"Active → V-ing."}'::jsonb),
 ('b2-u08-l5-q3','b2-u08-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Non-defining clause — chọn câu ĐÚNG:","options":[{"id":"a","text":"My father, that is a doctor, lives in Hue."},{"id":"b","text":"My father, who is a doctor, lives in Hue."},{"id":"c","text":"My father who is a doctor lives in Hue."}],"correctOptionId":"b","explanationVi":"Non-defining: dấu phẩy + who (không that)."}'::jsonb),
 ('b2-u08-l5-q4','b2-u08-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"Rút gọn: ''After she had read the report, she made a decision.'' →","acceptedAnswers":["Having read the report, she made a decision."],"explanationVi":"Trước → Having read."}'::jsonb),
 ('b2-u08-l5-q5','b2-u08-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào là dangling participle (lỗi)?","options":[{"id":"a","text":"Feeling hungry, she ordered pizza."},{"id":"b","text":"Feeling hungry, the pizza was ordered."},{"id":"c","text":"Having eaten, she felt better."}],"correctOptionId":"b","explanationVi":"Pizza không cảm thấy đói → dangling."}'::jsonb),
 ('b2-u08-l5-q6','b2-u08-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"whereby","right":"theo đó"},{"left":"concise","right":"súc tích"},{"left":"extinct","right":"tuyệt chủng"},{"left":"evolve","right":"tiến hóa"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u08-l5-q7','b2-u08-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Rút gọn passive: ''The letter that was found in the attic'' →","acceptedAnswers":["The letter found in the attic"],"explanationVi":"Passive → V3: found."}'::jsonb),
 ('b2-u08-l5-q8','b2-u08-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["tired","Feeling","cancelled","she","the","meeting"],"correctOrder":[1,0,2,3,4,5],"explanationVi":"Feeling tired, she cancelled the meeting."}'::jsonb),
 ('b2-u08-l5-q9','b2-u08-l5','multiple_choice',9,'quiz','medium',true,'{"question":"Sau ''first/last/only'' nên dùng dạng rút gọn nào?","options":[{"id":"a","text":"V-ing"},{"id":"b","text":"V3"},{"id":"c","text":"to-infinitive"}],"correctOptionId":"c","explanationVi":"first/last/only + to-infinitive."}'::jsonb),
 ('b2-u08-l5-q10','b2-u08-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Điền đúng (relative): ''It''s a process ___ results are automatically recorded.''","acceptedAnswers":["whereby","in which","where"],"explanationVi":"whereby/in which/where = trong đó."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u08-l5' WHERE id = 'b2-u08';
