-- ══════════════════════════════════════════════════════════════════════════
-- B2 Unit 09 — Building an Argument
-- Discourse Connectors; Concession/Contrast; Emphasis/Cleft Sentences
-- ══════════════════════════════════════════════════════════════════════════

UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B2' AND id = 'b2-u09';
DELETE FROM learning_lesson_activities WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B2' AND unit_id = 'b2-u09');
DELETE FROM learning_lessons WHERE level_code = 'B2' AND unit_id = 'b2-u09';

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u09-l1','B2','reading','b2-u09','normal',1,'Discourse Connectors','Liên kết văn bản: thêm / đối lập / nhân quả / minh hoạ',12,25,70,'{}'::jsonb,
  '{"warmup":"Khi viết đoạn văn, bạn dùng những từ gì để nối ý? ''Ngoài ra'', ''Tuy nhiên'', ''Do đó''... Bạn biết những từ tương đương trong tiếng Anh không?",
    "objectives":["Dùng đúng discourse connectors theo chức năng (thêm, đối lập, nhân quả, minh hoạ, tóm tắt)","Phân biệt từ dùng đầu câu vs giữa câu","Tránh lạm dụng however/furthermore"],
    "grammarHtml":"<b>Discourse Connectors theo chức năng:</b><br><b>Thêm (Addition):</b> furthermore, moreover, in addition, besides, what is more, not only...but also<br><b>Đối lập (Contrast):</b> however, nevertheless, nonetheless, on the other hand, in contrast, yet<br><b>Nhân quả (Cause/Result):</b> therefore, consequently, as a result, hence, thus, for this reason<br><b>Minh hoạ (Illustration):</b> for instance, for example, such as, namely, in particular<br><b>Điều kiện (Condition):</b> provided that, unless, as long as<br><b>Tóm tắt (Summary):</b> in conclusion, to sum up, overall, in short, in brief<br><b>Lưu ý vị trí:</b><br>Đầu câu (+ dấu phẩy): However, the results were different.<br>Giữa câu: The results, however, were different.<br>therefore / thus / hence: thường đầu mệnh đề, sau dấu chấm phẩy: <i>It was raining; therefore, we stayed inside.</i>",
    "vocabBlock":[
      {"word":"furthermore","ipa":"/ˈfɜːðəmɔː/","meaningVi":"hơn nữa (trang trọng)","example":"Furthermore, the evidence supports our claim."},
      {"word":"nevertheless","ipa":"/ˌnevəðəˈles/","meaningVi":"tuy nhiên, dù vậy","example":"It was risky; nevertheless, they proceeded."},
      {"word":"consequently","ipa":"/ˈkɒnsɪkwəntli/","meaningVi":"do đó, vì vậy","example":"She worked hard; consequently, she succeeded."},
      {"word":"nonetheless","ipa":"/ˌnʌnðəˈles/","meaningVi":"tuy thế, vẫn vậy","example":"It was difficult; nonetheless, he finished."},
      {"word":"hence","ipa":"/hens/","meaningVi":"do đó, vì thế (trang trọng)","example":"The data was incomplete; hence, the conclusions are limited."}],
    "examples":[
      {"en":"The new policy reduced costs. Furthermore, it improved efficiency.","vi":"Chính sách mới giảm chi phí. Hơn nữa, nó cải thiện hiệu quả."},
      {"en":"The experiment failed. Nevertheless, the team learned valuable lessons.","vi":"Thí nghiệm thất bại. Tuy nhiên, nhóm đã học được bài học quý giá."},
      {"en":"Sales dropped significantly; consequently, staff were made redundant.","vi":"Doanh số giảm mạnh; do đó, nhân viên bị cắt giảm."},
      {"en":"Many students struggle with grammar; for instance, they often confuse tenses.","vi":"Nhiều học sinh gặp khó khăn về ngữ pháp; chẳng hạn, họ thường nhầm thì."}],
    "commonMistakes":["❌ However I agree... → ✅ However, I agree... (cần dấu phẩy)","moreover / furthermore = trang trọng hơn also/and.","therefore / consequently / hence: đều chỉ kết quả nhưng mức độ trang trọng khác nhau."],
    "tips":["furthermore/moreover: thêm điểm QUAN TRỌNG HƠN.","nevertheless/nonetheless: đối lập — dù vậy.","hence/thus: rất trang trọng, chủ yếu viết học thuật."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u09-l1-p1','b2-u09-l1','multiple_choice',1,'practice','easy',false,'{"question":"Điền connector đúng (nhân quả): ''The project was underfunded; ___, it failed.''","options":[{"id":"a","text":"furthermore"},{"id":"b","text":"consequently"},{"id":"c","text":"nevertheless"}],"correctOptionId":"b","explanationVi":"Kết quả → consequently."}'::jsonb),
 ('b2-u09-l1-p2','b2-u09-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền connector đúng (thêm): ''The plan is cost-effective. ___, it is environmentally friendly.''","acceptedAnswers":["Furthermore","Moreover","In addition","What is more"],"explanationVi":"Thêm điểm tích cực → furthermore/moreover."}'::jsonb),
 ('b2-u09-l1-p3','b2-u09-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với chức năng:","pairs":[{"left":"furthermore","right":"thêm"},{"left":"nevertheless","right":"đối lập"},{"left":"consequently","right":"kết quả"},{"left":"for instance","right":"minh hoạ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l1-p4','b2-u09-l1','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''However the results were disappointing, the team continued.''","acceptedAnswers":["However, the results were disappointing, but the team continued.","The results were disappointing; however, the team continued.","The results were, however, disappointing, but the team continued."],"explanationVi":"however cần dấu phẩy sau + không nối hai mệnh đề như although."}'::jsonb),
 ('b2-u09-l1-p5','b2-u09-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Chính sách mới giảm chi phí. Hơn nữa, nó cải thiện năng suất.","acceptedAnswers":["The new policy reduced costs. Furthermore, it improved productivity.","The new policy cut costs. Moreover, it boosted productivity."],"explanationVi":"Furthermore / Moreover = hơn nữa."}'::jsonb),
 ('b2-u09-l1-p6','b2-u09-l1','multiple_choice',6,'practice','medium',false,'{"question":"Chức năng của ''namely'' là?","options":[{"id":"a","text":"Thêm ý"},{"id":"b","text":"Minh hoạ/liệt kê cụ thể"},{"id":"c","text":"Nhân quả"}],"correctOptionId":"b","explanationVi":"namely = cụ thể là (minh hoạ chính xác)."}'::jsonb),
 ('b2-u09-l1-p7','b2-u09-l1','grammar_fill_blank',7,'practice','medium',false,'{"question":"Điền connector đúng (đối lập): ''The treatment is expensive. ___, it is highly effective.''","acceptedAnswers":["Nevertheless","Nonetheless","However","Yet"],"explanationVi":"Đối lập: dù đắt → vẫn hiệu quả."}'::jsonb),
 ('b2-u09-l1-q1','b2-u09-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Connector nào chỉ KẾT QUẢ?","options":[{"id":"a","text":"furthermore"},{"id":"b","text":"consequently"},{"id":"c","text":"nonetheless"}],"correctOptionId":"b","explanationVi":"consequently = do đó (kết quả)."}'::jsonb),
 ('b2-u09-l1-q2','b2-u09-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền connector đúng (trang trọng, kết quả): ''The data was flawed; ___, the conclusions are unreliable.''","acceptedAnswers":["hence","therefore","consequently","thus"],"explanationVi":"hence/therefore/consequently/thus = do đó."}'::jsonb),
 ('b2-u09-l1-q3','b2-u09-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Connector nào dùng để giới thiệu ví dụ cụ thể?","options":[{"id":"a","text":"moreover"},{"id":"b","text":"for instance"},{"id":"c","text":"nevertheless"}],"correctOptionId":"b","explanationVi":"for instance = chẳng hạn (minh hoạ)."}'::jsonb),
 ('b2-u09-l1-q4','b2-u09-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng (tóm kết): ''___, the study shows that regular exercise improves mental health.''","acceptedAnswers":["In conclusion","To sum up","Overall","In short"],"explanationVi":"Tóm kết → In conclusion/To sum up."}'::jsonb),
 ('b2-u09-l1-q5','b2-u09-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"furthermore","right":"hơn nữa"},{"left":"nevertheless","right":"tuy nhiên"},{"left":"hence","right":"do đó (trang trọng)"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l1-q6','b2-u09-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["the","results","were","Furthermore","promising","initial"],"correctOrder":[3,0,1,2,4,5],"explanationVi":"Furthermore, the initial results were promising."}'::jsonb),
 ('b2-u09-l1-q7','b2-u09-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền connector phù hợp nhất (đối lập, trang trọng): ''The evidence was weak. ___, the jury convicted him.''","acceptedAnswers":["Nevertheless","Nonetheless","However","Yet"],"explanationVi":"Đối lập: dù bằng chứng yếu → vẫn kết tội."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u09-l2','B2','reading','b2-u09','normal',2,'Concession & Contrast','although / even though / despite / in spite of / while / whereas',12,25,70,'{}'::jsonb,
  '{"warmup":"''Mặc dù trời mưa, tôi vẫn đi.'' — Bạn có thể nói câu này bao nhiêu cách? although / despite / in spite of / even though / while...",
    "objectives":["Dùng although, even though, though để nối mệnh đề nhượng bộ","Dùng despite, in spite of + noun/V-ing","Phân biệt while/whereas (đối lập trực tiếp) vs although (nhượng bộ)"],
    "grammarHtml":"<b>Concession & Contrast:</b><br><b>although / even though / though + clause:</b><br><i>Although it was expensive, she bought it.</i> (even though = nhấn mạnh hơn; though = thông thường)<br><i>Though tired, she kept working.</i> (rút gọn — though đứng sau tính từ/phó từ)<br><b>despite / in spite of + noun / V-ing / the fact that:</b><br><i>Despite the rain, they played. (= Despite raining → sai; Despite the rain ✓)</i><br><i>In spite of being tired, she kept working.</i><br><i>Despite the fact that it was raining, they played.</i><br><b>while / whereas (đối lập song song):</b><br><i>While Tom is outgoing, his sister is shy.</i><br><i>Prices rose, whereas wages stayed the same.</i><br><b>Phân biệt:</b><br>although = nhượng bộ (unexpected contrast)<br>while/whereas = đối lập (two different but parallel facts)",
    "vocabBlock":[
      {"word":"despite","ipa":"/dɪˈspaɪt/","meaningVi":"mặc dù (+ danh từ/V-ing)","example":"Despite the difficulties, she succeeded."},
      {"word":"in spite of","ipa":"/ɪn spaɪt əv/","meaningVi":"mặc dù (= despite)","example":"In spite of the rain, we went out."},
      {"word":"whereas","ipa":"/weərˈæz/","meaningVi":"trong khi đó (đối lập)","example":"He likes tea, whereas she prefers coffee."},
      {"word":"nonetheless","ipa":"/ˌnʌnðəˈles/","meaningVi":"tuy vậy","example":"It was hard; nonetheless, she succeeded."},
      {"word":"concession","ipa":"/kənˈseʃn/","meaningVi":"sự nhượng bộ (ngữ pháp)","example":"''Although'' introduces a concession clause."}],
    "examples":[
      {"en":"Although the project took longer than expected, the results were excellent.","vi":"Mặc dù dự án mất nhiều thời gian hơn dự kiến, kết quả rất xuất sắc."},
      {"en":"Despite working long hours, she maintained a positive attitude.","vi":"Mặc dù làm việc nhiều giờ, cô ấy vẫn giữ thái độ tích cực."},
      {"en":"Western countries consume far more energy per capita, whereas developing nations use considerably less.","vi":"Các nước phương Tây tiêu thụ nhiều năng lượng hơn nhiều, trong khi các nước đang phát triển dùng ít hơn nhiều."},
      {"en":"In spite of the fact that funding was cut, the research continued.","vi":"Mặc dù tài trợ bị cắt, nghiên cứu vẫn tiếp tục."}],
    "commonMistakes":["❌ Despite it was raining → ✅ Despite the rain / Despite the fact that it was raining","❌ In spite of she was tired → ✅ In spite of being tired / In spite of her tiredness","although + clause; despite/in spite of + noun/V-ing (không dùng với clause trực tiếp)"],
    "tips":["despite/in spite of = giống nhau, + noun/V-ing.","although/even though = + full clause.","while/whereas = song song, đối lập (không nhất thiết có yếu tố bất ngờ)."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u09-l2-p1','b2-u09-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG: ''___ the bad weather, the event was a success.''","options":[{"id":"a","text":"Although"},{"id":"b","text":"Despite"},{"id":"c","text":"Even though"}],"correctOptionId":"b","explanationVi":"Sau despite → noun (the bad weather)."}'::jsonb),
 ('b2-u09-l2-p2','b2-u09-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''___ she was exhausted, she finished the marathon.''","acceptedAnswers":["Although","Even though","Though"],"explanationVi":"+ clause → although/even though/though."}'::jsonb),
 ('b2-u09-l2-p3','b2-u09-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"despite","right":"mặc dù (+ noun)"},{"left":"whereas","right":"trong khi đó (đối lập)"},{"left":"in spite of","right":"mặc dù (= despite)"},{"left":"concession","right":"sự nhượng bộ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l2-p4','b2-u09-l2','error_correction',4,'practice','medium',false,'{"question":"Sửa lỗi: ''Despite she was tired, she kept working.''","acceptedAnswers":["Despite being tired, she kept working.","Although she was tired, she kept working.","In spite of being tired, she kept working."],"explanationVi":"despite + V-ing hoặc thay bằng although + clause."}'::jsonb),
 ('b2-u09-l2-p5','b2-u09-l2','translation',5,'practice','medium',false,'{"question":"Dịch dùng despite: ''Mặc dù trời mưa, chúng tôi vẫn đi chơi.''","acceptedAnswers":["Despite the rain, we went out.","Despite it raining, we went out.","In spite of the rain, we went out."],"explanationVi":"Despite + the rain (noun)."}'::jsonb),
 ('b2-u09-l2-p6','b2-u09-l2','grammar_fill_blank',6,'practice','medium',false,'{"question":"Điền đúng (đối lập song song): ''Tom loves adventure, ___ his brother prefers staying home.''","acceptedAnswers":["whereas","while"],"explanationVi":"Đối lập song song → whereas / while."}'::jsonb),
 ('b2-u09-l2-p7','b2-u09-l2','multiple_choice',7,'practice','medium',false,'{"question":"''In spite of the fact that'' + ___:","options":[{"id":"a","text":"V-ing"},{"id":"b","text":"noun"},{"id":"c","text":"full clause (S + V)"}],"correctOptionId":"c","explanationVi":"in spite of the fact that + full clause."}'::jsonb),
 ('b2-u09-l2-q1','b2-u09-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG:","options":[{"id":"a","text":"Despite it was hard, she passed."},{"id":"b","text":"Despite the difficulty, she passed."},{"id":"c","text":"Despite that it was hard, she passed."}],"correctOptionId":"b","explanationVi":"Despite + noun: the difficulty."}'::jsonb),
 ('b2-u09-l2-q2','b2-u09-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''___ working full-time, she completed her degree.''","acceptedAnswers":["Despite","In spite of"],"explanationVi":"Despite/In spite of + V-ing."}'::jsonb),
 ('b2-u09-l2-q3','b2-u09-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Từ nào dùng đúng nhất để đối lập song song: ''She is creative ___ her colleague is analytical.''?","options":[{"id":"a","text":"although"},{"id":"b","text":"whereas"},{"id":"c","text":"despite"}],"correctOptionId":"b","explanationVi":"Đối lập song song = whereas."}'::jsonb),
 ('b2-u09-l2-q4','b2-u09-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Chuyển sang despite: ''Although the budget was small, they achieved a lot.'' →","acceptedAnswers":["Despite the small budget, they achieved a lot.","Despite having a small budget, they achieved a lot."],"explanationVi":"Despite + noun/V-ing."}'::jsonb),
 ('b2-u09-l2-q5','b2-u09-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"despite","right":"mặc dù (+ noun/V-ing)"},{"left":"whereas","right":"trong khi đó"},{"left":"nonetheless","right":"tuy vậy"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l2-q6','b2-u09-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["she","tired","Despite","being","working","kept"],"correctOrder":[2,3,0,4,1,5],"explanationVi":"Despite being tired, she kept working."}'::jsonb),
 ('b2-u09-l2-q7','b2-u09-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Điền đúng: ''___ the fact that funding was cut, the project continued.''","acceptedAnswers":["Despite","In spite of"],"explanationVi":"Despite/In spite of + the fact that + clause."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u09-l3','B2','reading','b2-u09','normal',3,'Emphasis & Cleft Sentences','It is/was... that/who — What... is/was',12,25,70,'{}'::jsonb,
  '{"warmup":"So sánh: ''I met John yesterday.'' vs ''It was John that I met yesterday.'' vs ''It was yesterday that I met John.'' — Cảm giác khác nhau chỗ nào?",
    "objectives":["Dùng it-cleft (It is/was + X + that/who...) để nhấn mạnh","Dùng what-cleft (What + S + V + is/was...) để nhấn mạnh","Nhận biết và dùng đúng cả hai dạng cleft sentence"],
    "grammarHtml":"<b>Cleft Sentences — câu phân tách nhấn mạnh:</b><br><b>It-cleft:</b> It is/was + [phần nhấn mạnh] + that/who + [phần còn lại]<br><i>I met John yesterday.</i><br>→ Nhấn John: <b>It was John that/whom I met yesterday.</b><br>→ Nhấn yesterday: <b>It was yesterday that I met John.</b><br>→ Nhấn I: <b>It was I who met John.</b> (trang trọng)<br><b>What-cleft (pseudo-cleft):</b> What + [S + V] + is/was + [noun phrase]<br><i>I need more time.</i> → <b>What I need is more time.</b><br><i>He did something strange.</i> → <b>What he did was (something) strange.</b><br><b>All-cleft:</b> All + S + V + is/was + to-infinitive/noun<br><i>All I want is a good night''s sleep.</i><br><b>Nhấn mạnh bằng inversion (đảo ngữ nhấn mạnh):</b><br>Never have I seen such a mess.<br>Not only did she pass, but she also got top marks.",
    "vocabBlock":[
      {"word":"cleft sentence","ipa":"/kleft ˈsentəns/","meaningVi":"câu phân tách (nhấn mạnh)","example":"It was the manager who made the decision."},
      {"word":"emphasis","ipa":"/ˈemfəsɪs/","meaningVi":"sự nhấn mạnh","example":"Place emphasis on the key points."},
      {"word":"inversion","ipa":"/ɪnˈvɜːʃn/","meaningVi":"sự đảo ngữ","example":"Inversion is used for emphasis."},
      {"word":"pseudo-cleft","ipa":"/ˈsjuːdəʊ kleft/","meaningVi":"câu phân tách giả (what-cleft)","example":"What surprised me was his reaction."}],
    "examples":[
      {"en":"It was the CEO who announced the restructuring.","vi":"Chính CEO là người thông báo về việc tái cơ cấu."},
      {"en":"It was the high cost that deterred investors.","vi":"Chính chi phí cao là điều làm các nhà đầu tư ngần ngại."},
      {"en":"What the company needs is better leadership.","vi":"Điều công ty cần là sự lãnh đạo tốt hơn."},
      {"en":"All I asked for was a simple explanation.","vi":"Tất cả những gì tôi yêu cầu chỉ là một lời giải thích đơn giản."}],
    "commonMistakes":["❌ It was John who did met her → ✅ It was John who met her (không dùng auxiliary sau who/that trong it-cleft)","What I need is/are: số ít/nhiều tùy vào noun sau là: What I need is time. / What I need are more resources.","All...is/was + to-infinitive hoặc noun."],
    "tips":["It-cleft = nhấn mạnh người, thời gian, địa điểm, lý do.","What-cleft = nhấn mạnh hành động hoặc điều gì đó trừu tượng.","Trong văn nói: rising intonation trên phần được nhấn mạnh."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u09-l3-p1','b2-u09-l3','multiple_choice',1,'practice','easy',false,'{"question":"Chuyển sang it-cleft nhấn mạnh ''the manager'': ''The manager signed the contract.''","options":[{"id":"a","text":"It was the manager which signed the contract."},{"id":"b","text":"It was the manager who signed the contract."},{"id":"c","text":"It was the manager that signed the contract."}],"correctOptionId":"b","explanationVi":"Nhấn người → It was + person + who."}'::jsonb),
 ('b2-u09-l3-p2','b2-u09-l3','grammar_fill_blank',2,'practice','easy',false,'{"question":"What-cleft: ''I need a better system.'' →","acceptedAnswers":["What I need is a better system."],"explanationVi":"What I need is... = pseudo-cleft."}'::jsonb),
 ('b2-u09-l3-p3','b2-u09-l3','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"cleft sentence","right":"câu phân tách nhấn mạnh"},{"left":"emphasis","right":"sự nhấn mạnh"},{"left":"inversion","right":"đảo ngữ"},{"left":"pseudo-cleft","right":"câu phân tách giả (what-cleft)"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l3-p4','b2-u09-l3','grammar_fill_blank',4,'practice','medium',false,'{"question":"Nhấn mạnh ''yesterday'': ''I saw her yesterday.'' →","acceptedAnswers":["It was yesterday that I saw her."],"explanationVi":"Nhấn thời gian → It was + time + that."}'::jsonb),
 ('b2-u09-l3-p5','b2-u09-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh dùng cleft:","sourceText":"Chính chi phí cao là điều ngăn chúng tôi tiến hành.","acceptedAnswers":["It was the high cost that prevented us from proceeding.","It was the high cost that stopped us from proceeding."],"explanationVi":"It was + high cost + that..."}'::jsonb),
 ('b2-u09-l3-p6','b2-u09-l3','multiple_choice',6,'practice','medium',false,'{"question":"Chọn câu what-cleft ĐÚNG: ''They need more funding.'' →","options":[{"id":"a","text":"What they need are more funding."},{"id":"b","text":"What they need is more funding."},{"id":"c","text":"What they needs is more funding."}],"correctOptionId":"b","explanationVi":"funding = uncountable → What they need IS."}'::jsonb),
 ('b2-u09-l3-p7','b2-u09-l3','grammar_fill_blank',7,'practice','medium',false,'{"question":"All-cleft: ''I want a good night''s sleep.'' →","acceptedAnswers":["All I want is a good night''s sleep."],"explanationVi":"All I want is... = all-cleft."}'::jsonb),
 ('b2-u09-l3-q1','b2-u09-l3','multiple_choice',8,'quiz','easy',true,'{"question":"It-cleft nhấn mạnh người dùng?","options":[{"id":"a","text":"that"},{"id":"b","text":"who"},{"id":"c","text":"which"}],"correctOptionId":"b","explanationVi":"Nhấn người → It was + person + WHO."}'::jsonb),
 ('b2-u09-l3-q2','b2-u09-l3','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Nhấn mạnh ''in 1969'': ''Humans first landed on the moon in 1969.'' →","acceptedAnswers":["It was in 1969 that humans first landed on the moon."],"explanationVi":"Nhấn thời gian → It was + time + that."}'::jsonb),
 ('b2-u09-l3-q3','b2-u09-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Câu what-cleft ĐÚNG: ''She enjoys reading.'' →","options":[{"id":"a","text":"What she enjoys is to read."},{"id":"b","text":"What she enjoys is reading."},{"id":"c","text":"What does she enjoy is reading."}],"correctOptionId":"b","explanationVi":"What she enjoys is + V-ing."}'::jsonb),
 ('b2-u09-l3-q4','b2-u09-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Nhấn ''the lack of funding'' làm vấn đề: ''The lack of funding caused the failure.'' →","acceptedAnswers":["It was the lack of funding that caused the failure."],"explanationVi":"It was + cause + that..."}'::jsonb),
 ('b2-u09-l3-q5','b2-u09-l3','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"cleft sentence","right":"câu phân tách"},{"left":"emphasis","right":"nhấn mạnh"},{"left":"inversion","right":"đảo ngữ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l3-q6','b2-u09-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng (what-cleft):","tokens":["is","What","better","the","communication","team","needs"],"correctOrder":[1,5,0,3,2,4,6],"explanationVi":"What the team needs is better communication."}'::jsonb),
 ('b2-u09-l3-q7','b2-u09-l3','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Nhấn ''the director'' quyết định: ''The director made the final call.'' →","acceptedAnswers":["It was the director who made the final call.","It was the director that made the final call."],"explanationVi":"It was + person + who/that."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u09-l4','B2','reading','b2-u09','normal',4,'The Climate Debate','Đọc hiểu: Tranh luận về khí hậu',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc bài tranh luận về biến đổi khí hậu — chú ý cách dùng discourse connectors, nhượng bộ và cleft sentences.",
    "objectives":["Đọc hiểu văn bản lập luận B2","Nhận biết connectors, concession/contrast và emphasis trong ngữ cảnh","Phân tích lập luận và phản lập luận"],
    "vocabBlock":[
      {"word":"urgent","ipa":"/ˈɜːdʒənt/","meaningVi":"cấp bách","example":"Climate change requires urgent action."},
      {"word":"mitigate","ipa":"/ˈmɪtɪɡeɪt/","meaningVi":"giảm thiểu","example":"We need to mitigate the effects."},
      {"word":"emission","ipa":"/ɪˈmɪʃn/","meaningVi":"sự phát thải","example":"Carbon emissions must be reduced."},
      {"word":"advocate","ipa":"/ˈædvəkət/","meaningVi":"người ủng hộ / vận động","example":"Environmental advocates demand action."}],
    "examples":[
      {"en":"Climate change is, without doubt, the most pressing issue of our time. What scientists agree on is that global temperatures are rising at an unprecedented rate. Despite decades of warnings, governments have been slow to act. Nevertheless, some progress has been made: renewable energy now accounts for a growing share of global power. It was the Paris Agreement that first established internationally binding emissions targets, though critics argue these are insufficient. Furthermore, while wealthier nations produce the most emissions, it is developing countries that suffer the greatest consequences. What is needed, therefore, is not simply technological innovation, but a fundamental shift in how we organise our economies. In spite of the challenges, advocates argue that the solutions exist — what is missing is the political will to implement them.","vi":"Biến đổi khí hậu là, không nghi ngờ gì, vấn đề cấp bách nhất của thời đại chúng ta. Điều mà các nhà khoa học đồng ý là nhiệt độ toàn cầu đang tăng với tốc độ chưa từng có. Mặc dù có nhiều thập kỷ cảnh báo, các chính phủ vẫn hành động chậm chạp. Tuy nhiên, một số tiến bộ đã được thực hiện: năng lượng tái tạo hiện chiếm tỷ lệ ngày càng tăng trong điện năng toàn cầu. Chính Thỏa thuận Paris là văn bản đầu tiên thiết lập các mục tiêu phát thải ràng buộc quốc tế, dù các nhà phê bình cho rằng chúng chưa đủ. Hơn nữa, trong khi các quốc gia giàu hơn tạo ra nhiều khí thải nhất, chính các nước đang phát triển lại phải chịu hậu quả lớn nhất. Do đó, điều cần thiết không chỉ là đổi mới công nghệ, mà là sự thay đổi căn bản trong cách chúng ta tổ chức nền kinh tế. Mặc dù có những thách thức, những người ủng hộ lập luận rằng các giải pháp tồn tại — điều còn thiếu là ý chí chính trị để thực hiện chúng."}],
    "commonMistakes":["Để ý: It was the Paris Agreement that... (it-cleft), What scientists agree on is... (what-cleft), despite/in spite of, nevertheless/furthermore."],
    "tips":["Văn bản lập luận thường dùng cleft sentences để nhấn mạnh điểm chính.","Chú ý: what is needed / what is missing = what-cleft nhấn mạnh chủ đề."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u09-l4-p1','b2-u09-l4','multiple_choice',1,'practice','easy',false,'{"question":"Theo bài, các nhà khoa học đồng ý điều gì?","options":[{"id":"a","text":"Biến đổi khí hậu sẽ ngưng lại"},{"id":"b","text":"Nhiệt độ toàn cầu đang tăng với tốc độ chưa từng có"},{"id":"c","text":"Năng lượng tái tạo không hiệu quả"}],"correctOptionId":"b","explanationVi":"''What scientists agree on is that global temperatures are rising at an unprecedented rate.''"}'::jsonb),
 ('b2-u09-l4-p2','b2-u09-l4','multiple_choice',2,'practice','easy',false,'{"question":"Cấu trúc nào trong ''It was the Paris Agreement that first established...''?","options":[{"id":"a","text":"What-cleft"},{"id":"b","text":"It-cleft"},{"id":"c","text":"All-cleft"}],"correctOptionId":"b","explanationVi":"It was + X + that = it-cleft."}'::jsonb),
 ('b2-u09-l4-p3','b2-u09-l4','multiple_choice',3,'practice','medium',false,'{"question":"Bài lập luận rằng nước nào phải chịu hậu quả lớn nhất?","options":[{"id":"a","text":"Các nước giàu"},{"id":"b","text":"Các nước đang phát triển"},{"id":"c","text":"Tất cả như nhau"}],"correctOptionId":"b","explanationVi":"''it is developing countries that suffer the greatest consequences.''"}'::jsonb),
 ('b2-u09-l4-p4','b2-u09-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"urgent","right":"cấp bách"},{"left":"mitigate","right":"giảm thiểu"},{"left":"emission","right":"sự phát thải"},{"left":"advocate","right":"người ủng hộ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l4-p5','b2-u09-l4','multiple_choice',5,'practice','medium',false,'{"question":"Câu ''What is needed is not simply technological innovation'' — nhấn mạnh điều gì?","options":[{"id":"a","text":"Công nghệ mới"},{"id":"b","text":"Sự thay đổi cần thiết (không chỉ công nghệ)"},{"id":"c","text":"Ý chí chính trị"}],"correctOptionId":"b","explanationVi":"What-cleft nhấn mạnh what is needed."}'::jsonb),
 ('b2-u09-l4-p6','b2-u09-l4','multiple_choice',6,'practice','medium',false,'{"question":"Connector nào trong bài chỉ TƯƠNG PHẢN song song?","options":[{"id":"a","text":"furthermore"},{"id":"b","text":"while (wealthier nations...developing countries)"},{"id":"c","text":"nevertheless"}],"correctOptionId":"b","explanationVi":"while = đối lập song song."}'::jsonb),
 ('b2-u09-l4-p7','b2-u09-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Hoàn thành what-cleft từ bài: ''___ is missing is the political will.''","acceptedAnswers":["What"],"explanationVi":"What is missing = what-cleft."}'::jsonb),
 ('b2-u09-l4-q1','b2-u09-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Tiến bộ nào được đề cập trong bài?","options":[{"id":"a","text":"Khí thải đã giảm một nửa"},{"id":"b","text":"Năng lượng tái tạo chiếm tỷ lệ ngày càng tăng"},{"id":"c","text":"Tất cả quốc gia đã đạt mục tiêu Paris"}],"correctOptionId":"b","explanationVi":"''renewable energy now accounts for a growing share.''"}'::jsonb),
 ('b2-u09-l4-q2','b2-u09-l4','multiple_choice',9,'quiz','easy',true,'{"question":"Bài kết luận rằng điều gì còn thiếu?","options":[{"id":"a","text":"Công nghệ"},{"id":"b","text":"Ý chí chính trị"},{"id":"c","text":"Tài chính"}],"correctOptionId":"b","explanationVi":"''what is missing is the political will.''"}'::jsonb),
 ('b2-u09-l4-q3','b2-u09-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Connector ''nevertheless'' trong bài chức năng gì?","options":[{"id":"a","text":"Thêm ý"},{"id":"b","text":"Nhân quả"},{"id":"c","text":"Đối lập nhượng bộ"}],"correctOptionId":"c","explanationVi":"nevertheless = tuy nhiên, dù vậy = đối lập."}'::jsonb),
 ('b2-u09-l4-q4','b2-u09-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành it-cleft: ''___ the Paris Agreement ___ established binding targets.''","acceptedAnswers":["It was / that"],"explanationVi":"It was... that = it-cleft."}'::jsonb),
 ('b2-u09-l4-q5','b2-u09-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Từ ''mitigate'' trong bài có nghĩa là?","options":[{"id":"a","text":"Tăng cường"},{"id":"b","text":"Giảm thiểu"},{"id":"c","text":"Ngăn chặn hoàn toàn"}],"correctOptionId":"b","explanationVi":"mitigate = giảm thiểu (không hoàn toàn ngăn chặn)."}'::jsonb),
 ('b2-u09-l4-q6','b2-u09-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"emission","right":"sự phát thải"},{"left":"urgent","right":"cấp bách"},{"left":"advocate","right":"người ủng hộ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l4-q7','b2-u09-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Chuyển sang what-cleft: ''The world needs strong leadership.'' →","acceptedAnswers":["What the world needs is strong leadership."],"explanationVi":"What the world needs is... = pseudo-cleft."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u09-l5','B2','reading','b2-u09','unit_review',5,'Unit 9 Review','Ôn tập Unit 9: Xây dựng lập luận',15,35,75,'{}'::jsonb,
  '{"warmup":"Ôn tập Unit 9: discourse connectors, concession/contrast và cleft sentences.","objectives":["Tổng hợp can-do Unit 9","Đạt ≥ 75% để hoàn thành Unit"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để qua Unit."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u09-l5-q1','b2-u09-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Điền connector đúng (kết quả): ''Sales fell sharply; ___, staff were laid off.''","acceptedAnswers":["consequently","therefore","hence","as a result"],"explanationVi":"Kết quả → consequently/therefore."}'::jsonb),
 ('b2-u09-l5-q2','b2-u09-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG: ''___ the heavy rain, the match continued.''","options":[{"id":"a","text":"Although"},{"id":"b","text":"Despite"},{"id":"c","text":"Even though"}],"correctOptionId":"b","explanationVi":"Despite + noun."}'::jsonb),
 ('b2-u09-l5-q3','b2-u09-l5','multiple_choice',3,'quiz','easy',true,'{"question":"It-cleft: nhấn người dùng từ gì?","options":[{"id":"a","text":"that"},{"id":"b","text":"who"},{"id":"c","text":"which"}],"correctOptionId":"b","explanationVi":"Nhấn người → It was + person + WHO."}'::jsonb),
 ('b2-u09-l5-q4','b2-u09-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"What-cleft: ''The country needs investment.'' →","acceptedAnswers":["What the country needs is investment."],"explanationVi":"What + S + V + is..."}'::jsonb),
 ('b2-u09-l5-q5','b2-u09-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào ĐÚNG (despite)?","options":[{"id":"a","text":"Despite she was tired, she finished."},{"id":"b","text":"Despite being tired, she finished."},{"id":"c","text":"Despite of being tired, she finished."}],"correctOptionId":"b","explanationVi":"Despite + V-ing (không có of)."}'::jsonb),
 ('b2-u09-l5-q6','b2-u09-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với chức năng:","pairs":[{"left":"furthermore","right":"thêm ý"},{"left":"whereas","right":"đối lập song song"},{"left":"consequently","right":"kết quả"},{"left":"nevertheless","right":"đối lập nhượng bộ"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u09-l5-q7','b2-u09-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Nhấn ''in 2020'' = ''It was ___ that the pandemic began.''","acceptedAnswers":["in 2020"],"explanationVi":"It was + time + that."}'::jsonb),
 ('b2-u09-l5-q8','b2-u09-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["is","What","time","need","more","we"],"correctOrder":[1,4,0,2,3,5],"explanationVi":"What we need is more time."}'::jsonb),
 ('b2-u09-l5-q9','b2-u09-l5','multiple_choice',9,'quiz','medium',true,'{"question":"Chuyển sang despite: ''Although the cost was high, they proceeded.'' →","options":[{"id":"a","text":"Despite the high cost, they proceeded."},{"id":"b","text":"Despite the cost was high, they proceeded."},{"id":"c","text":"Despite of the high cost, they proceeded."}],"correctOptionId":"a","explanationVi":"Despite + noun phrase."}'::jsonb),
 ('b2-u09-l5-q10','b2-u09-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Nhấn ''the CEO'' ra quyết định: ''The CEO made the announcement.'' →","acceptedAnswers":["It was the CEO who made the announcement.","It was the CEO that made the announcement."],"explanationVi":"It was + person + who/that."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u09-l5' WHERE id = 'b2-u09';
