-- ══════════════════════════════════════════════════════════════════════════
-- B2 Unit 10 — The More You Learn
-- Double Comparatives; Complex Comparisons; Global Issues vocab
-- ══════════════════════════════════════════════════════════════════════════

UPDATE learning_units SET review_lesson_id = NULL WHERE level_code = 'B2' AND id = 'b2-u10';
DELETE FROM learning_lesson_activities WHERE lesson_id IN (SELECT id FROM learning_lessons WHERE level_code = 'B2' AND unit_id = 'b2-u10');
DELETE FROM learning_lessons WHERE level_code = 'B2' AND unit_id = 'b2-u10';

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u10-l1','B2','reading','b2-u10','normal',1,'Double Comparatives','The more..., the more... — so sánh kép',12,25,70,'{}'::jsonb,
  '{"warmup":"''Bạn càng học nhiều, bạn càng biết ít'' — Câu này nói điều gì? Bạn nói câu này như thế nào trong tiếng Anh?",
    "objectives":["Dùng the + comparative, the + comparative để diễn đạt mối quan hệ tỷ lệ","Dùng the more/less/faster/better... với nhiều loại tính từ và trạng từ","Dùng đúng trật tự và cấu trúc trong cả hai mệnh đề"],
    "grammarHtml":"<b>Double Comparatives:</b><br>The + comparative + S + V, the + comparative + S + V<br><i>The more you practise, the better you become.</i><br><i>The harder she works, the more she earns.</i><br><b>Cấu trúc:</b><br>The more/less + [adjective/adverb] + S + V, the more/less + [adjective/adverb] + S + V<br>Hoặc với tính từ/trạng từ ngắn có dạng -er:<br>The harder, the faster, the sooner, the better, the longer, the cheaper...<br><b>Ví dụ với -er:</b><br>The longer you wait, the worse it gets.<br>The sooner we leave, the earlier we arrive.<br><b>Không có chủ ngữ (rút gọn):</b><br>The more, the merrier. (Càng nhiều càng vui)<br>The sooner, the better. (Càng sớm càng tốt)<br><b>Trật tự:</b> Mệnh đề 1 = điều kiện/nguyên nhân; mệnh đề 2 = kết quả.",
    "vocabBlock":[
      {"word":"the more...the more","ipa":"/ðə mɔː...ðə mɔː/","meaningVi":"càng...càng","example":"The more you read, the more you learn."},
      {"word":"proportional","ipa":"/prəˈpɔːʃənl/","meaningVi":"tỷ lệ thuận","example":"Effort and reward are proportional."},
      {"word":"diminish","ipa":"/dɪˈmɪnɪʃ/","meaningVi":"giảm bớt, thu nhỏ","example":"The gap between them diminished."},
      {"word":"accelerate","ipa":"/əkˈseləreɪt/","meaningVi":"tăng tốc","example":"The more we invest, the faster growth accelerates."},
      {"word":"compound","ipa":"/ˈkɒmpaʊnd/","meaningVi":"tổng hợp, cộng dồn","example":"Compound interest grows exponentially."}],
    "examples":[
      {"en":"The more you exercise, the healthier you become.","vi":"Bạn tập thể dục càng nhiều, bạn càng khỏe mạnh."},
      {"en":"The longer we delay action on climate change, the more expensive solutions will become.","vi":"Chúng ta càng trì hoãn hành động về biến đổi khí hậu, các giải pháp sẽ càng tốn kém."},
      {"en":"The harder the challenge, the greater the sense of achievement.","vi":"Thách thức càng khó, cảm giác thành tựu càng lớn."},
      {"en":"The sooner, the better — we shouldn''t delay any further.","vi":"Càng sớm càng tốt — chúng ta không nên trì hoãn thêm nữa."}],
    "commonMistakes":["❌ More you practise, more you improve. → ✅ The more you practise, the more you improve.","❌ The more harder → ✅ The harder (tính từ ngắn dùng -er trực tiếp)","Trật tự: điều kiện trước (The more you eat), kết quả sau (the fatter you get)."],
    "tips":["Cả hai mệnh đề đều có ''the'' + comparative.","Rút gọn (không chủ ngữ) chỉ dùng trong câu nói ngắn hoặc tục ngữ.","the more/less + tính từ dài; the -er + tính từ ngắn."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u10-l1-p1','b2-u10-l1','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG:","options":[{"id":"a","text":"More you study, more you learn."},{"id":"b","text":"The more you study, the more you learn."},{"id":"c","text":"The more you study, more you learn."}],"correctOptionId":"b","explanationVi":"Cả hai mệnh đề cần ''the''."}'::jsonb),
 ('b2-u10-l1-p2','b2-u10-l1','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''___ longer we wait, ___ worse the situation gets.''","acceptedAnswers":["The / the"],"explanationVi":"The...the = double comparative."}'::jsonb),
 ('b2-u10-l1-p3','b2-u10-l1','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"proportional","right":"tỷ lệ thuận"},{"left":"diminish","right":"giảm bớt"},{"left":"accelerate","right":"tăng tốc"},{"left":"compound","right":"cộng dồn"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l1-p4','b2-u10-l1','grammar_fill_blank',4,'practice','medium',false,'{"question":"Hoàn thành: ''The ___ (hard) the challenge, the ___ (great) the achievement.''","acceptedAnswers":["harder / greater"],"explanationVi":"Tính từ ngắn: harder, greater."}'::jsonb),
 ('b2-u10-l1-p5','b2-u10-l1','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Bạn càng thực hành nhiều, bạn càng tự tin hơn.","acceptedAnswers":["The more you practise, the more confident you become.","The more you practice, the more confident you get."],"explanationVi":"The more you practise, the more confident..."}'::jsonb),
 ('b2-u10-l1-p6','b2-u10-l1','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''The more harder you try, the more better the results.''","acceptedAnswers":["The harder you try, the better the results."],"explanationVi":"harder/better (không thêm more với -er form)."}'::jsonb),
 ('b2-u10-l1-p7','b2-u10-l1','multiple_choice',7,'practice','medium',false,'{"question":"Câu nào là rút gọn double comparative hợp lệ?","options":[{"id":"a","text":"More the merrier."},{"id":"b","text":"The more, the merrier."},{"id":"c","text":"More, merrier."}],"correctOptionId":"b","explanationVi":"Rút gọn: The more, the merrier."}'::jsonb),
 ('b2-u10-l1-q1','b2-u10-l1','multiple_choice',8,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG:","options":[{"id":"a","text":"The sooner we act, the better."},{"id":"b","text":"The sooner we act, better."},{"id":"c","text":"Sooner we act, the better."}],"correctOptionId":"a","explanationVi":"Cả hai mệnh đề cần ''the''."}'::jsonb),
 ('b2-u10-l1-q2','b2-u10-l1','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''___ more you invest now, ___ greater the returns later.''","acceptedAnswers":["The / the"],"explanationVi":"The...the."}'::jsonb),
 ('b2-u10-l1-q3','b2-u10-l1','multiple_choice',10,'quiz','medium',true,'{"question":"Dạng so sánh đúng trong ''The ___ we delay, the ___ we''ll suffer'':","options":[{"id":"a","text":"more longer / more worse"},{"id":"b","text":"longer / more"},{"id":"c","text":"longer / worse"}],"correctOptionId":"c","explanationVi":"longer (short adj), worse (irregular comparative)."}'::jsonb),
 ('b2-u10-l1-q4','b2-u10-l1','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành: ''The ___ (many) people attend, the ___ (successful) the event.''","acceptedAnswers":["more / more successful"],"explanationVi":"more people; more successful."}'::jsonb),
 ('b2-u10-l1-q5','b2-u10-l1','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"proportional","right":"tỷ lệ thuận"},{"left":"accelerate","right":"tăng tốc"},{"left":"diminish","right":"giảm bớt"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l1-q6','b2-u10-l1','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["you","The","become","exercise","healthier","more","the"],"correctOrder":[1,5,0,3,2,4,6],"explanationVi":"The more you exercise, the healthier you become."}'::jsonb),
 ('b2-u10-l1-q7','b2-u10-l1','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Dịch dùng double comparative: ''Càng trì hoãn, càng tốn kém.''","acceptedAnswers":["The longer we delay, the more expensive it becomes.","The more we delay, the more expensive it gets."],"explanationVi":"The longer/more...the more expensive."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u10-l2','B2','reading','b2-u10','normal',2,'Complex Comparisons','as...as; not as...as; far/much + comparative; the same as',12,25,70,'{}'::jsonb,
  '{"warmup":"''Không đắt bằng'' / ''đắt hơn nhiều'' / ''đắt như nhau'' — Tiếng Anh có nhiều cách so sánh mức độ. Bạn biết cấu trúc nào?",
    "objectives":["Dùng (not) as + adj/adv + as để so sánh bằng/không bằng","Dùng far/much/a lot/slightly/considerably + comparative để nhấn mức độ","Dùng the same as, similar to, different from, superior/inferior to"],
    "grammarHtml":"<b>Complex Comparisons:</b><br><b>So sánh bằng:</b> as + adj/adv + as<br><i>She is as talented as her sister.</i><br><b>Không bằng:</b> not as/so + adj/adv + as<br><i>This model isn''t as expensive as the other one.</i><br><b>Nhấn mức độ so sánh hơn:</b><br>far/much/a lot + comparative: <i>far more efficient, much cheaper</i><br>slightly/a little + comparative: <i>slightly better, a little faster</i><br>considerably/significantly + comparative: <i>considerably higher, significantly worse</i><br><b>Bằng nhau:</b> the same as, as much/many...as<br><i>The results are the same as last year''s.</i><br><b>Tương tự/khác biệt:</b><br>similar to, identical to, different from<br><i>This approach is similar to the one used in 2020.</i><br><b>Hơn/kém (trang trọng):</b><br>superior to, inferior to, preferable to<br><i>Option A is superior to Option B in terms of cost.</i>",
    "vocabBlock":[
      {"word":"considerably","ipa":"/kənˈsɪdərəbli/","meaningVi":"đáng kể, đáng kể hơn","example":"The new model is considerably faster."},
      {"word":"marginally","ipa":"/ˈmɑːdʒɪnəli/","meaningVi":"không đáng kể, hơi","example":"Prices are marginally higher this month."},
      {"word":"superior to","ipa":"/suːˈpɪəriə tə/","meaningVi":"tốt hơn, cao cấp hơn (trang trọng)","example":"Quality A is superior to Quality B."},
      {"word":"inferior to","ipa":"/ɪnˈfɪəriə tə/","meaningVi":"kém hơn (trang trọng)","example":"This product is inferior to the original."},
      {"word":"identical to","ipa":"/aɪˈdentɪkl tə/","meaningVi":"giống hệt","example":"The results are identical to last year''s."}],
    "examples":[
      {"en":"Electric vehicles are not as expensive as they were five years ago.","vi":"Xe điện không đắt bằng năm năm trước."},
      {"en":"The new treatment is far more effective than the old one.","vi":"Phương pháp điều trị mới hiệu quả hơn nhiều so với phương pháp cũ."},
      {"en":"The company''s performance was considerably better than expected.","vi":"Hiệu suất của công ty tốt hơn đáng kể so với dự kiến."},
      {"en":"This solution is preferable to the one proposed last year.","vi":"Giải pháp này tốt hơn giải pháp được đề xuất năm ngoái."}],
    "commonMistakes":["❌ more cheaper → ✅ much cheaper (không dùng more với -er form)","superior/inferior/preferable + TO (không dùng than): superior to, not superior than.","not as...as (more common) / not so...as (more formal)."],
    "tips":["far/much = nhấn mạnh mức độ lớn.","slightly/marginally = khác biệt nhỏ.","superior/inferior/preferable + to (preposition)."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u10-l2-p1','b2-u10-l2','multiple_choice',1,'practice','easy',false,'{"question":"Chọn câu ĐÚNG (không bằng): ''This phone isn''t ___ expensive ___ the other.''","options":[{"id":"a","text":"more / than"},{"id":"b","text":"as / as"},{"id":"c","text":"so / than"}],"correctOptionId":"b","explanationVi":"Not as...as = không bằng."}'::jsonb),
 ('b2-u10-l2-p2','b2-u10-l2','grammar_fill_blank',2,'practice','easy',false,'{"question":"Điền đúng: ''The new system is ___ (far / efficient) than the old one.''","acceptedAnswers":["far more efficient"],"explanationVi":"far more + long adjective."}'::jsonb),
 ('b2-u10-l2-p3','b2-u10-l2','vocabulary_match',3,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"considerably","right":"đáng kể"},{"left":"marginally","right":"không đáng kể"},{"left":"superior to","right":"tốt hơn (trang trọng)"},{"left":"inferior to","right":"kém hơn"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l2-p4','b2-u10-l2','grammar_fill_blank',4,'practice','medium',false,'{"question":"Điền đúng (trang trọng): ''Option A is ___ Option B in terms of reliability.''","acceptedAnswers":["superior to","preferable to"],"explanationVi":"superior to / preferable to + noun."}'::jsonb),
 ('b2-u10-l2-p5','b2-u10-l2','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Kết quả tốt hơn đáng kể so với dự kiến.","acceptedAnswers":["The results were considerably better than expected.","The results were significantly better than expected."],"explanationVi":"considerably/significantly + comparative + than."}'::jsonb),
 ('b2-u10-l2-p6','b2-u10-l2','error_correction',6,'practice','medium',false,'{"question":"Sửa lỗi: ''This design is superior than the previous one.''","acceptedAnswers":["This design is superior to the previous one."],"explanationVi":"superior TO (không dùng than)."}'::jsonb),
 ('b2-u10-l2-p7','b2-u10-l2','multiple_choice',7,'practice','medium',false,'{"question":"Điền từ nhấn mạnh khác biệt NHỎ: ''The new version is ___ faster.''","options":[{"id":"a","text":"far"},{"id":"b","text":"slightly"},{"id":"c","text":"considerably"}],"correctOptionId":"b","explanationVi":"slightly/marginally = khác biệt nhỏ."}'::jsonb),
 ('b2-u10-l2-q1','b2-u10-l2','multiple_choice',8,'quiz','easy',true,'{"question":"Câu nào có nghĩa là ''kém bằng''?","options":[{"id":"a","text":"as good as"},{"id":"b","text":"not as good as"},{"id":"c","text":"better than"}],"correctOptionId":"b","explanationVi":"not as good as = kém hơn/không bằng."}'::jsonb),
 ('b2-u10-l2-q2','b2-u10-l2','grammar_fill_blank',9,'quiz','easy',true,'{"question":"Điền đúng: ''The new drug is ___ more effective than the old one.''","acceptedAnswers":["far","much","a lot","considerably","significantly"],"explanationVi":"far/much/considerably + more effective."}'::jsonb),
 ('b2-u10-l2-q3','b2-u10-l2','multiple_choice',10,'quiz','medium',true,'{"question":"Câu nào ĐÚNG?","options":[{"id":"a","text":"This is more preferable than that."},{"id":"b","text":"This is preferable to that."},{"id":"c","text":"This is preferable than that."}],"correctOptionId":"b","explanationVi":"preferable TO (không dùng than; không thêm more)."}'::jsonb),
 ('b2-u10-l2-q4','b2-u10-l2','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền đúng: ''The two samples are almost ___ to each other.''","acceptedAnswers":["identical"],"explanationVi":"identical to = giống hệt."}'::jsonb),
 ('b2-u10-l2-q5','b2-u10-l2','vocabulary_match',12,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"identical to","right":"giống hệt"},{"left":"considerably","right":"đáng kể"},{"left":"inferior to","right":"kém hơn"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l2-q6','b2-u10-l2','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["the","is","new","far","efficient","system","more"],"correctOrder":[3,0,2,1,6,5,4],"explanationVi":"The new system is far more efficient."}'::jsonb),
 ('b2-u10-l2-q7','b2-u10-l2','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Dịch: ''Cách tiếp cận này không tốt bằng cách trước.'' →","acceptedAnswers":["This approach is not as good as the previous one.","This approach isn''t as effective as the previous one."],"explanationVi":"not as...as = không bằng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u10-l3','B2','reading','b2-u10','normal',3,'Global Issues Vocabulary','Từ vựng vấn đề toàn cầu B2',12,25,70,'{}'::jsonb,
  '{"warmup":"Bạn có quan tâm đến các vấn đề toàn cầu không? Nghèo đói, bất bình đẳng, biến đổi khí hậu... Bạn biết những từ nào?",
    "objectives":["Học 10 từ vựng B2 về vấn đề toàn cầu","Dùng từ trong ngữ cảnh so sánh và lập luận","Phân biệt sắc thái từ về quy mô và tác động"],
    "vocabBlock":[
      {"word":"inequality","ipa":"/ˌɪnɪˈkwɒlɪti/","meaningVi":"bất bình đẳng","example":"Income inequality is growing worldwide."},
      {"word":"poverty","ipa":"/ˈpɒvəti/","meaningVi":"nghèo đói","example":"Millions still live in extreme poverty."},
      {"word":"displacement","ipa":"/dɪsˈpleɪsmənt/","meaningVi":"sự di dời, di cư cưỡng bức","example":"Conflict causes mass displacement."},
      {"word":"deforestation","ipa":"/ˌdiːˌfɒrɪˈsteɪʃn/","meaningVi":"nạn phá rừng","example":"Deforestation is accelerating in tropical regions."},
      {"word":"biodiversity","ipa":"/ˌbaɪəʊdaɪˈvɜːsɪti/","meaningVi":"đa dạng sinh học","example":"We must protect biodiversity."},
      {"word":"humanitarian","ipa":"/hjuːˌmænɪˈteəriən/","meaningVi":"nhân đạo","example":"Humanitarian aid was sent to the region."},
      {"word":"sanitation","ipa":"/ˌsænɪˈteɪʃn/","meaningVi":"vệ sinh môi trường","example":"Access to clean water and sanitation is a basic right."},
      {"word":"governance","ipa":"/ˈɡʌvənəns/","meaningVi":"quản trị, điều hành","example":"Good governance reduces corruption."},
      {"word":"disparity","ipa":"/dɪˈspærɪti/","meaningVi":"sự chênh lệch, khác biệt","example":"The disparity between rich and poor is growing."},
      {"word":"sustainable development","ipa":"/səˈsteɪnəbl dɪˈveləpmənt/","meaningVi":"phát triển bền vững","example":"The UN promotes sustainable development."}],
    "examples":[
      {"en":"The disparity between developed and developing nations is far greater than it was fifty years ago.","vi":"Sự chênh lệch giữa các nước phát triển và đang phát triển lớn hơn nhiều so với năm mươi năm trước."},
      {"en":"The more we invest in education, the less inequality societies tend to experience.","vi":"Chúng ta đầu tư vào giáo dục càng nhiều, xã hội càng ít bất bình đẳng."},
      {"en":"Deforestation is not as severe in countries with strong environmental governance.","vi":"Nạn phá rừng không nghiêm trọng bằng ở các nước có quản trị môi trường mạnh."}],
    "commonMistakes":["inequality (bất bình đẳng) ≠ inequity (sự không công bằng): overlap nhưng không đồng nghĩa hoàn toàn.","disparity = chênh lệch (thường về số lượng/tỷ lệ); inequality = bất bình đẳng (về quyền, cơ hội).","sanitation (vệ sinh môi trường) ≠ hygiene (vệ sinh cá nhân)."],
    "tips":["sustainable development + goals = SDGs (17 mục tiêu phát triển bền vững của LHQ).","humanitarian + aid/crisis/organisation.","governance + good/poor/corporate/environmental."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u10-l3-p1','b2-u10-l3','vocabulary_match',1,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"inequality","right":"bất bình đẳng"},{"left":"poverty","right":"nghèo đói"},{"left":"deforestation","right":"nạn phá rừng"},{"left":"biodiversity","right":"đa dạng sinh học"}],"explanationVi":"Từ vựng toàn cầu."}'::jsonb),
 ('b2-u10-l3-p2','b2-u10-l3','vocabulary_match',2,'practice','easy',false,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"humanitarian","right":"nhân đạo"},{"left":"sanitation","right":"vệ sinh môi trường"},{"left":"governance","right":"quản trị"},{"left":"disparity","right":"sự chênh lệch"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l3-p3','b2-u10-l3','multiple_choice',3,'practice','easy',false,'{"question":"Điền từ đúng: ''Millions of people were forced into ___ due to conflict.''","options":[{"id":"a","text":"displacement"},{"id":"b","text":"governance"},{"id":"c","text":"sanitation"}],"correctOptionId":"a","explanationVi":"displacement = di dời cưỡng bức."}'::jsonb),
 ('b2-u10-l3-p4','b2-u10-l3','multiple_choice',4,'practice','medium',false,'{"question":"Điền từ đúng: ''The ___ between urban and rural incomes has widened.''","options":[{"id":"a","text":"biodiversity"},{"id":"b","text":"disparity"},{"id":"c","text":"displacement"}],"correctOptionId":"b","explanationVi":"disparity = sự chênh lệch."}'::jsonb),
 ('b2-u10-l3-p5','b2-u10-l3','translation',5,'practice','medium',false,'{"question":"Dịch sang tiếng Anh:","sourceText":"Chúng ta cần đầu tư vào phát triển bền vững để giảm nghèo đói.","acceptedAnswers":["We need to invest in sustainable development to reduce poverty.","We must invest in sustainable development to combat poverty."],"explanationVi":"sustainable development + reduce poverty."}'::jsonb),
 ('b2-u10-l3-p6','b2-u10-l3','multiple_choice',6,'practice','medium',false,'{"question":"''The UN promotes ___ development'' — điền từ đúng:","options":[{"id":"a","text":"humanitarian"},{"id":"b","text":"sustainable"},{"id":"c","text":"deforestation"}],"correctOptionId":"b","explanationVi":"sustainable development = phát triển bền vững."}'::jsonb),
 ('b2-u10-l3-p7','b2-u10-l3','vocabulary_match',7,'practice','easy',false,'{"question":"Nối từ còn lại:","pairs":[{"left":"sustainable development","right":"phát triển bền vững"},{"left":"displacement","right":"di dời cưỡng bức"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l3-q1','b2-u10-l3','vocabulary_match',8,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"deforestation","right":"nạn phá rừng"},{"left":"governance","right":"quản trị"},{"left":"disparity","right":"sự chênh lệch"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l3-q2','b2-u10-l3','multiple_choice',9,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''bất bình đẳng''?","options":[{"id":"a","text":"sanitation"},{"id":"b","text":"inequality"},{"id":"c","text":"displacement"}],"correctOptionId":"b","explanationVi":"inequality = bất bình đẳng."}'::jsonb),
 ('b2-u10-l3-q3','b2-u10-l3','multiple_choice',10,'quiz','medium',true,'{"question":"Điền từ đúng: ''___ aid organisations responded to the crisis.''","options":[{"id":"a","text":"Humanitarian"},{"id":"b","text":"Sustainable"},{"id":"c","text":"Deforestation"}],"correctOptionId":"a","explanationVi":"humanitarian aid = viện trợ nhân đạo."}'::jsonb),
 ('b2-u10-l3-q4','b2-u10-l3','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Điền từ đúng: ''Access to clean water and ___ is a fundamental human right.''","acceptedAnswers":["sanitation"],"explanationVi":"sanitation = vệ sinh môi trường."}'::jsonb),
 ('b2-u10-l3-q5','b2-u10-l3','multiple_choice',12,'quiz','medium',true,'{"question":"''Biodiversity'' đề cập đến điều gì?","options":[{"id":"a","text":"Năng lượng tái tạo"},{"id":"b","text":"Sự đa dạng của các loài sinh vật"},{"id":"c","text":"Phát triển bền vững"}],"correctOptionId":"b","explanationVi":"biodiversity = đa dạng sinh học."}'::jsonb),
 ('b2-u10-l3-q6','b2-u10-l3','sentence_ordering',13,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng:","tokens":["growing","Income","is","worldwide","inequality"],"correctOrder":[1,0,2,3,4],"explanationVi":"Income inequality is growing worldwide."}'::jsonb),
 ('b2-u10-l3-q7','b2-u10-l3','vocabulary_match',14,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"poverty","right":"nghèo đói"},{"left":"biodiversity","right":"đa dạng sinh học"},{"left":"sustainable development","right":"phát triển bền vững"}],"explanationVi":"Ghép đúng."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u10-l4','B2','reading','b2-u10','normal',4,'A Changing World','Đọc hiểu B2 tổng hợp: Thế giới đang thay đổi',12,25,70,'{}'::jsonb,
  '{"warmup":"Đọc bài về những thay đổi trên thế giới — bài tổng hợp toàn bộ B2: comparatives, cleft, connectors, relative clauses...",
    "objectives":["Đọc hiểu văn bản B2 tổng hợp","Nhận biết các cấu trúc B2 trong ngữ cảnh thực tế","Trả lời câu hỏi suy luận và phân tích"],
    "vocabBlock":[
      {"word":"unprecedented","ipa":"/ʌnˈpresɪdentɪd/","meaningVi":"chưa từng có","example":"Change is occurring at an unprecedented rate."},
      {"word":"interconnected","ipa":"/ˌɪntəkəˈnektɪd/","meaningVi":"liên kết với nhau","example":"The world''s economies are deeply interconnected."},
      {"word":"disparity","ipa":"/dɪˈspærɪti/","meaningVi":"sự chênh lệch","example":"The disparity between countries is enormous."},
      {"word":"tackle","ipa":"/ˈtækl/","meaningVi":"giải quyết (vấn đề khó)","example":"We must tackle inequality head-on."}],
    "examples":[
      {"en":"The world is changing faster than at any previous point in history. What is striking is not just the speed of change, but its scope — technological, environmental, social, and political transformations are occurring simultaneously, each making the others more complex. The disparity between the world''s wealthiest and poorest people is considerably greater than it was a generation ago. Furthermore, the consequences of this inequality are not distributed equally: it is the most vulnerable populations that suffer the most from climate change, conflict, and inadequate sanitation. Nevertheless, the picture is not entirely bleak. The more governments invest in education and renewable energy, the more resilient their societies become. What is needed is not simply more money, but smarter governance — systems whereby resources reach those who need them most. Having ratified international agreements on sustainable development, many countries are now making measurable progress. The question remaining is whether the world''s most powerful nations will act with the urgency that the situation demands.","vi":"Thế giới đang thay đổi nhanh hơn bất kỳ thời điểm nào trước đây trong lịch sử. Điều nổi bật không chỉ là tốc độ thay đổi, mà còn là phạm vi — các biến đổi công nghệ, môi trường, xã hội và chính trị đang xảy ra đồng thời, mỗi biến đổi làm cho những biến đổi khác phức tạp hơn. Sự chênh lệch giữa những người giàu nhất và nghèo nhất thế giới lớn hơn đáng kể so với một thế hệ trước. Hơn nữa, hậu quả của sự bất bình đẳng này không được phân bổ đều: chính những nhóm dân số dễ bị tổn thương nhất là những người chịu đựng nhiều nhất từ biến đổi khí hậu, xung đột và vệ sinh không đầy đủ. Tuy nhiên, bức tranh không hoàn toàn u ám. Chính phủ đầu tư vào giáo dục và năng lượng tái tạo càng nhiều, xã hội của họ càng trở nên kiên cường. Điều cần thiết không chỉ là nhiều tiền hơn, mà là quản trị thông minh hơn — các hệ thống mà theo đó tài nguyên đến tay những người cần nhất. Sau khi phê chuẩn các thỏa thuận quốc tế về phát triển bền vững, nhiều quốc gia hiện đang đạt được tiến bộ có thể đo lường. Câu hỏi còn lại là liệu các quốc gia quyền lực nhất thế giới có hành động với sự khẩn cấp mà tình hình đòi hỏi không."}],
    "commonMistakes":["Chú ý: What is striking (what-cleft), it is...that (it-cleft), whereby (relative), Having ratified (participle), The more...the more (double comparative)."],
    "tips":["Văn bản B2 tổng hợp dùng nhiều cấu trúc phức tạp cùng lúc.","Khi đọc học thuật: tìm cleft sentences để hiểu điểm nhấn của tác giả."]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u10-l4-p1','b2-u10-l4','multiple_choice',1,'practice','easy',false,'{"question":"Theo bài, điều gì nổi bật nhất về thay đổi hiện nay?","options":[{"id":"a","text":"Chỉ có tốc độ"},{"id":"b","text":"Không chỉ tốc độ mà còn phạm vi"},{"id":"c","text":"Chỉ ảnh hưởng đến công nghệ"}],"correctOptionId":"b","explanationVi":"''not just the speed of change, but its scope.''"}'::jsonb),
 ('b2-u10-l4-p2','b2-u10-l4','multiple_choice',2,'practice','easy',false,'{"question":"Nhóm nào chịu hậu quả nhiều nhất từ bất bình đẳng?","options":[{"id":"a","text":"Các nước giàu"},{"id":"b","text":"Nhóm dân số dễ bị tổn thương nhất"},{"id":"c","text":"Các tập đoàn lớn"}],"correctOptionId":"b","explanationVi":"''it is the most vulnerable populations that suffer the most.''"}'::jsonb),
 ('b2-u10-l4-p3','b2-u10-l4','multiple_choice',3,'practice','medium',false,'{"question":"Cấu trúc ''What is needed is not simply more money'' là?","options":[{"id":"a","text":"It-cleft"},{"id":"b","text":"What-cleft (pseudo-cleft)"},{"id":"c","text":"Double comparative"}],"correctOptionId":"b","explanationVi":"What is needed is... = what-cleft."}'::jsonb),
 ('b2-u10-l4-p4','b2-u10-l4','vocabulary_match',4,'practice','easy',false,'{"question":"Nối từ trong bài với nghĩa:","pairs":[{"left":"unprecedented","right":"chưa từng có"},{"left":"interconnected","right":"liên kết"},{"left":"disparity","right":"sự chênh lệch"},{"left":"tackle","right":"giải quyết"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l4-p5','b2-u10-l4','multiple_choice',5,'practice','medium',false,'{"question":"''Having ratified international agreements'' là cấu trúc gì?","options":[{"id":"a","text":"Reduced relative clause"},{"id":"b","text":"Perfect participle clause (hành động trước)"},{"id":"c","text":"Non-defining clause"}],"correctOptionId":"b","explanationVi":"Having + V3 = participle clause, hành động trước."}'::jsonb),
 ('b2-u10-l4-p6','b2-u10-l4','multiple_choice',6,'practice','medium',false,'{"question":"Bài kết thúc bằng câu hỏi về điều gì?","options":[{"id":"a","text":"Liệu công nghệ có giải quyết được vấn đề"},{"id":"b","text":"Liệu các nước quyền lực có hành động đủ khẩn cấp"},{"id":"c","text":"Khi nào sẽ đạt mục tiêu phát triển bền vững"}],"correctOptionId":"b","explanationVi":"''whether the world''s most powerful nations will act with the urgency.''"}'::jsonb),
 ('b2-u10-l4-p7','b2-u10-l4','grammar_fill_blank',7,'practice','medium',false,'{"question":"Double comparative trong bài: ''The more governments invest in education, ___ resilient their societies become.''","acceptedAnswers":["the more"],"explanationVi":"the more...the more."}'::jsonb),
 ('b2-u10-l4-q1','b2-u10-l4','multiple_choice',8,'quiz','easy',true,'{"question":"Theo bài, sự chênh lệch giàu nghèo hiện nay như thế nào so với thế hệ trước?","options":[{"id":"a","text":"Nhỏ hơn"},{"id":"b","text":"Như cũ"},{"id":"c","text":"Lớn hơn đáng kể"}],"correctOptionId":"c","explanationVi":"''considerably greater than it was a generation ago.''"}'::jsonb),
 ('b2-u10-l4-q2','b2-u10-l4','multiple_choice',9,'quiz','easy',true,'{"question":"''It is the most vulnerable populations that suffer the most'' — nhấn mạnh điều gì?","options":[{"id":"a","text":"Mức độ đau khổ"},{"id":"b","text":"Nhóm người chịu nhiều nhất"},{"id":"c","text":"Nguyên nhân đau khổ"}],"correctOptionId":"b","explanationVi":"It-cleft nhấn mạnh: it is + the most vulnerable + that."}'::jsonb),
 ('b2-u10-l4-q3','b2-u10-l4','multiple_choice',10,'quiz','medium',true,'{"question":"Relative pronoun nào trong ''systems whereby resources reach those who need them''?","options":[{"id":"a","text":"who"},{"id":"b","text":"whereby"},{"id":"c","text":"Cả hai"}],"correctOptionId":"c","explanationVi":"whereby (system) và who (those who need)."}'::jsonb),
 ('b2-u10-l4-q4','b2-u10-l4','grammar_fill_blank',11,'quiz','medium',true,'{"question":"Hoàn thành double comparative từ bài: ''___ more governments invest, ___ more resilient societies become.''","acceptedAnswers":["The / the"],"explanationVi":"The more...the more."}'::jsonb),
 ('b2-u10-l4-q5','b2-u10-l4','multiple_choice',12,'quiz','medium',true,'{"question":"Từ ''unprecedented'' trong bài có nghĩa là?","options":[{"id":"a","text":"Chậm, thận trọng"},{"id":"b","text":"Chưa từng có, vô tiền khoáng hậu"},{"id":"c","text":"Có thể dự đoán"}],"correctOptionId":"b","explanationVi":"unprecedented = chưa từng xảy ra trước đây."}'::jsonb),
 ('b2-u10-l4-q6','b2-u10-l4','vocabulary_match',13,'quiz','easy',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"tackle","right":"giải quyết"},{"left":"interconnected","right":"liên kết"},{"left":"unprecedented","right":"chưa từng có"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l4-q7','b2-u10-l4','grammar_fill_blank',14,'quiz','hard',true,'{"question":"Viết what-cleft: ''Thế giới cần sự lãnh đạo thông minh hơn.'' →","acceptedAnswers":["What the world needs is smarter leadership.","What the world needs is better governance."],"explanationVi":"What the world needs is..."}'::jsonb);

INSERT INTO learning_lessons (id, level_code, skill_code, unit_id, lesson_type, lesson_order, title, subtitle, duration_minutes, xp_reward, required_score_to_pass, content, theory_content) VALUES
 ('b2-u10-l5','B2','reading','b2-u10','unit_review',5,'Unit 10 Review — B2 Final','Ôn tập Unit 10 & Tổng kết B2',20,50,75,'{}'::jsonb,
  '{"warmup":"Chúc mừng! Đây là bài ôn tập cuối cùng của B2. Hãy tổng hợp những gì bạn đã học.",
    "objectives":["Tổng hợp can-do Unit 10 và toàn bộ B2","Đạt ≥ 75% để hoàn thành B2","Sẵn sàng cho level C1"],"vocabBlock":[],"examples":[],"commonMistakes":[],"tips":["Cần đúng ≥ 8/10 để hoàn thành B2. Chúc mừng khi đạt mục tiêu!"]}'::jsonb);

INSERT INTO learning_lesson_activities (id, lesson_id, activity_type, display_order, phase, difficulty, counts_toward_mastery, payload) VALUES
 ('b2-u10-l5-q1','b2-u10-l5','grammar_fill_blank',1,'quiz','easy',true,'{"question":"Điền đúng: ''___ more you learn, ___ more opportunities you have.''","acceptedAnswers":["The / the"],"explanationVi":"Double comparative: The more...the more."}'::jsonb),
 ('b2-u10-l5-q2','b2-u10-l5','multiple_choice',2,'quiz','easy',true,'{"question":"Chọn câu ĐÚNG (considerably):","options":[{"id":"a","text":"The results were more considerable better."},{"id":"b","text":"The results were considerably better."},{"id":"c","text":"The results were considerable better."}],"correctOptionId":"b","explanationVi":"considerably + comparative."}'::jsonb),
 ('b2-u10-l5-q3','b2-u10-l5','multiple_choice',3,'quiz','easy',true,'{"question":"Từ nào có nghĩa là ''bất bình đẳng''?","options":[{"id":"a","text":"disparity"},{"id":"b","text":"inequality"},{"id":"c","text":"displacement"}],"correctOptionId":"b","explanationVi":"inequality = bất bình đẳng."}'::jsonb),
 ('b2-u10-l5-q4','b2-u10-l5','grammar_fill_blank',4,'quiz','medium',true,'{"question":"What-cleft: ''The world needs better governance.'' →","acceptedAnswers":["What the world needs is better governance."],"explanationVi":"What the world needs is..."}'::jsonb),
 ('b2-u10-l5-q5','b2-u10-l5','multiple_choice',5,'quiz','medium',true,'{"question":"Câu nào ĐÚNG (superior):","options":[{"id":"a","text":"Option A is superior than Option B."},{"id":"b","text":"Option A is more superior to Option B."},{"id":"c","text":"Option A is superior to Option B."}],"correctOptionId":"c","explanationVi":"superior TO (không dùng than, không thêm more)."}'::jsonb),
 ('b2-u10-l5-q6','b2-u10-l5','vocabulary_match',6,'quiz','medium',true,'{"question":"Nối từ với nghĩa:","pairs":[{"left":"deforestation","right":"nạn phá rừng"},{"left":"governance","right":"quản trị"},{"left":"humanitarian","right":"nhân đạo"},{"left":"disparity","right":"sự chênh lệch"}],"explanationVi":"Ghép đúng."}'::jsonb),
 ('b2-u10-l5-q7','b2-u10-l5','grammar_fill_blank',7,'quiz','medium',true,'{"question":"Điền đúng: ''The gap between rich and poor is ___ greater than before.''","acceptedAnswers":["considerably","far","much","significantly"],"explanationVi":"considerably/far/much + greater."}'::jsonb),
 ('b2-u10-l5-q8','b2-u10-l5','sentence_ordering',8,'quiz','hard',true,'{"question":"Sắp xếp thành câu đúng (double comparative):","tokens":["invest","societies","more","governments","resilient","The","become","the","more"],"correctOrder":[5,2,0,3,8,1,4,7,6],"explanationVi":"The more governments invest, the more resilient societies become."}'::jsonb),
 ('b2-u10-l5-q9','b2-u10-l5','multiple_choice',9,'quiz','medium',true,'{"question":"''It is education that makes the greatest difference.'' — Cấu trúc này nhấn mạnh điều gì?","options":[{"id":"a","text":"Kết quả của giáo dục"},{"id":"b","text":"Giáo dục là nhân tố quan trọng nhất"},{"id":"c","text":"Sự khác biệt là lớn"}],"correctOptionId":"b","explanationVi":"It-cleft nhấn mạnh: it is + education + that."}'::jsonb),
 ('b2-u10-l5-q10','b2-u10-l5','grammar_fill_blank',10,'quiz','hard',true,'{"question":"Dịch dùng double comparative: ''Chúng ta hành động càng sớm, hậu quả càng ít nghiêm trọng.''","acceptedAnswers":["The sooner we act, the less severe the consequences will be.","The sooner we act, the less serious the consequences."],"explanationVi":"The sooner...the less severe."}'::jsonb);

UPDATE learning_units SET review_lesson_id = 'b2-u10-l5' WHERE id = 'b2-u10';
