-- =============================================================================
-- V70 — Seed câu hỏi Reading cho Placement Test (A1–C1).
-- =============================================================================
-- CAT đánh giá 3 kỹ năng: grammar + vocabulary + reading (listening bỏ — chưa có audio host).
--   * Mỗi câu reading có passage (đoạn văn) + 1 câu hỏi đọc hiểu 4 đáp án.
--   * difficulty = b_i theo cấp: A1=-2.0, A2=-1.0, B1=0.0, B2=1.0, C1=2.0.
--   * skill_category = 'reading' (lowercase, khớp filter findForCat).
--   * 4 câu/cấp × 5 cấp = 20 câu → đủ cho CAT cân đều 3 skill trong 15 câu.
-- =============================================================================

-- ── A1 — reading (4) ─────────────────────────────────────────────────────────
INSERT INTO questions (id, cefr_level, skill_category, question, options, correct_answer, explanation, passage, difficulty, created_at) VALUES
    (gen_random_uuid(), 'A1', 'reading', 'What is Tom''s pet?',                 '{"A":"a cat","B":"a dog","C":"a bird","D":"a fish"}'::jsonb,                'B', 'Doan van: "Tom has a dog."',                'Tom has a dog. The dog is brown. It likes to run in the park.',                          -2.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'A1', 'reading', 'What color is the dog?',              '{"A":"black","B":"white","C":"brown","D":"red"}'::jsonb,                    'C', 'Doan van: "The dog is brown."',             'Tom has a dog. The dog is brown. It likes to run in the park.',                          -2.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'A1', 'reading', 'Where does Mary go on Monday?',       '{"A":"home","B":"school","C":"shop","D":"park"}'::jsonb,                    'B', 'Doan van: "On Monday she goes to school."', 'Mary is a student. On Monday she goes to school. She likes English.',                      -2.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'A1', 'reading', 'What does Mary like?',                '{"A":"math","B":"music","C":"English","D":"art"}'::jsonb,                   'C', 'Doan van: "She likes English."',           'Mary is a student. On Monday she goes to school. She likes English.',                      -2.0, CURRENT_TIMESTAMP);

-- ── A2 — reading (4) ─────────────────────────────────────────────────────────
INSERT INTO questions (id, cefr_level, skill_category, question, options, correct_answer, explanation, passage, difficulty, created_at) VALUES
    (gen_random_uuid(), 'A2', 'reading', 'When did Anna visit her grandmother?', '{"A":"last week","B":"yesterday","C":"last weekend","D":"today"}'::jsonb,  'C', 'Doan van: "Last weekend Anna visited..."',  'Last weekend Anna visited her grandmother. They cooked dinner and watched a film together.', -1.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'A2', 'reading', 'What did they do together?',          '{"A":"cooked and watched a film","B":"played games","C":"went shopping","D":"read books"}'::jsonb, 'A', 'Doan van neu ro hai hoat dong.',     'Last weekend Anna visited her grandmother. They cooked dinner and watched a film together.', -1.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'A2', 'reading', 'How does Ben go to work?',            '{"A":"by car","B":"by bus","C":"by bike","D":"on foot"}'::jsonb,            'C', 'Doan van: "Ben rides his bike to work."',  'Ben rides his bike to work every day because it is cheap and good for his health.',        -1.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'A2', 'reading', 'Why does Ben cycle?',                 '{"A":"it is fast","B":"it is cheap and healthy","C":"he has no car","D":"it is fun"}'::jsonb, 'B', 'Doan van: "cheap and good for his health".', 'Ben rides his bike to work every day because it is cheap and good for his health.',        -1.0, CURRENT_TIMESTAMP);

-- ── B1 — reading (4) ─────────────────────────────────────────────────────────
INSERT INTO questions (id, cefr_level, skill_category, question, options, correct_answer, explanation, passage, difficulty, created_at) VALUES
    (gen_random_uuid(), 'B1', 'reading', 'Why was the trip delayed?',          '{"A":"bad weather","B":"a strike","C":"a broken bus","D":"illness"}'::jsonb, 'A', 'Doan van: "because of heavy rain".',       'The school trip to the mountains was delayed because of heavy rain. Students waited two hours before the buses finally left.', 0.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'B1', 'reading', 'How long did students wait?',        '{"A":"one hour","B":"two hours","C":"three hours","D":"all day"}'::jsonb,   'B', 'Doan van: "waited two hours".',           'The school trip to the mountains was delayed because of heavy rain. Students waited two hours before the buses finally left.', 0.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'B1', 'reading', 'What is the main idea of the text?',  '{"A":"online shopping is growing","B":"shops are closing","C":"prices are rising","D":"delivery is slow"}'::jsonb, 'A', 'Y chinh: online shopping tang truong.', 'More and more people buy clothes and food online. Online shopping is growing fast because it saves time and offers many choices.', 0.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'B1', 'reading', 'Why is online shopping popular?',    '{"A":"it is cheaper only","B":"it saves time and offers choices","C":"shops are far","D":"it is safer"}'::jsonb, 'B', 'Doan van: "saves time and offers many choices".', 'More and more people buy clothes and food online. Online shopping is growing fast because it saves time and offers many choices.', 0.0, CURRENT_TIMESTAMP);

-- ── B2 — reading (4) ─────────────────────────────────────────────────────────
INSERT INTO questions (id, cefr_level, skill_category, question, options, correct_answer, explanation, passage, difficulty, created_at) VALUES
    (gen_random_uuid(), 'B2', 'reading', 'What does the author suggest about remote work?', '{"A":"it harms productivity","B":"it has both benefits and drawbacks","C":"it should be banned","D":"it suits everyone"}'::jsonb, 'B', 'Tac gia neu ca loi va hai.', 'Remote work offers flexibility and saves commuting time, yet it can blur the line between professional and personal life, leaving some employees feeling they never truly switch off.', 1.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'B2', 'reading', 'What is a drawback mentioned?',      '{"A":"lower pay","B":"longer commute","C":"difficulty switching off","D":"less flexibility"}'::jsonb, 'C', 'Doan van: "never truly switch off".', 'Remote work offers flexibility and saves commuting time, yet it can blur the line between professional and personal life, leaving some employees feeling they never truly switch off.', 1.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'B2', 'reading', 'What tone does the writer take towards the festival?', '{"A":"critical","B":"enthusiastic","C":"neutral","D":"sarcastic"}'::jsonb, 'B', 'Tu ngu "vibrant, unforgettable" -> nhiet tinh.', 'The annual film festival was a vibrant celebration of independent cinema, drawing crowds from around the world and offering an unforgettable experience for both directors and fans.', 1.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'B2', 'reading', 'Who attended the festival?',         '{"A":"only directors","B":"only fans","C":"directors and fans","D":"local students"}'::jsonb, 'C', 'Doan van: "both directors and fans".', 'The annual film festival was a vibrant celebration of independent cinema, drawing crowds from around the world and offering an unforgettable experience for both directors and fans.', 1.0, CURRENT_TIMESTAMP);

-- ── C1 — reading (4) ─────────────────────────────────────────────────────────
INSERT INTO questions (id, cefr_level, skill_category, question, options, correct_answer, explanation, passage, difficulty, created_at) VALUES
    (gen_random_uuid(), 'C1', 'reading', 'What is the writer''s primary argument?', '{"A":"technology always improves life","B":"unchecked automation may widen inequality","C":"machines cannot replace humans","D":"jobs are increasing"}'::jsonb, 'B', 'Luan diem chinh: automation lam tang bat binh dang.', 'While automation promises efficiency, critics caution that, left unchecked, it may concentrate wealth among those who own the technology, thereby widening the gap between rich and poor.', 2.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'C1', 'reading', 'The word "unchecked" most nearly means:', '{"A":"unverified","B":"unrestrained","C":"unexpected","D":"unpaid"}'::jsonb, 'B', 'Unchecked = khong bi kiem soat (unrestrained).', 'While automation promises efficiency, critics caution that, left unchecked, it may concentrate wealth among those who own the technology, thereby widening the gap between rich and poor.', 2.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'C1', 'reading', 'What can be inferred about the policy?', '{"A":"it was universally praised","B":"it faced nuanced criticism despite good intentions","C":"it was abandoned","D":"it had no effect"}'::jsonb, 'B', 'Suy luan: chinh sach bi phe binh tinh te du thien chi.', 'Though the reform was introduced with laudable intentions, its implementation proved so convoluted that even its staunchest supporters conceded the outcomes fell short of expectations.', 2.0, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'C1', 'reading', 'What does "conceded" imply here?',   '{"A":"strongly denied","B":"reluctantly admitted","C":"loudly celebrated","D":"completely ignored"}'::jsonb, 'B', 'Conceded = mien cuong thua nhan.', 'Though the reform was introduced with laudable intentions, its implementation proved so convoluted that even its staunchest supporters conceded the outcomes fell short of expectations.', 2.0, CURRENT_TIMESTAMP);
